# -*- coding: utf-8 -*-

# https://fontawesome.com

import bkt
from bkt.library.powerpoint import PPTSymbolsGallery


symbols_communication_5 = [
    ("Font Awesome 5 Free Regular", u"\uf2b9", "address book"),
    ("Font Awesome 5 Free Regular", u"\uf2bb", "address card"),
    ("Font Awesome 5 Free Regular", u"\uf2c1", "id badge"),
    ("Font Awesome 5 Free Regular", u"\uf2c2", "id card"),
    ("Font Awesome 5 Free Solid", u"\uf183", "man"),
    ("Font Awesome 5 Free Solid", u"\uf0c0", "users"),
    ("Font Awesome 5 Free Regular", u"\uf2bd", "user circle"),
    ("Font Awesome 5 Free Regular", u"\uf007", "user"),
    ("Font Awesome 5 Free Solid", u"\uf007", "user solid"),
    ("Font Awesome 5 Free Regular", u"\uf2b5", "handshake"),
    ("Font Awesome 5 Free Regular", u"\uf075", "comment"),
    ("Font Awesome 5 Free Regular", u"\uf4ad", "commenting"),
    ("Font Awesome 5 Free Regular", u"\uf086", "comments"),
    ("Font Awesome 5 Free Solid", u"\uf086", "comments"),
]


symbols_itsystems_5 = [
    
    ("Font Awesome 5 Free Solid", u"\uf108", "desktop"),
    ("Font Awesome 5 Free Solid", u"\uf109", "laptop"),
    ("Font Awesome 5 Free Solid", u"\uf3fa", "tablet"),
    ("Font Awesome 5 Free Solid", u"\uf3cd", "mobile"),
    ("Font Awesome 5 Free Solid", u"\uf095", "phone"),
    ("Font Awesome 5 Free Solid", u"\uf1ac", "fax"),
    ("Font Awesome 5 Free Regular", u"\uf0e0", "mail"),
    ("Font Awesome 5 Free Solid", u"\uf01c", "inbox"),
    ("Font Awesome 5 Free Regular", u"\uf11c", "keyboard"),
    
    ("Font Awesome 5 Free Solid", u"\uf0c2", "cloud"),
    ("Font Awesome 5 Free Solid", u"\uf09e", "rss"),
    ("Font Awesome 5 Free Solid", u"\uf1eb", "wifi"),
    
    ("Font Awesome 5 Free Solid", u"\uf2f6", "sign in"),
    ("Font Awesome 5 Free Solid", u"\uf084", "key"),
    ("Font Awesome 5 Free Solid", u"\uf023", "lock"),
    ("Font Awesome 5 Free Solid", u"\uf09c", "unlock"),
    ("Font Awesome 5 Free Solid", u"\uf13e", "unlock"),
    ("Font Awesome 5 Free Solid", u"\uf3ed", "shield"),
    
    ("Font Awesome 5 Free Solid", u"\uf19c", "university/bank"),
    ("Font Awesome 5 Free Solid", u"\uf015", "home"),
    ("Font Awesome 5 Free Solid", u"\uf1ad", "building"),
    
    ("Font Awesome 5 Free Solid", u"\uf1b2", "cube"),
    ("Font Awesome 5 Free Solid", u"\uf1b3", "cubes"),
    ("Font Awesome 5 Free Solid", u"\uf1c0", "database"),
    ("Font Awesome 5 Free Solid", u"\uf233", "server"),
    ("Font Awesome 5 Free Solid", u"\uf2db", "microchip"),
    
    ("Font Awesome 5 Free Solid", u"\uf188", "bug"),
]

symbols_files_5 = [
    ("Font Awesome 5 Free Regular", u"\uf07b", "folder"),
    ("Font Awesome 5 Free Regular", u"\uf07c", "folder open"),
    ("Font Awesome 5 Free Regular", u"\uf15b", "file"),
    ("Font Awesome 5 Free Regular", u"\uf0c5", "files"),
    ("Font Awesome 5 Free Regular", u"\uf15c", "text"),
    ("Font Awesome 5 Free Regular", u"\uf1c9", "code"),
    ("Font Awesome 5 Free Regular", u"\uf1c6", "archive"),
    ("Font Awesome 5 Free Regular", u"\uf1c5", "image"),
    ("Font Awesome 5 Free Regular", u"\uf1c8", "video"),
    ("Font Awesome 5 Free Regular", u"\uf1c7", "audio"),
    ("Font Awesome 5 Free Regular", u"\uf1c1", "pdf"),
    ("Font Awesome 5 Free Regular", u"\uf1c3", "excel"),
    ("Font Awesome 5 Free Regular", u"\uf1c4", "powerpoint"),
    ("Font Awesome 5 Free Regular", u"\uf1c2", "word"),
]

symbols_analysis_5 = [
    ("Font Awesome 5 Free Regular", u"\uf080", "bar chart"),
    ("Font Awesome 5 Free Solid", u"\uf200", "pie chart"),
    ("Font Awesome 5 Free Solid", u"\uf201", "line chart"),
    ("Font Awesome 5 Free Solid", u"\uf1fe", "area chart"),
    ("Font Awesome 5 Free Solid", u"\uf02a", "barcode"),
    ("Font Awesome 5 Free Solid", u"\uf24e", "balance"),
    
    ("Font Awesome 5 Free Solid", u"\uf005", "star"),
    ("Font Awesome 5 Free Solid", u"\uf5c0", "star half"),
    ("Font Awesome 5 Free Regular", u"\uf005", "star empty"),
    ("Font Awesome 5 Free Solid", u"\uf251", "hourglass start"),
    ("Font Awesome 5 Free Solid", u"\uf252", "hourglass half"),
    ("Font Awesome 5 Free Solid", u"\uf253", "hourglass end"),
    
    ("Font Awesome 5 Free Solid", u"\uf244", "battery empty"),
    ("Font Awesome 5 Free Solid", u"\uf243", "battery 1/4"),
    ("Font Awesome 5 Free Solid", u"\uf242", "battery 1/2"),
    ("Font Awesome 5 Free Solid", u"\uf241", "battery 3/4"),
    ("Font Awesome 5 Free Solid", u"\uf240", "battery full"),
    ("Font Awesome 5 Free Solid", u"\uf05e", "ban"),

    ("Font Awesome 5 Free Regular", u"\uf164", "thumbs up"),
    ("Font Awesome 5 Free Regular", u"\uf165", "thumbs down"),
    ("Font Awesome 5 Free Solid", u"\uf164", "thumbs up"),
    ("Font Awesome 5 Free Solid", u"\uf165", "thumbs down"),
    
    ("Font Awesome 5 Free Regular", u"\uf14a", "check square"),
    ("Font Awesome 5 Free Regular", u"\uf058", "check circle"),
    ("Font Awesome 5 Free Solid", u"\uf00c", "check"),
    ("Font Awesome 5 Free Solid", u"\uf00d", "x"),
]


symbols_mixed_5 = [
    ("Font Awesome 5 Free Solid", u"\uf0d0", "magic"),
    ("Font Awesome 5 Free Solid", u"\uf02d", "book"),
    ("Font Awesome 5 Free Solid", u"\uf02e", "bookmark"),
    ("Font Awesome 5 Free Solid", u"\uf0b1", "briefcase"),
    ("Font Awesome 5 Free Solid", u"\uf140", "bullseye"),
    ("Font Awesome 5 Free Regular", u"\uf073", "calendar"),
    ("Font Awesome 5 Free Solid", u"\uf0a3", "certificate"),
    ("Font Awesome 5 Free Regular", u"\uf017", "clock"),
    ("Font Awesome 5 Free Solid", u"\uf013", "cog"),
    ("Font Awesome 5 Free Solid", u"\uf085", "cogs"),
    ("Font Awesome 5 Free Solid", u"\uf134", "fire extinguisher"),
    ("Font Awesome 5 Free Solid", u"\uf277", "map signs"),
    ("Font Awesome 5 Free Solid", u"\uf041", "map marker"),
    ("Font Awesome 5 Free Regular", u"\uf1ea", "newspaper"),
    ("Font Awesome 5 Free Regular", u"\uf0eb", "lightbulb"),
    ("Font Awesome 5 Free Solid", u"\uf08d", "pin"),
    ("Font Awesome 5 Free Solid", u"\uf074", "random"),
    ("Font Awesome 5 Free Solid", u"\uf1b8", "recycle"),
    ("Font Awesome 5 Free Solid", u"\uf021", "refresh"),
    ("Font Awesome 5 Free Solid", u"\uf135", "rocket"),
    ("Font Awesome 5 Free Solid", u"\uf002", "search"),
    ("Font Awesome 5 Free Solid", u"\uf3fd", "tachometer"),
    ("Font Awesome 5 Free Solid", u"\uf02b", "tag"),
    ("Font Awesome 5 Free Solid", u"\uf02c", "tags"),
    ("Font Awesome 5 Free Regular", u"\uf2ed", "trash"),
    ("Font Awesome 5 Free Solid", u"\uf0ad", "wrench"),
]


# icons from metadata, version fontawesome-free-5.4.1-desktop
fa5_icons = [
    ("500px", u"\uf26e" , [ "brands" ] ),
    ("accessible-icon", u"\uf368" , [ "brands" ] ),
    ("accusoft", u"\uf369" , [ "brands" ] ),
    ("acquisitions-incorporated", u"\uf6af" , [ "brands" ] ),
    ("ad", u"\uf641" , [ "solid" ] ),
    ("address-book", u"\uf2b9" , [ "solid", "regular" ] ),
    ("address-card", u"\uf2bb" , [ "solid", "regular" ] ),
    ("adjust", u"\uf042" , [ "solid" ] ),
    ("adn", u"\uf170" , [ "brands" ] ),
    ("adversal", u"\uf36a" , [ "brands" ] ),
    ("affiliatetheme", u"\uf36b" , [ "brands" ] ),
    ("air-freshener", u"\uf5d0" , [ "solid" ] ),
    ("algolia", u"\uf36c" , [ "brands" ] ),
    ("align-center", u"\uf037" , [ "solid" ] ),
    ("align-justify", u"\uf039" , [ "solid" ] ),
    ("align-left", u"\uf036" , [ "solid" ] ),
    ("align-right", u"\uf038" , [ "solid" ] ),
    ("alipay", u"\uf642" , [ "brands" ] ),
    ("allergies", u"\uf461" , [ "solid" ] ),
    ("amazon", u"\uf270" , [ "brands" ] ),
    ("amazon-pay", u"\uf42c" , [ "brands" ] ),
    ("ambulance", u"\uf0f9" , [ "solid" ] ),
    ("american-sign-language-interpreting", u"\uf2a3" , [ "solid" ] ),
    ("amilia", u"\uf36d" , [ "brands" ] ),
    ("anchor", u"\uf13d" , [ "solid" ] ),
    ("android", u"\uf17b" , [ "brands" ] ),
    ("angellist", u"\uf209" , [ "brands" ] ),
    ("angle-double-down", u"\uf103" , [ "solid" ] ),
    ("angle-double-left", u"\uf100" , [ "solid" ] ),
    ("angle-double-right", u"\uf101" , [ "solid" ] ),
    ("angle-double-up", u"\uf102" , [ "solid" ] ),
    ("angle-down", u"\uf107" , [ "solid" ] ),
    ("angle-left", u"\uf104" , [ "solid" ] ),
    ("angle-right", u"\uf105" , [ "solid" ] ),
    ("angle-up", u"\uf106" , [ "solid" ] ),
    ("angry", u"\uf556" , [ "solid", "regular" ] ),
    ("angrycreative", u"\uf36e" , [ "brands" ] ),
    ("angular", u"\uf420" , [ "brands" ] ),
    ("ankh", u"\uf644" , [ "solid" ] ),
    ("app-store", u"\uf36f" , [ "brands" ] ),
    ("app-store-ios", u"\uf370" , [ "brands" ] ),
    ("apper", u"\uf371" , [ "brands" ] ),
    ("apple", u"\uf179" , [ "brands" ] ),
    ("apple-alt", u"\uf5d1" , [ "solid" ] ),
    ("apple-pay", u"\uf415" , [ "brands" ] ),
    ("archive", u"\uf187" , [ "solid" ] ),
    ("archway", u"\uf557" , [ "solid" ] ),
    ("arrow-alt-circle-down", u"\uf358" , [ "solid", "regular" ] ),
    ("arrow-alt-circle-left", u"\uf359" , [ "solid", "regular" ] ),
    ("arrow-alt-circle-right", u"\uf35a" , [ "solid", "regular" ] ),
    ("arrow-alt-circle-up", u"\uf35b" , [ "solid", "regular" ] ),
    ("arrow-circle-down", u"\uf0ab" , [ "solid" ] ),
    ("arrow-circle-left", u"\uf0a8" , [ "solid" ] ),
    ("arrow-circle-right", u"\uf0a9" , [ "solid" ] ),
    ("arrow-circle-up", u"\uf0aa" , [ "solid" ] ),
    ("arrow-down", u"\uf063" , [ "solid" ] ),
    ("arrow-left", u"\uf060" , [ "solid" ] ),
    ("arrow-right", u"\uf061" , [ "solid" ] ),
    ("arrow-up", u"\uf062" , [ "solid" ] ),
    ("arrows-alt", u"\uf0b2" , [ "solid" ] ),
    ("arrows-alt-h", u"\uf337" , [ "solid" ] ),
    ("arrows-alt-v", u"\uf338" , [ "solid" ] ),
    ("assistive-listening-systems", u"\uf2a2" , [ "solid" ] ),
    ("asterisk", u"\uf069" , [ "solid" ] ),
    ("asymmetrik", u"\uf372" , [ "brands" ] ),
    ("at", u"\uf1fa" , [ "solid" ] ),
    ("atlas", u"\uf558" , [ "solid" ] ),
    ("atom", u"\uf5d2" , [ "solid" ] ),
    ("audible", u"\uf373" , [ "brands" ] ),
    ("audio-description", u"\uf29e" , [ "solid" ] ),
    ("autoprefixer", u"\uf41c" , [ "brands" ] ),
    ("avianex", u"\uf374" , [ "brands" ] ),
    ("aviato", u"\uf421" , [ "brands" ] ),
    ("award", u"\uf559" , [ "solid" ] ),
    ("aws", u"\uf375" , [ "brands" ] ),
    ("backspace", u"\uf55a" , [ "solid" ] ),
    ("backward", u"\uf04a" , [ "solid" ] ),
    ("balance-scale", u"\uf24e" , [ "solid" ] ),
    ("ban", u"\uf05e" , [ "solid" ] ),
    ("band-aid", u"\uf462" , [ "solid" ] ),
    ("bandcamp", u"\uf2d5" , [ "brands" ] ),
    ("barcode", u"\uf02a" , [ "solid" ] ),
    ("bars", u"\uf0c9" , [ "solid" ] ),
    ("baseball-ball", u"\uf433" , [ "solid" ] ),
    ("basketball-ball", u"\uf434" , [ "solid" ] ),
    ("bath", u"\uf2cd" , [ "solid" ] ),
    ("battery-empty", u"\uf244" , [ "solid" ] ),
    ("battery-full", u"\uf240" , [ "solid" ] ),
    ("battery-half", u"\uf242" , [ "solid" ] ),
    ("battery-quarter", u"\uf243" , [ "solid" ] ),
    ("battery-three-quarters", u"\uf241" , [ "solid" ] ),
    ("bed", u"\uf236" , [ "solid" ] ),
    ("beer", u"\uf0fc" , [ "solid" ] ),
    ("behance", u"\uf1b4" , [ "brands" ] ),
    ("behance-square", u"\uf1b5" , [ "brands" ] ),
    ("bell", u"\uf0f3" , [ "solid", "regular" ] ),
    ("bell-slash", u"\uf1f6" , [ "solid", "regular" ] ),
    ("bezier-curve", u"\uf55b" , [ "solid" ] ),
    ("bible", u"\uf647" , [ "solid" ] ),
    ("bicycle", u"\uf206" , [ "solid" ] ),
    ("bimobject", u"\uf378" , [ "brands" ] ),
    ("binoculars", u"\uf1e5" , [ "solid" ] ),
    ("birthday-cake", u"\uf1fd" , [ "solid" ] ),
    ("bitbucket", u"\uf171" , [ "brands" ] ),
    ("bitcoin", u"\uf379" , [ "brands" ] ),
    ("bity", u"\uf37a" , [ "brands" ] ),
    ("black-tie", u"\uf27e" , [ "brands" ] ),
    ("blackberry", u"\uf37b" , [ "brands" ] ),
    ("blender", u"\uf517" , [ "solid" ] ),
    ("blender-phone", u"\uf6b6" , [ "solid" ] ),
    ("blind", u"\uf29d" , [ "solid" ] ),
    ("blogger", u"\uf37c" , [ "brands" ] ),
    ("blogger-b", u"\uf37d" , [ "brands" ] ),
    ("bluetooth", u"\uf293" , [ "brands" ] ),
    ("bluetooth-b", u"\uf294" , [ "brands" ] ),
    ("bold", u"\uf032" , [ "solid" ] ),
    ("bolt", u"\uf0e7" , [ "solid" ] ),
    ("bomb", u"\uf1e2" , [ "solid" ] ),
    ("bone", u"\uf5d7" , [ "solid" ] ),
    ("bong", u"\uf55c" , [ "solid" ] ),
    ("book", u"\uf02d" , [ "solid" ] ),
    ("book-dead", u"\uf6b7" , [ "solid" ] ),
    ("book-open", u"\uf518" , [ "solid" ] ),
    ("book-reader", u"\uf5da" , [ "solid" ] ),
    ("bookmark", u"\uf02e" , [ "solid", "regular" ] ),
    ("bowling-ball", u"\uf436" , [ "solid" ] ),
    ("box", u"\uf466" , [ "solid" ] ),
    ("box-open", u"\uf49e" , [ "solid" ] ),
    ("boxes", u"\uf468" , [ "solid" ] ),
    ("braille", u"\uf2a1" , [ "solid" ] ),
    ("brain", u"\uf5dc" , [ "solid" ] ),
    ("briefcase", u"\uf0b1" , [ "solid" ] ),
    ("briefcase-medical", u"\uf469" , [ "solid" ] ),
    ("broadcast-tower", u"\uf519" , [ "solid" ] ),
    ("broom", u"\uf51a" , [ "solid" ] ),
    ("brush", u"\uf55d" , [ "solid" ] ),
    ("btc", u"\uf15a" , [ "brands" ] ),
    ("bug", u"\uf188" , [ "solid" ] ),
    ("building", u"\uf1ad" , [ "solid", "regular" ] ),
    ("bullhorn", u"\uf0a1" , [ "solid" ] ),
    ("bullseye", u"\uf140" , [ "solid" ] ),
    ("burn", u"\uf46a" , [ "solid" ] ),
    ("buromobelexperte", u"\uf37f" , [ "brands" ] ),
    ("bus", u"\uf207" , [ "solid" ] ),
    ("bus-alt", u"\uf55e" , [ "solid" ] ),
    ("business-time", u"\uf64a" , [ "solid" ] ),
    ("buysellads", u"\uf20d" , [ "brands" ] ),
    ("calculator", u"\uf1ec" , [ "solid" ] ),
    ("calendar", u"\uf133" , [ "solid", "regular" ] ),
    ("calendar-alt", u"\uf073" , [ "solid", "regular" ] ),
    ("calendar-check", u"\uf274" , [ "solid", "regular" ] ),
    ("calendar-minus", u"\uf272" , [ "solid", "regular" ] ),
    ("calendar-plus", u"\uf271" , [ "solid", "regular" ] ),
    ("calendar-times", u"\uf273" , [ "solid", "regular" ] ),
    ("camera", u"\uf030" , [ "solid" ] ),
    ("camera-retro", u"\uf083" , [ "solid" ] ),
    ("campground", u"\uf6bb" , [ "solid" ] ),
    ("cannabis", u"\uf55f" , [ "solid" ] ),
    ("capsules", u"\uf46b" , [ "solid" ] ),
    ("car", u"\uf1b9" , [ "solid" ] ),
    ("car-alt", u"\uf5de" , [ "solid" ] ),
    ("car-battery", u"\uf5df" , [ "solid" ] ),
    ("car-crash", u"\uf5e1" , [ "solid" ] ),
    ("car-side", u"\uf5e4" , [ "solid" ] ),
    ("caret-down", u"\uf0d7" , [ "solid" ] ),
    ("caret-left", u"\uf0d9" , [ "solid" ] ),
    ("caret-right", u"\uf0da" , [ "solid" ] ),
    ("caret-square-down", u"\uf150" , [ "solid", "regular" ] ),
    ("caret-square-left", u"\uf191" , [ "solid", "regular" ] ),
    ("caret-square-right", u"\uf152" , [ "solid", "regular" ] ),
    ("caret-square-up", u"\uf151" , [ "solid", "regular" ] ),
    ("caret-up", u"\uf0d8" , [ "solid" ] ),
    ("cart-arrow-down", u"\uf218" , [ "solid" ] ),
    ("cart-plus", u"\uf217" , [ "solid" ] ),
    ("cat", u"\uf6be" , [ "solid" ] ),
    ("cc-amazon-pay", u"\uf42d" , [ "brands" ] ),
    ("cc-amex", u"\uf1f3" , [ "brands" ] ),
    ("cc-apple-pay", u"\uf416" , [ "brands" ] ),
    ("cc-diners-club", u"\uf24c" , [ "brands" ] ),
    ("cc-discover", u"\uf1f2" , [ "brands" ] ),
    ("cc-jcb", u"\uf24b" , [ "brands" ] ),
    ("cc-mastercard", u"\uf1f1" , [ "brands" ] ),
    ("cc-paypal", u"\uf1f4" , [ "brands" ] ),
    ("cc-stripe", u"\uf1f5" , [ "brands" ] ),
    ("cc-visa", u"\uf1f0" , [ "brands" ] ),
    ("centercode", u"\uf380" , [ "brands" ] ),
    ("certificate", u"\uf0a3" , [ "solid" ] ),
    ("chair", u"\uf6c0" , [ "solid" ] ),
    ("chalkboard", u"\uf51b" , [ "solid" ] ),
    ("chalkboard-teacher", u"\uf51c" , [ "solid" ] ),
    ("charging-station", u"\uf5e7" , [ "solid" ] ),
    ("chart-area", u"\uf1fe" , [ "solid" ] ),
    ("chart-bar", u"\uf080" , [ "solid", "regular" ] ),
    ("chart-line", u"\uf201" , [ "solid" ] ),
    ("chart-pie", u"\uf200" , [ "solid" ] ),
    ("check", u"\uf00c" , [ "solid" ] ),
    ("check-circle", u"\uf058" , [ "solid", "regular" ] ),
    ("check-double", u"\uf560" , [ "solid" ] ),
    ("check-square", u"\uf14a" , [ "solid", "regular" ] ),
    ("chess", u"\uf439" , [ "solid" ] ),
    ("chess-bishop", u"\uf43a" , [ "solid" ] ),
    ("chess-board", u"\uf43c" , [ "solid" ] ),
    ("chess-king", u"\uf43f" , [ "solid" ] ),
    ("chess-knight", u"\uf441" , [ "solid" ] ),
    ("chess-pawn", u"\uf443" , [ "solid" ] ),
    ("chess-queen", u"\uf445" , [ "solid" ] ),
    ("chess-rook", u"\uf447" , [ "solid" ] ),
    ("chevron-circle-down", u"\uf13a" , [ "solid" ] ),
    ("chevron-circle-left", u"\uf137" , [ "solid" ] ),
    ("chevron-circle-right", u"\uf138" , [ "solid" ] ),
    ("chevron-circle-up", u"\uf139" , [ "solid" ] ),
    ("chevron-down", u"\uf078" , [ "solid" ] ),
    ("chevron-left", u"\uf053" , [ "solid" ] ),
    ("chevron-right", u"\uf054" , [ "solid" ] ),
    ("chevron-up", u"\uf077" , [ "solid" ] ),
    ("child", u"\uf1ae" , [ "solid" ] ),
    ("chrome", u"\uf268" , [ "brands" ] ),
    ("church", u"\uf51d" , [ "solid" ] ),
    ("circle", u"\uf111" , [ "solid", "regular" ] ),
    ("circle-notch", u"\uf1ce" , [ "solid" ] ),
    ("city", u"\uf64f" , [ "solid" ] ),
    ("clipboard", u"\uf328" , [ "solid", "regular" ] ),
    ("clipboard-check", u"\uf46c" , [ "solid" ] ),
    ("clipboard-list", u"\uf46d" , [ "solid" ] ),
    ("clock", u"\uf017" , [ "solid", "regular" ] ),
    ("clone", u"\uf24d" , [ "solid", "regular" ] ),
    ("closed-captioning", u"\uf20a" , [ "solid", "regular" ] ),
    ("cloud", u"\uf0c2" , [ "solid" ] ),
    ("cloud-download-alt", u"\uf381" , [ "solid" ] ),
    ("cloud-moon", u"\uf6c3" , [ "solid" ] ),
    ("cloud-sun", u"\uf6c4" , [ "solid" ] ),
    ("cloud-upload-alt", u"\uf382" , [ "solid" ] ),
    ("cloudscale", u"\uf383" , [ "brands" ] ),
    ("cloudsmith", u"\uf384" , [ "brands" ] ),
    ("cloudversify", u"\uf385" , [ "brands" ] ),
    ("cocktail", u"\uf561" , [ "solid" ] ),
    ("code", u"\uf121" , [ "solid" ] ),
    ("code-branch", u"\uf126" , [ "solid" ] ),
    ("codepen", u"\uf1cb" , [ "brands" ] ),
    ("codiepie", u"\uf284" , [ "brands" ] ),
    ("coffee", u"\uf0f4" , [ "solid" ] ),
    ("cog", u"\uf013" , [ "solid" ] ),
    ("cogs", u"\uf085" , [ "solid" ] ),
    ("coins", u"\uf51e" , [ "solid" ] ),
    ("columns", u"\uf0db" , [ "solid" ] ),
    ("comment", u"\uf075" , [ "solid", "regular" ] ),
    ("comment-alt", u"\uf27a" , [ "solid", "regular" ] ),
    ("comment-dollar", u"\uf651" , [ "solid" ] ),
    ("comment-dots", u"\uf4ad" , [ "solid", "regular" ] ),
    ("comment-slash", u"\uf4b3" , [ "solid" ] ),
    ("comments", u"\uf086" , [ "solid", "regular" ] ),
    ("comments-dollar", u"\uf653" , [ "solid" ] ),
    ("compact-disc", u"\uf51f" , [ "solid" ] ),
    ("compass", u"\uf14e" , [ "solid", "regular" ] ),
    ("compress", u"\uf066" , [ "solid" ] ),
    ("concierge-bell", u"\uf562" , [ "solid" ] ),
    ("connectdevelop", u"\uf20e" , [ "brands" ] ),
    ("contao", u"\uf26d" , [ "brands" ] ),
    ("cookie", u"\uf563" , [ "solid" ] ),
    ("cookie-bite", u"\uf564" , [ "solid" ] ),
    ("copy", u"\uf0c5" , [ "solid", "regular" ] ),
    ("copyright", u"\uf1f9" , [ "solid", "regular" ] ),
    ("couch", u"\uf4b8" , [ "solid" ] ),
    ("cpanel", u"\uf388" , [ "brands" ] ),
    ("creative-commons", u"\uf25e" , [ "brands" ] ),
    ("creative-commons-by", u"\uf4e7" , [ "brands" ] ),
    ("creative-commons-nc", u"\uf4e8" , [ "brands" ] ),
    ("creative-commons-nc-eu", u"\uf4e9" , [ "brands" ] ),
    ("creative-commons-nc-jp", u"\uf4ea" , [ "brands" ] ),
    ("creative-commons-nd", u"\uf4eb" , [ "brands" ] ),
    ("creative-commons-pd", u"\uf4ec" , [ "brands" ] ),
    ("creative-commons-pd-alt", u"\uf4ed" , [ "brands" ] ),
    ("creative-commons-remix", u"\uf4ee" , [ "brands" ] ),
    ("creative-commons-sa", u"\uf4ef" , [ "brands" ] ),
    ("creative-commons-sampling", u"\uf4f0" , [ "brands" ] ),
    ("creative-commons-sampling-plus", u"\uf4f1" , [ "brands" ] ),
    ("creative-commons-share", u"\uf4f2" , [ "brands" ] ),
    ("creative-commons-zero", u"\uf4f3" , [ "brands" ] ),
    ("credit-card", u"\uf09d" , [ "solid", "regular" ] ),
    ("critical-role", u"\uf6c9" , [ "brands" ] ),
    ("crop", u"\uf125" , [ "solid" ] ),
    ("crop-alt", u"\uf565" , [ "solid" ] ),
    ("cross", u"\uf654" , [ "solid" ] ),
    ("crosshairs", u"\uf05b" , [ "solid" ] ),
    ("crow", u"\uf520" , [ "solid" ] ),
    ("crown", u"\uf521" , [ "solid" ] ),
    ("css3", u"\uf13c" , [ "brands" ] ),
    ("css3-alt", u"\uf38b" , [ "brands" ] ),
    ("cube", u"\uf1b2" , [ "solid" ] ),
    ("cubes", u"\uf1b3" , [ "solid" ] ),
    ("cut", u"\uf0c4" , [ "solid" ] ),
    ("cuttlefish", u"\uf38c" , [ "brands" ] ),
    ("d-and-d", u"\uf38d" , [ "brands" ] ),
    ("dashcube", u"\uf210" , [ "brands" ] ),
    ("database", u"\uf1c0" , [ "solid" ] ),
    ("deaf", u"\uf2a4" , [ "solid" ] ),
    ("delicious", u"\uf1a5" , [ "brands" ] ),
    ("deploydog", u"\uf38e" , [ "brands" ] ),
    ("deskpro", u"\uf38f" , [ "brands" ] ),
    ("desktop", u"\uf108" , [ "solid" ] ),
    ("dev", u"\uf6cc" , [ "brands" ] ),
    ("deviantart", u"\uf1bd" , [ "brands" ] ),
    ("dharmachakra", u"\uf655" , [ "solid" ] ),
    ("diagnoses", u"\uf470" , [ "solid" ] ),
    ("dice", u"\uf522" , [ "solid" ] ),
    ("dice-d20", u"\uf6cf" , [ "solid" ] ),
    ("dice-d6", u"\uf6d1" , [ "solid" ] ),
    ("dice-five", u"\uf523" , [ "solid" ] ),
    ("dice-four", u"\uf524" , [ "solid" ] ),
    ("dice-one", u"\uf525" , [ "solid" ] ),
    ("dice-six", u"\uf526" , [ "solid" ] ),
    ("dice-three", u"\uf527" , [ "solid" ] ),
    ("dice-two", u"\uf528" , [ "solid" ] ),
    ("digg", u"\uf1a6" , [ "brands" ] ),
    ("digital-ocean", u"\uf391" , [ "brands" ] ),
    ("digital-tachograph", u"\uf566" , [ "solid" ] ),
    ("directions", u"\uf5eb" , [ "solid" ] ),
    ("discord", u"\uf392" , [ "brands" ] ),
    ("discourse", u"\uf393" , [ "brands" ] ),
    ("divide", u"\uf529" , [ "solid" ] ),
    ("dizzy", u"\uf567" , [ "solid", "regular" ] ),
    ("dna", u"\uf471" , [ "solid" ] ),
    ("dochub", u"\uf394" , [ "brands" ] ),
    ("docker", u"\uf395" , [ "brands" ] ),
    ("dog", u"\uf6d3" , [ "solid" ] ),
    ("dollar-sign", u"\uf155" , [ "solid" ] ),
    ("dolly", u"\uf472" , [ "solid" ] ),
    ("dolly-flatbed", u"\uf474" , [ "solid" ] ),
    ("donate", u"\uf4b9" , [ "solid" ] ),
    ("door-closed", u"\uf52a" , [ "solid" ] ),
    ("door-open", u"\uf52b" , [ "solid" ] ),
    ("dot-circle", u"\uf192" , [ "solid", "regular" ] ),
    ("dove", u"\uf4ba" , [ "solid" ] ),
    ("download", u"\uf019" , [ "solid" ] ),
    ("draft2digital", u"\uf396" , [ "brands" ] ),
    ("drafting-compass", u"\uf568" , [ "solid" ] ),
    ("dragon", u"\uf6d5" , [ "solid" ] ),
    ("draw-polygon", u"\uf5ee" , [ "solid" ] ),
    ("dribbble", u"\uf17d" , [ "brands" ] ),
    ("dribbble-square", u"\uf397" , [ "brands" ] ),
    ("dropbox", u"\uf16b" , [ "brands" ] ),
    ("drum", u"\uf569" , [ "solid" ] ),
    ("drum-steelpan", u"\uf56a" , [ "solid" ] ),
    ("drumstick-bite", u"\uf6d7" , [ "solid" ] ),
    ("drupal", u"\uf1a9" , [ "brands" ] ),
    ("dumbbell", u"\uf44b" , [ "solid" ] ),
    ("dungeon", u"\uf6d9" , [ "solid" ] ),
    ("dyalog", u"\uf399" , [ "brands" ] ),
    ("earlybirds", u"\uf39a" , [ "brands" ] ),
    ("ebay", u"\uf4f4" , [ "brands" ] ),
    ("edge", u"\uf282" , [ "brands" ] ),
    ("edit", u"\uf044" , [ "solid", "regular" ] ),
    ("eject", u"\uf052" , [ "solid" ] ),
    ("elementor", u"\uf430" , [ "brands" ] ),
    ("ellipsis-h", u"\uf141" , [ "solid" ] ),
    ("ellipsis-v", u"\uf142" , [ "solid" ] ),
    ("ello", u"\uf5f1" , [ "brands" ] ),
    ("ember", u"\uf423" , [ "brands" ] ),
    ("empire", u"\uf1d1" , [ "brands" ] ),
    ("envelope", u"\uf0e0" , [ "solid", "regular" ] ),
    ("envelope-open", u"\uf2b6" , [ "solid", "regular" ] ),
    ("envelope-open-text", u"\uf658" , [ "solid" ] ),
    ("envelope-square", u"\uf199" , [ "solid" ] ),
    ("envira", u"\uf299" , [ "brands" ] ),
    ("equals", u"\uf52c" , [ "solid" ] ),
    ("eraser", u"\uf12d" , [ "solid" ] ),
    ("erlang", u"\uf39d" , [ "brands" ] ),
    ("ethereum", u"\uf42e" , [ "brands" ] ),
    ("etsy", u"\uf2d7" , [ "brands" ] ),
    ("euro-sign", u"\uf153" , [ "solid" ] ),
    ("exchange-alt", u"\uf362" , [ "solid" ] ),
    ("exclamation", u"\uf12a" , [ "solid" ] ),
    ("exclamation-circle", u"\uf06a" , [ "solid" ] ),
    ("exclamation-triangle", u"\uf071" , [ "solid" ] ),
    ("expand", u"\uf065" , [ "solid" ] ),
    ("expand-arrows-alt", u"\uf31e" , [ "solid" ] ),
    ("expeditedssl", u"\uf23e" , [ "brands" ] ),
    ("external-link-alt", u"\uf35d" , [ "solid" ] ),
    ("external-link-square-alt", u"\uf360" , [ "solid" ] ),
    ("eye", u"\uf06e" , [ "solid", "regular" ] ),
    ("eye-dropper", u"\uf1fb" , [ "solid" ] ),
    ("eye-slash", u"\uf070" , [ "solid", "regular" ] ),
    ("facebook", u"\uf09a" , [ "brands" ] ),
    ("facebook-f", u"\uf39e" , [ "brands" ] ),
    ("facebook-messenger", u"\uf39f" , [ "brands" ] ),
    ("facebook-square", u"\uf082" , [ "brands" ] ),
    ("fantasy-flight-games", u"\uf6dc" , [ "brands" ] ),
    ("fast-backward", u"\uf049" , [ "solid" ] ),
    ("fast-forward", u"\uf050" , [ "solid" ] ),
    ("fax", u"\uf1ac" , [ "solid" ] ),
    ("feather", u"\uf52d" , [ "solid" ] ),
    ("feather-alt", u"\uf56b" , [ "solid" ] ),
    ("female", u"\uf182" , [ "solid" ] ),
    ("fighter-jet", u"\uf0fb" , [ "solid" ] ),
    ("file", u"\uf15b" , [ "solid", "regular" ] ),
    ("file-alt", u"\uf15c" , [ "solid", "regular" ] ),
    ("file-archive", u"\uf1c6" , [ "solid", "regular" ] ),
    ("file-audio", u"\uf1c7" , [ "solid", "regular" ] ),
    ("file-code", u"\uf1c9" , [ "solid", "regular" ] ),
    ("file-contract", u"\uf56c" , [ "solid" ] ),
    ("file-csv", u"\uf6dd" , [ "solid" ] ),
    ("file-download", u"\uf56d" , [ "solid" ] ),
    ("file-excel", u"\uf1c3" , [ "solid", "regular" ] ),
    ("file-export", u"\uf56e" , [ "solid" ] ),
    ("file-image", u"\uf1c5" , [ "solid", "regular" ] ),
    ("file-import", u"\uf56f" , [ "solid" ] ),
    ("file-invoice", u"\uf570" , [ "solid" ] ),
    ("file-invoice-dollar", u"\uf571" , [ "solid" ] ),
    ("file-medical", u"\uf477" , [ "solid" ] ),
    ("file-medical-alt", u"\uf478" , [ "solid" ] ),
    ("file-pdf", u"\uf1c1" , [ "solid", "regular" ] ),
    ("file-powerpoint", u"\uf1c4" , [ "solid", "regular" ] ),
    ("file-prescription", u"\uf572" , [ "solid" ] ),
    ("file-signature", u"\uf573" , [ "solid" ] ),
    ("file-upload", u"\uf574" , [ "solid" ] ),
    ("file-video", u"\uf1c8" , [ "solid", "regular" ] ),
    ("file-word", u"\uf1c2" , [ "solid", "regular" ] ),
    ("fill", u"\uf575" , [ "solid" ] ),
    ("fill-drip", u"\uf576" , [ "solid" ] ),
    ("film", u"\uf008" , [ "solid" ] ),
    ("filter", u"\uf0b0" , [ "solid" ] ),
    ("fingerprint", u"\uf577" , [ "solid" ] ),
    ("fire", u"\uf06d" , [ "solid" ] ),
    ("fire-extinguisher", u"\uf134" , [ "solid" ] ),
    ("firefox", u"\uf269" , [ "brands" ] ),
    ("first-aid", u"\uf479" , [ "solid" ] ),
    ("first-order", u"\uf2b0" , [ "brands" ] ),
    ("first-order-alt", u"\uf50a" , [ "brands" ] ),
    ("firstdraft", u"\uf3a1" , [ "brands" ] ),
    ("fish", u"\uf578" , [ "solid" ] ),
    ("fist-raised", u"\uf6de" , [ "solid" ] ),
    ("flag", u"\uf024" , [ "solid", "regular" ] ),
    ("flag-checkered", u"\uf11e" , [ "solid" ] ),
    ("flask", u"\uf0c3" , [ "solid" ] ),
    ("flickr", u"\uf16e" , [ "brands" ] ),
    ("flipboard", u"\uf44d" , [ "brands" ] ),
    ("flushed", u"\uf579" , [ "solid", "regular" ] ),
    ("fly", u"\uf417" , [ "brands" ] ),
    ("folder", u"\uf07b" , [ "solid", "regular" ] ),
    ("folder-minus", u"\uf65d" , [ "solid" ] ),
    ("folder-open", u"\uf07c" , [ "solid", "regular" ] ),
    ("folder-plus", u"\uf65e" , [ "solid" ] ),
    ("font", u"\uf031" , [ "solid" ] ),
    ("font-awesome", u"\uf2b4" , [ "brands" ] ),
    ("font-awesome-alt", u"\uf35c" , [ "brands" ] ),
    ("font-awesome-flag", u"\uf425" , [ "brands" ] ),
    ("font-awesome-logo-full", u"\uf4e6" , [ "regular", "solid", "brands" ] ),
    ("fonticons", u"\uf280" , [ "brands" ] ),
    ("fonticons-fi", u"\uf3a2" , [ "brands" ] ),
    ("football-ball", u"\uf44e" , [ "solid" ] ),
    ("fort-awesome", u"\uf286" , [ "brands" ] ),
    ("fort-awesome-alt", u"\uf3a3" , [ "brands" ] ),
    ("forumbee", u"\uf211" , [ "brands" ] ),
    ("forward", u"\uf04e" , [ "solid" ] ),
    ("foursquare", u"\uf180" , [ "brands" ] ),
    ("free-code-camp", u"\uf2c5" , [ "brands" ] ),
    ("freebsd", u"\uf3a4" , [ "brands" ] ),
    ("frog", u"\uf52e" , [ "solid" ] ),
    ("frown", u"\uf119" , [ "solid", "regular" ] ),
    ("frown-open", u"\uf57a" , [ "solid", "regular" ] ),
    ("fulcrum", u"\uf50b" , [ "brands" ] ),
    ("funnel-dollar", u"\uf662" , [ "solid" ] ),
    ("futbol", u"\uf1e3" , [ "solid", "regular" ] ),
    ("galactic-republic", u"\uf50c" , [ "brands" ] ),
    ("galactic-senate", u"\uf50d" , [ "brands" ] ),
    ("gamepad", u"\uf11b" , [ "solid" ] ),
    ("gas-pump", u"\uf52f" , [ "solid" ] ),
    ("gavel", u"\uf0e3" , [ "solid" ] ),
    ("gem", u"\uf3a5" , [ "solid", "regular" ] ),
    ("genderless", u"\uf22d" , [ "solid" ] ),
    ("get-pocket", u"\uf265" , [ "brands" ] ),
    ("gg", u"\uf260" , [ "brands" ] ),
    ("gg-circle", u"\uf261" , [ "brands" ] ),
    ("ghost", u"\uf6e2" , [ "solid" ] ),
    ("gift", u"\uf06b" , [ "solid" ] ),
    ("git", u"\uf1d3" , [ "brands" ] ),
    ("git-square", u"\uf1d2" , [ "brands" ] ),
    ("github", u"\uf09b" , [ "brands" ] ),
    ("github-alt", u"\uf113" , [ "brands" ] ),
    ("github-square", u"\uf092" , [ "brands" ] ),
    ("gitkraken", u"\uf3a6" , [ "brands" ] ),
    ("gitlab", u"\uf296" , [ "brands" ] ),
    ("gitter", u"\uf426" , [ "brands" ] ),
    ("glass-martini", u"\uf000" , [ "solid" ] ),
    ("glass-martini-alt", u"\uf57b" , [ "solid" ] ),
    ("glasses", u"\uf530" , [ "solid" ] ),
    ("glide", u"\uf2a5" , [ "brands" ] ),
    ("glide-g", u"\uf2a6" , [ "brands" ] ),
    ("globe", u"\uf0ac" , [ "solid" ] ),
    ("globe-africa", u"\uf57c" , [ "solid" ] ),
    ("globe-americas", u"\uf57d" , [ "solid" ] ),
    ("globe-asia", u"\uf57e" , [ "solid" ] ),
    ("gofore", u"\uf3a7" , [ "brands" ] ),
    ("golf-ball", u"\uf450" , [ "solid" ] ),
    ("goodreads", u"\uf3a8" , [ "brands" ] ),
    ("goodreads-g", u"\uf3a9" , [ "brands" ] ),
    ("google", u"\uf1a0" , [ "brands" ] ),
    ("google-drive", u"\uf3aa" , [ "brands" ] ),
    ("google-play", u"\uf3ab" , [ "brands" ] ),
    ("google-plus", u"\uf2b3" , [ "brands" ] ),
    ("google-plus-g", u"\uf0d5" , [ "brands" ] ),
    ("google-plus-square", u"\uf0d4" , [ "brands" ] ),
    ("google-wallet", u"\uf1ee" , [ "brands" ] ),
    ("gopuram", u"\uf664" , [ "solid" ] ),
    ("graduation-cap", u"\uf19d" , [ "solid" ] ),
    ("gratipay", u"\uf184" , [ "brands" ] ),
    ("grav", u"\uf2d6" , [ "brands" ] ),
    ("greater-than", u"\uf531" , [ "solid" ] ),
    ("greater-than-equal", u"\uf532" , [ "solid" ] ),
    ("grimace", u"\uf57f" , [ "solid", "regular" ] ),
    ("grin", u"\uf580" , [ "solid", "regular" ] ),
    ("grin-alt", u"\uf581" , [ "solid", "regular" ] ),
    ("grin-beam", u"\uf582" , [ "solid", "regular" ] ),
    ("grin-beam-sweat", u"\uf583" , [ "solid", "regular" ] ),
    ("grin-hearts", u"\uf584" , [ "solid", "regular" ] ),
    ("grin-squint", u"\uf585" , [ "solid", "regular" ] ),
    ("grin-squint-tears", u"\uf586" , [ "solid", "regular" ] ),
    ("grin-stars", u"\uf587" , [ "solid", "regular" ] ),
    ("grin-tears", u"\uf588" , [ "solid", "regular" ] ),
    ("grin-tongue", u"\uf589" , [ "solid", "regular" ] ),
    ("grin-tongue-squint", u"\uf58a" , [ "solid", "regular" ] ),
    ("grin-tongue-wink", u"\uf58b" , [ "solid", "regular" ] ),
    ("grin-wink", u"\uf58c" , [ "solid", "regular" ] ),
    ("grip-horizontal", u"\uf58d" , [ "solid" ] ),
    ("grip-vertical", u"\uf58e" , [ "solid" ] ),
    ("gripfire", u"\uf3ac" , [ "brands" ] ),
    ("grunt", u"\uf3ad" , [ "brands" ] ),
    ("gulp", u"\uf3ae" , [ "brands" ] ),
    ("h-square", u"\uf0fd" , [ "solid" ] ),
    ("hacker-news", u"\uf1d4" , [ "brands" ] ),
    ("hacker-news-square", u"\uf3af" , [ "brands" ] ),
    ("hackerrank", u"\uf5f7" , [ "brands" ] ),
    ("hammer", u"\uf6e3" , [ "solid" ] ),
    ("hamsa", u"\uf665" , [ "solid" ] ),
    ("hand-holding", u"\uf4bd" , [ "solid" ] ),
    ("hand-holding-heart", u"\uf4be" , [ "solid" ] ),
    ("hand-holding-usd", u"\uf4c0" , [ "solid" ] ),
    ("hand-lizard", u"\uf258" , [ "solid", "regular" ] ),
    ("hand-paper", u"\uf256" , [ "solid", "regular" ] ),
    ("hand-peace", u"\uf25b" , [ "solid", "regular" ] ),
    ("hand-point-down", u"\uf0a7" , [ "solid", "regular" ] ),
    ("hand-point-left", u"\uf0a5" , [ "solid", "regular" ] ),
    ("hand-point-right", u"\uf0a4" , [ "solid", "regular" ] ),
    ("hand-point-up", u"\uf0a6" , [ "solid", "regular" ] ),
    ("hand-pointer", u"\uf25a" , [ "solid", "regular" ] ),
    ("hand-rock", u"\uf255" , [ "solid", "regular" ] ),
    ("hand-scissors", u"\uf257" , [ "solid", "regular" ] ),
    ("hand-spock", u"\uf259" , [ "solid", "regular" ] ),
    ("hands", u"\uf4c2" , [ "solid" ] ),
    ("hands-helping", u"\uf4c4" , [ "solid" ] ),
    ("handshake", u"\uf2b5" , [ "solid", "regular" ] ),
    ("hanukiah", u"\uf6e6" , [ "solid" ] ),
    ("hashtag", u"\uf292" , [ "solid" ] ),
    ("hat-wizard", u"\uf6e8" , [ "solid" ] ),
    ("haykal", u"\uf666" , [ "solid" ] ),
    ("hdd", u"\uf0a0" , [ "solid", "regular" ] ),
    ("heading", u"\uf1dc" , [ "solid" ] ),
    ("headphones", u"\uf025" , [ "solid" ] ),
    ("headphones-alt", u"\uf58f" , [ "solid" ] ),
    ("headset", u"\uf590" , [ "solid" ] ),
    ("heart", u"\uf004" , [ "solid", "regular" ] ),
    ("heartbeat", u"\uf21e" , [ "solid" ] ),
    ("helicopter", u"\uf533" , [ "solid" ] ),
    ("highlighter", u"\uf591" , [ "solid" ] ),
    ("hiking", u"\uf6ec" , [ "solid" ] ),
    ("hippo", u"\uf6ed" , [ "solid" ] ),
    ("hips", u"\uf452" , [ "brands" ] ),
    ("hire-a-helper", u"\uf3b0" , [ "brands" ] ),
    ("history", u"\uf1da" , [ "solid" ] ),
    ("hockey-puck", u"\uf453" , [ "solid" ] ),
    ("home", u"\uf015" , [ "solid" ] ),
    ("hooli", u"\uf427" , [ "brands" ] ),
    ("hornbill", u"\uf592" , [ "brands" ] ),
    ("horse", u"\uf6f0" , [ "solid" ] ),
    ("hospital", u"\uf0f8" , [ "solid", "regular" ] ),
    ("hospital-alt", u"\uf47d" , [ "solid" ] ),
    ("hospital-symbol", u"\uf47e" , [ "solid" ] ),
    ("hot-tub", u"\uf593" , [ "solid" ] ),
    ("hotel", u"\uf594" , [ "solid" ] ),
    ("hotjar", u"\uf3b1" , [ "brands" ] ),
    ("hourglass", u"\uf254" , [ "solid", "regular" ] ),
    ("hourglass-end", u"\uf253" , [ "solid" ] ),
    ("hourglass-half", u"\uf252" , [ "solid" ] ),
    ("hourglass-start", u"\uf251" , [ "solid" ] ),
    ("house-damage", u"\uf6f1" , [ "solid" ] ),
    ("houzz", u"\uf27c" , [ "brands" ] ),
    ("hryvnia", u"\uf6f2" , [ "solid" ] ),
    ("html5", u"\uf13b" , [ "brands" ] ),
    ("hubspot", u"\uf3b2" , [ "brands" ] ),
    ("i-cursor", u"\uf246" , [ "solid" ] ),
    ("id-badge", u"\uf2c1" , [ "solid", "regular" ] ),
    ("id-card", u"\uf2c2" , [ "solid", "regular" ] ),
    ("id-card-alt", u"\uf47f" , [ "solid" ] ),
    ("image", u"\uf03e" , [ "solid", "regular" ] ),
    ("images", u"\uf302" , [ "solid", "regular" ] ),
    ("imdb", u"\uf2d8" , [ "brands" ] ),
    ("inbox", u"\uf01c" , [ "solid" ] ),
    ("indent", u"\uf03c" , [ "solid" ] ),
    ("industry", u"\uf275" , [ "solid" ] ),
    ("infinity", u"\uf534" , [ "solid" ] ),
    ("info", u"\uf129" , [ "solid" ] ),
    ("info-circle", u"\uf05a" , [ "solid" ] ),
    ("instagram", u"\uf16d" , [ "brands" ] ),
    ("internet-explorer", u"\uf26b" , [ "brands" ] ),
    ("ioxhost", u"\uf208" , [ "brands" ] ),
    ("italic", u"\uf033" , [ "solid" ] ),
    ("itunes", u"\uf3b4" , [ "brands" ] ),
    ("itunes-note", u"\uf3b5" , [ "brands" ] ),
    ("java", u"\uf4e4" , [ "brands" ] ),
    ("jedi", u"\uf669" , [ "solid" ] ),
    ("jedi-order", u"\uf50e" , [ "brands" ] ),
    ("jenkins", u"\uf3b6" , [ "brands" ] ),
    ("joget", u"\uf3b7" , [ "brands" ] ),
    ("joint", u"\uf595" , [ "solid" ] ),
    ("joomla", u"\uf1aa" , [ "brands" ] ),
    ("journal-whills", u"\uf66a" , [ "solid" ] ),
    ("js", u"\uf3b8" , [ "brands" ] ),
    ("js-square", u"\uf3b9" , [ "brands" ] ),
    ("jsfiddle", u"\uf1cc" , [ "brands" ] ),
    ("kaaba", u"\uf66b" , [ "solid" ] ),
    ("kaggle", u"\uf5fa" , [ "brands" ] ),
    ("key", u"\uf084" , [ "solid" ] ),
    ("keybase", u"\uf4f5" , [ "brands" ] ),
    ("keyboard", u"\uf11c" , [ "solid", "regular" ] ),
    ("keycdn", u"\uf3ba" , [ "brands" ] ),
    ("khanda", u"\uf66d" , [ "solid" ] ),
    ("kickstarter", u"\uf3bb" , [ "brands" ] ),
    ("kickstarter-k", u"\uf3bc" , [ "brands" ] ),
    ("kiss", u"\uf596" , [ "solid", "regular" ] ),
    ("kiss-beam", u"\uf597" , [ "solid", "regular" ] ),
    ("kiss-wink-heart", u"\uf598" , [ "solid", "regular" ] ),
    ("kiwi-bird", u"\uf535" , [ "solid" ] ),
    ("korvue", u"\uf42f" , [ "brands" ] ),
    ("landmark", u"\uf66f" , [ "solid" ] ),
    ("language", u"\uf1ab" , [ "solid" ] ),
    ("laptop", u"\uf109" , [ "solid" ] ),
    ("laptop-code", u"\uf5fc" , [ "solid" ] ),
    ("laravel", u"\uf3bd" , [ "brands" ] ),
    ("lastfm", u"\uf202" , [ "brands" ] ),
    ("lastfm-square", u"\uf203" , [ "brands" ] ),
    ("laugh", u"\uf599" , [ "solid", "regular" ] ),
    ("laugh-beam", u"\uf59a" , [ "solid", "regular" ] ),
    ("laugh-squint", u"\uf59b" , [ "solid", "regular" ] ),
    ("laugh-wink", u"\uf59c" , [ "solid", "regular" ] ),
    ("layer-group", u"\uf5fd" , [ "solid" ] ),
    ("leaf", u"\uf06c" , [ "solid" ] ),
    ("leanpub", u"\uf212" , [ "brands" ] ),
    ("lemon", u"\uf094" , [ "solid", "regular" ] ),
    ("less", u"\uf41d" , [ "brands" ] ),
    ("less-than", u"\uf536" , [ "solid" ] ),
    ("less-than-equal", u"\uf537" , [ "solid" ] ),
    ("level-down-alt", u"\uf3be" , [ "solid" ] ),
    ("level-up-alt", u"\uf3bf" , [ "solid" ] ),
    ("life-ring", u"\uf1cd" , [ "solid", "regular" ] ),
    ("lightbulb", u"\uf0eb" , [ "solid", "regular" ] ),
    ("line", u"\uf3c0" , [ "brands" ] ),
    ("link", u"\uf0c1" , [ "solid" ] ),
    ("linkedin", u"\uf08c" , [ "brands" ] ),
    ("linkedin-in", u"\uf0e1" , [ "brands" ] ),
    ("linode", u"\uf2b8" , [ "brands" ] ),
    ("linux", u"\uf17c" , [ "brands" ] ),
    ("lira-sign", u"\uf195" , [ "solid" ] ),
    ("list", u"\uf03a" , [ "solid" ] ),
    ("list-alt", u"\uf022" , [ "solid", "regular" ] ),
    ("list-ol", u"\uf0cb" , [ "solid" ] ),
    ("list-ul", u"\uf0ca" , [ "solid" ] ),
    ("location-arrow", u"\uf124" , [ "solid" ] ),
    ("lock", u"\uf023" , [ "solid" ] ),
    ("lock-open", u"\uf3c1" , [ "solid" ] ),
    ("long-arrow-alt-down", u"\uf309" , [ "solid" ] ),
    ("long-arrow-alt-left", u"\uf30a" , [ "solid" ] ),
    ("long-arrow-alt-right", u"\uf30b" , [ "solid" ] ),
    ("long-arrow-alt-up", u"\uf30c" , [ "solid" ] ),
    ("low-vision", u"\uf2a8" , [ "solid" ] ),
    ("luggage-cart", u"\uf59d" , [ "solid" ] ),
    ("lyft", u"\uf3c3" , [ "brands" ] ),
    ("magento", u"\uf3c4" , [ "brands" ] ),
    ("magic", u"\uf0d0" , [ "solid" ] ),
    ("magnet", u"\uf076" , [ "solid" ] ),
    ("mail-bulk", u"\uf674" , [ "solid" ] ),
    ("mailchimp", u"\uf59e" , [ "brands" ] ),
    ("male", u"\uf183" , [ "solid" ] ),
    ("mandalorian", u"\uf50f" , [ "brands" ] ),
    ("map", u"\uf279" , [ "solid", "regular" ] ),
    ("map-marked", u"\uf59f" , [ "solid" ] ),
    ("map-marked-alt", u"\uf5a0" , [ "solid" ] ),
    ("map-marker", u"\uf041" , [ "solid" ] ),
    ("map-marker-alt", u"\uf3c5" , [ "solid" ] ),
    ("map-pin", u"\uf276" , [ "solid" ] ),
    ("map-signs", u"\uf277" , [ "solid" ] ),
    ("markdown", u"\uf60f" , [ "brands" ] ),
    ("marker", u"\uf5a1" , [ "solid" ] ),
    ("mars", u"\uf222" , [ "solid" ] ),
    ("mars-double", u"\uf227" , [ "solid" ] ),
    ("mars-stroke", u"\uf229" , [ "solid" ] ),
    ("mars-stroke-h", u"\uf22b" , [ "solid" ] ),
    ("mars-stroke-v", u"\uf22a" , [ "solid" ] ),
    ("mask", u"\uf6fa" , [ "solid" ] ),
    ("mastodon", u"\uf4f6" , [ "brands" ] ),
    ("maxcdn", u"\uf136" , [ "brands" ] ),
    ("medal", u"\uf5a2" , [ "solid" ] ),
    ("medapps", u"\uf3c6" , [ "brands" ] ),
    ("medium", u"\uf23a" , [ "brands" ] ),
    ("medium-m", u"\uf3c7" , [ "brands" ] ),
    ("medkit", u"\uf0fa" , [ "solid" ] ),
    ("medrt", u"\uf3c8" , [ "brands" ] ),
    ("meetup", u"\uf2e0" , [ "brands" ] ),
    ("megaport", u"\uf5a3" , [ "brands" ] ),
    ("meh", u"\uf11a" , [ "solid", "regular" ] ),
    ("meh-blank", u"\uf5a4" , [ "solid", "regular" ] ),
    ("meh-rolling-eyes", u"\uf5a5" , [ "solid", "regular" ] ),
    ("memory", u"\uf538" , [ "solid" ] ),
    ("menorah", u"\uf676" , [ "solid" ] ),
    ("mercury", u"\uf223" , [ "solid" ] ),
    ("microchip", u"\uf2db" , [ "solid" ] ),
    ("microphone", u"\uf130" , [ "solid" ] ),
    ("microphone-alt", u"\uf3c9" , [ "solid" ] ),
    ("microphone-alt-slash", u"\uf539" , [ "solid" ] ),
    ("microphone-slash", u"\uf131" , [ "solid" ] ),
    ("microscope", u"\uf610" , [ "solid" ] ),
    ("microsoft", u"\uf3ca" , [ "brands" ] ),
    ("minus", u"\uf068" , [ "solid" ] ),
    ("minus-circle", u"\uf056" , [ "solid" ] ),
    ("minus-square", u"\uf146" , [ "solid", "regular" ] ),
    ("mix", u"\uf3cb" , [ "brands" ] ),
    ("mixcloud", u"\uf289" , [ "brands" ] ),
    ("mizuni", u"\uf3cc" , [ "brands" ] ),
    ("mobile", u"\uf10b" , [ "solid" ] ),
    ("mobile-alt", u"\uf3cd" , [ "solid" ] ),
    ("modx", u"\uf285" , [ "brands" ] ),
    ("monero", u"\uf3d0" , [ "brands" ] ),
    ("money-bill", u"\uf0d6" , [ "solid" ] ),
    ("money-bill-alt", u"\uf3d1" , [ "solid", "regular" ] ),
    ("money-bill-wave", u"\uf53a" , [ "solid" ] ),
    ("money-bill-wave-alt", u"\uf53b" , [ "solid" ] ),
    ("money-check", u"\uf53c" , [ "solid" ] ),
    ("money-check-alt", u"\uf53d" , [ "solid" ] ),
    ("monument", u"\uf5a6" , [ "solid" ] ),
    ("moon", u"\uf186" , [ "solid", "regular" ] ),
    ("mortar-pestle", u"\uf5a7" , [ "solid" ] ),
    ("mosque", u"\uf678" , [ "solid" ] ),
    ("motorcycle", u"\uf21c" , [ "solid" ] ),
    ("mountain", u"\uf6fc" , [ "solid" ] ),
    ("mouse-pointer", u"\uf245" , [ "solid" ] ),
    ("music", u"\uf001" , [ "solid" ] ),
    ("napster", u"\uf3d2" , [ "brands" ] ),
    ("neos", u"\uf612" , [ "brands" ] ),
    ("network-wired", u"\uf6ff" , [ "solid" ] ),
    ("neuter", u"\uf22c" , [ "solid" ] ),
    ("newspaper", u"\uf1ea" , [ "solid", "regular" ] ),
    ("nimblr", u"\uf5a8" , [ "brands" ] ),
    ("nintendo-switch", u"\uf418" , [ "brands" ] ),
    ("node", u"\uf419" , [ "brands" ] ),
    ("node-js", u"\uf3d3" , [ "brands" ] ),
    ("not-equal", u"\uf53e" , [ "solid" ] ),
    ("notes-medical", u"\uf481" , [ "solid" ] ),
    ("npm", u"\uf3d4" , [ "brands" ] ),
    ("ns8", u"\uf3d5" , [ "brands" ] ),
    ("nutritionix", u"\uf3d6" , [ "brands" ] ),
    ("object-group", u"\uf247" , [ "solid", "regular" ] ),
    ("object-ungroup", u"\uf248" , [ "solid", "regular" ] ),
    ("odnoklassniki", u"\uf263" , [ "brands" ] ),
    ("odnoklassniki-square", u"\uf264" , [ "brands" ] ),
    ("oil-can", u"\uf613" , [ "solid" ] ),
    ("old-republic", u"\uf510" , [ "brands" ] ),
    ("om", u"\uf679" , [ "solid" ] ),
    ("opencart", u"\uf23d" , [ "brands" ] ),
    ("openid", u"\uf19b" , [ "brands" ] ),
    ("opera", u"\uf26a" , [ "brands" ] ),
    ("optin-monster", u"\uf23c" , [ "brands" ] ),
    ("osi", u"\uf41a" , [ "brands" ] ),
    ("otter", u"\uf700" , [ "solid" ] ),
    ("outdent", u"\uf03b" , [ "solid" ] ),
    ("page4", u"\uf3d7" , [ "brands" ] ),
    ("pagelines", u"\uf18c" , [ "brands" ] ),
    ("paint-brush", u"\uf1fc" , [ "solid" ] ),
    ("paint-roller", u"\uf5aa" , [ "solid" ] ),
    ("palette", u"\uf53f" , [ "solid" ] ),
    ("palfed", u"\uf3d8" , [ "brands" ] ),
    ("pallet", u"\uf482" , [ "solid" ] ),
    ("paper-plane", u"\uf1d8" , [ "solid", "regular" ] ),
    ("paperclip", u"\uf0c6" , [ "solid" ] ),
    ("parachute-box", u"\uf4cd" , [ "solid" ] ),
    ("paragraph", u"\uf1dd" , [ "solid" ] ),
    ("parking", u"\uf540" , [ "solid" ] ),
    ("passport", u"\uf5ab" , [ "solid" ] ),
    ("pastafarianism", u"\uf67b" , [ "solid" ] ),
    ("paste", u"\uf0ea" , [ "solid" ] ),
    ("patreon", u"\uf3d9" , [ "brands" ] ),
    ("pause", u"\uf04c" , [ "solid" ] ),
    ("pause-circle", u"\uf28b" , [ "solid", "regular" ] ),
    ("paw", u"\uf1b0" , [ "solid" ] ),
    ("paypal", u"\uf1ed" , [ "brands" ] ),
    ("peace", u"\uf67c" , [ "solid" ] ),
    ("pen", u"\uf304" , [ "solid" ] ),
    ("pen-alt", u"\uf305" , [ "solid" ] ),
    ("pen-fancy", u"\uf5ac" , [ "solid" ] ),
    ("pen-nib", u"\uf5ad" , [ "solid" ] ),
    ("pen-square", u"\uf14b" , [ "solid" ] ),
    ("pencil-alt", u"\uf303" , [ "solid" ] ),
    ("pencil-ruler", u"\uf5ae" , [ "solid" ] ),
    ("penny-arcade", u"\uf704" , [ "brands" ] ),
    ("people-carry", u"\uf4ce" , [ "solid" ] ),
    ("percent", u"\uf295" , [ "solid" ] ),
    ("percentage", u"\uf541" , [ "solid" ] ),
    ("periscope", u"\uf3da" , [ "brands" ] ),
    ("phabricator", u"\uf3db" , [ "brands" ] ),
    ("phoenix-framework", u"\uf3dc" , [ "brands" ] ),
    ("phoenix-squadron", u"\uf511" , [ "brands" ] ),
    ("phone", u"\uf095" , [ "solid" ] ),
    ("phone-slash", u"\uf3dd" , [ "solid" ] ),
    ("phone-square", u"\uf098" , [ "solid" ] ),
    ("phone-volume", u"\uf2a0" , [ "solid" ] ),
    ("php", u"\uf457" , [ "brands" ] ),
    ("pied-piper", u"\uf2ae" , [ "brands" ] ),
    ("pied-piper-alt", u"\uf1a8" , [ "brands" ] ),
    ("pied-piper-hat", u"\uf4e5" , [ "brands" ] ),
    ("pied-piper-pp", u"\uf1a7" , [ "brands" ] ),
    ("piggy-bank", u"\uf4d3" , [ "solid" ] ),
    ("pills", u"\uf484" , [ "solid" ] ),
    ("pinterest", u"\uf0d2" , [ "brands" ] ),
    ("pinterest-p", u"\uf231" , [ "brands" ] ),
    ("pinterest-square", u"\uf0d3" , [ "brands" ] ),
    ("place-of-worship", u"\uf67f" , [ "solid" ] ),
    ("plane", u"\uf072" , [ "solid" ] ),
    ("plane-arrival", u"\uf5af" , [ "solid" ] ),
    ("plane-departure", u"\uf5b0" , [ "solid" ] ),
    ("play", u"\uf04b" , [ "solid" ] ),
    ("play-circle", u"\uf144" , [ "solid", "regular" ] ),
    ("playstation", u"\uf3df" , [ "brands" ] ),
    ("plug", u"\uf1e6" , [ "solid" ] ),
    ("plus", u"\uf067" , [ "solid" ] ),
    ("plus-circle", u"\uf055" , [ "solid" ] ),
    ("plus-square", u"\uf0fe" , [ "solid", "regular" ] ),
    ("podcast", u"\uf2ce" , [ "solid" ] ),
    ("poll", u"\uf681" , [ "solid" ] ),
    ("poll-h", u"\uf682" , [ "solid" ] ),
    ("poo", u"\uf2fe" , [ "solid" ] ),
    ("poop", u"\uf619" , [ "solid" ] ),
    ("portrait", u"\uf3e0" , [ "solid" ] ),
    ("pound-sign", u"\uf154" , [ "solid" ] ),
    ("power-off", u"\uf011" , [ "solid" ] ),
    ("pray", u"\uf683" , [ "solid" ] ),
    ("praying-hands", u"\uf684" , [ "solid" ] ),
    ("prescription", u"\uf5b1" , [ "solid" ] ),
    ("prescription-bottle", u"\uf485" , [ "solid" ] ),
    ("prescription-bottle-alt", u"\uf486" , [ "solid" ] ),
    ("print", u"\uf02f" , [ "solid" ] ),
    ("procedures", u"\uf487" , [ "solid" ] ),
    ("product-hunt", u"\uf288" , [ "brands" ] ),
    ("project-diagram", u"\uf542" , [ "solid" ] ),
    ("pushed", u"\uf3e1" , [ "brands" ] ),
    ("puzzle-piece", u"\uf12e" , [ "solid" ] ),
    ("python", u"\uf3e2" , [ "brands" ] ),
    ("qq", u"\uf1d6" , [ "brands" ] ),
    ("qrcode", u"\uf029" , [ "solid" ] ),
    ("question", u"\uf128" , [ "solid" ] ),
    ("question-circle", u"\uf059" , [ "solid", "regular" ] ),
    ("quidditch", u"\uf458" , [ "solid" ] ),
    ("quinscape", u"\uf459" , [ "brands" ] ),
    ("quora", u"\uf2c4" , [ "brands" ] ),
    ("quote-left", u"\uf10d" , [ "solid" ] ),
    ("quote-right", u"\uf10e" , [ "solid" ] ),
    ("quran", u"\uf687" , [ "solid" ] ),
    ("r-project", u"\uf4f7" , [ "brands" ] ),
    ("random", u"\uf074" , [ "solid" ] ),
    ("ravelry", u"\uf2d9" , [ "brands" ] ),
    ("react", u"\uf41b" , [ "brands" ] ),
    ("readme", u"\uf4d5" , [ "brands" ] ),
    ("rebel", u"\uf1d0" , [ "brands" ] ),
    ("receipt", u"\uf543" , [ "solid" ] ),
    ("recycle", u"\uf1b8" , [ "solid" ] ),
    ("red-river", u"\uf3e3" , [ "brands" ] ),
    ("reddit", u"\uf1a1" , [ "brands" ] ),
    ("reddit-alien", u"\uf281" , [ "brands" ] ),
    ("reddit-square", u"\uf1a2" , [ "brands" ] ),
    ("redo", u"\uf01e" , [ "solid" ] ),
    ("redo-alt", u"\uf2f9" , [ "solid" ] ),
    ("registered", u"\uf25d" , [ "solid", "regular" ] ),
    ("rendact", u"\uf3e4" , [ "brands" ] ),
    ("renren", u"\uf18b" , [ "brands" ] ),
    ("reply", u"\uf3e5" , [ "solid" ] ),
    ("reply-all", u"\uf122" , [ "solid" ] ),
    ("replyd", u"\uf3e6" , [ "brands" ] ),
    ("researchgate", u"\uf4f8" , [ "brands" ] ),
    ("resolving", u"\uf3e7" , [ "brands" ] ),
    ("retweet", u"\uf079" , [ "solid" ] ),
    ("rev", u"\uf5b2" , [ "brands" ] ),
    ("ribbon", u"\uf4d6" , [ "solid" ] ),
    ("ring", u"\uf70b" , [ "solid" ] ),
    ("road", u"\uf018" , [ "solid" ] ),
    ("robot", u"\uf544" , [ "solid" ] ),
    ("rocket", u"\uf135" , [ "solid" ] ),
    ("rocketchat", u"\uf3e8" , [ "brands" ] ),
    ("rockrms", u"\uf3e9" , [ "brands" ] ),
    ("route", u"\uf4d7" , [ "solid" ] ),
    ("rss", u"\uf09e" , [ "solid" ] ),
    ("rss-square", u"\uf143" , [ "solid" ] ),
    ("ruble-sign", u"\uf158" , [ "solid" ] ),
    ("ruler", u"\uf545" , [ "solid" ] ),
    ("ruler-combined", u"\uf546" , [ "solid" ] ),
    ("ruler-horizontal", u"\uf547" , [ "solid" ] ),
    ("ruler-vertical", u"\uf548" , [ "solid" ] ),
    ("running", u"\uf70c" , [ "solid" ] ),
    ("rupee-sign", u"\uf156" , [ "solid" ] ),
    ("sad-cry", u"\uf5b3" , [ "solid", "regular" ] ),
    ("sad-tear", u"\uf5b4" , [ "solid", "regular" ] ),
    ("safari", u"\uf267" , [ "brands" ] ),
    ("sass", u"\uf41e" , [ "brands" ] ),
    ("save", u"\uf0c7" , [ "solid", "regular" ] ),
    ("schlix", u"\uf3ea" , [ "brands" ] ),
    ("school", u"\uf549" , [ "solid" ] ),
    ("screwdriver", u"\uf54a" , [ "solid" ] ),
    ("scribd", u"\uf28a" , [ "brands" ] ),
    ("scroll", u"\uf70e" , [ "solid" ] ),
    ("search", u"\uf002" , [ "solid" ] ),
    ("search-dollar", u"\uf688" , [ "solid" ] ),
    ("search-location", u"\uf689" , [ "solid" ] ),
    ("search-minus", u"\uf010" , [ "solid" ] ),
    ("search-plus", u"\uf00e" , [ "solid" ] ),
    ("searchengin", u"\uf3eb" , [ "brands" ] ),
    ("seedling", u"\uf4d8" , [ "solid" ] ),
    ("sellcast", u"\uf2da" , [ "brands" ] ),
    ("sellsy", u"\uf213" , [ "brands" ] ),
    ("server", u"\uf233" , [ "solid" ] ),
    ("servicestack", u"\uf3ec" , [ "brands" ] ),
    ("shapes", u"\uf61f" , [ "solid" ] ),
    ("share", u"\uf064" , [ "solid" ] ),
    ("share-alt", u"\uf1e0" , [ "solid" ] ),
    ("share-alt-square", u"\uf1e1" , [ "solid" ] ),
    ("share-square", u"\uf14d" , [ "solid", "regular" ] ),
    ("shekel-sign", u"\uf20b" , [ "solid" ] ),
    ("shield-alt", u"\uf3ed" , [ "solid" ] ),
    ("ship", u"\uf21a" , [ "solid" ] ),
    ("shipping-fast", u"\uf48b" , [ "solid" ] ),
    ("shirtsinbulk", u"\uf214" , [ "brands" ] ),
    ("shoe-prints", u"\uf54b" , [ "solid" ] ),
    ("shopping-bag", u"\uf290" , [ "solid" ] ),
    ("shopping-basket", u"\uf291" , [ "solid" ] ),
    ("shopping-cart", u"\uf07a" , [ "solid" ] ),
    ("shopware", u"\uf5b5" , [ "brands" ] ),
    ("shower", u"\uf2cc" , [ "solid" ] ),
    ("shuttle-van", u"\uf5b6" , [ "solid" ] ),
    ("sign", u"\uf4d9" , [ "solid" ] ),
    ("sign-in-alt", u"\uf2f6" , [ "solid" ] ),
    ("sign-language", u"\uf2a7" , [ "solid" ] ),
    ("sign-out-alt", u"\uf2f5" , [ "solid" ] ),
    ("signal", u"\uf012" , [ "solid" ] ),
    ("signature", u"\uf5b7" , [ "solid" ] ),
    ("simplybuilt", u"\uf215" , [ "brands" ] ),
    ("sistrix", u"\uf3ee" , [ "brands" ] ),
    ("sitemap", u"\uf0e8" , [ "solid" ] ),
    ("sith", u"\uf512" , [ "brands" ] ),
    ("skull", u"\uf54c" , [ "solid" ] ),
    ("skull-crossbones", u"\uf714" , [ "solid" ] ),
    ("skyatlas", u"\uf216" , [ "brands" ] ),
    ("skype", u"\uf17e" , [ "brands" ] ),
    ("slack", u"\uf198" , [ "brands" ] ),
    ("slack-hash", u"\uf3ef" , [ "brands" ] ),
    ("slash", u"\uf715" , [ "solid" ] ),
    ("sliders-h", u"\uf1de" , [ "solid" ] ),
    ("slideshare", u"\uf1e7" , [ "brands" ] ),
    ("smile", u"\uf118" , [ "solid", "regular" ] ),
    ("smile-beam", u"\uf5b8" , [ "solid", "regular" ] ),
    ("smile-wink", u"\uf4da" , [ "solid", "regular" ] ),
    ("smoking", u"\uf48d" , [ "solid" ] ),
    ("smoking-ban", u"\uf54d" , [ "solid" ] ),
    ("snapchat", u"\uf2ab" , [ "brands" ] ),
    ("snapchat-ghost", u"\uf2ac" , [ "brands" ] ),
    ("snapchat-square", u"\uf2ad" , [ "brands" ] ),
    ("snowflake", u"\uf2dc" , [ "solid", "regular" ] ),
    ("socks", u"\uf696" , [ "solid" ] ),
    ("solar-panel", u"\uf5ba" , [ "solid" ] ),
    ("sort", u"\uf0dc" , [ "solid" ] ),
    ("sort-alpha-down", u"\uf15d" , [ "solid" ] ),
    ("sort-alpha-up", u"\uf15e" , [ "solid" ] ),
    ("sort-amount-down", u"\uf160" , [ "solid" ] ),
    ("sort-amount-up", u"\uf161" , [ "solid" ] ),
    ("sort-down", u"\uf0dd" , [ "solid" ] ),
    ("sort-numeric-down", u"\uf162" , [ "solid" ] ),
    ("sort-numeric-up", u"\uf163" , [ "solid" ] ),
    ("sort-up", u"\uf0de" , [ "solid" ] ),
    ("soundcloud", u"\uf1be" , [ "brands" ] ),
    ("spa", u"\uf5bb" , [ "solid" ] ),
    ("space-shuttle", u"\uf197" , [ "solid" ] ),
    ("speakap", u"\uf3f3" , [ "brands" ] ),
    ("spider", u"\uf717" , [ "solid" ] ),
    ("spinner", u"\uf110" , [ "solid" ] ),
    ("splotch", u"\uf5bc" , [ "solid" ] ),
    ("spotify", u"\uf1bc" , [ "brands" ] ),
    ("spray-can", u"\uf5bd" , [ "solid" ] ),
    ("square", u"\uf0c8" , [ "solid", "regular" ] ),
    ("square-full", u"\uf45c" , [ "solid" ] ),
    ("square-root-alt", u"\uf698" , [ "solid" ] ),
    ("squarespace", u"\uf5be" , [ "brands" ] ),
    ("stack-exchange", u"\uf18d" , [ "brands" ] ),
    ("stack-overflow", u"\uf16c" , [ "brands" ] ),
    ("stamp", u"\uf5bf" , [ "solid" ] ),
    ("star", u"\uf005" , [ "solid", "regular" ] ),
    ("star-and-crescent", u"\uf699" , [ "solid" ] ),
    ("star-half", u"\uf089" , [ "solid", "regular" ] ),
    ("star-half-alt", u"\uf5c0" , [ "solid" ] ),
    ("star-of-david", u"\uf69a" , [ "solid" ] ),
    ("star-of-life", u"\uf621" , [ "solid" ] ),
    ("staylinked", u"\uf3f5" , [ "brands" ] ),
    ("steam", u"\uf1b6" , [ "brands" ] ),
    ("steam-square", u"\uf1b7" , [ "brands" ] ),
    ("steam-symbol", u"\uf3f6" , [ "brands" ] ),
    ("step-backward", u"\uf048" , [ "solid" ] ),
    ("step-forward", u"\uf051" , [ "solid" ] ),
    ("stethoscope", u"\uf0f1" , [ "solid" ] ),
    ("sticker-mule", u"\uf3f7" , [ "brands" ] ),
    ("sticky-note", u"\uf249" , [ "solid", "regular" ] ),
    ("stop", u"\uf04d" , [ "solid" ] ),
    ("stop-circle", u"\uf28d" , [ "solid", "regular" ] ),
    ("stopwatch", u"\uf2f2" , [ "solid" ] ),
    ("store", u"\uf54e" , [ "solid" ] ),
    ("store-alt", u"\uf54f" , [ "solid" ] ),
    ("strava", u"\uf428" , [ "brands" ] ),
    ("stream", u"\uf550" , [ "solid" ] ),
    ("street-view", u"\uf21d" , [ "solid" ] ),
    ("strikethrough", u"\uf0cc" , [ "solid" ] ),
    ("stripe", u"\uf429" , [ "brands" ] ),
    ("stripe-s", u"\uf42a" , [ "brands" ] ),
    ("stroopwafel", u"\uf551" , [ "solid" ] ),
    ("studiovinari", u"\uf3f8" , [ "brands" ] ),
    ("stumbleupon", u"\uf1a4" , [ "brands" ] ),
    ("stumbleupon-circle", u"\uf1a3" , [ "brands" ] ),
    ("subscript", u"\uf12c" , [ "solid" ] ),
    ("subway", u"\uf239" , [ "solid" ] ),
    ("suitcase", u"\uf0f2" , [ "solid" ] ),
    ("suitcase-rolling", u"\uf5c1" , [ "solid" ] ),
    ("sun", u"\uf185" , [ "solid", "regular" ] ),
    ("superpowers", u"\uf2dd" , [ "brands" ] ),
    ("superscript", u"\uf12b" , [ "solid" ] ),
    ("supple", u"\uf3f9" , [ "brands" ] ),
    ("surprise", u"\uf5c2" , [ "solid", "regular" ] ),
    ("swatchbook", u"\uf5c3" , [ "solid" ] ),
    ("swimmer", u"\uf5c4" , [ "solid" ] ),
    ("swimming-pool", u"\uf5c5" , [ "solid" ] ),
    ("synagogue", u"\uf69b" , [ "solid" ] ),
    ("sync", u"\uf021" , [ "solid" ] ),
    ("sync-alt", u"\uf2f1" , [ "solid" ] ),
    ("syringe", u"\uf48e" , [ "solid" ] ),
    ("table", u"\uf0ce" , [ "solid" ] ),
    ("table-tennis", u"\uf45d" , [ "solid" ] ),
    ("tablet", u"\uf10a" , [ "solid" ] ),
    ("tablet-alt", u"\uf3fa" , [ "solid" ] ),
    ("tablets", u"\uf490" , [ "solid" ] ),
    ("tachometer-alt", u"\uf3fd" , [ "solid" ] ),
    ("tag", u"\uf02b" , [ "solid" ] ),
    ("tags", u"\uf02c" , [ "solid" ] ),
    ("tape", u"\uf4db" , [ "solid" ] ),
    ("tasks", u"\uf0ae" , [ "solid" ] ),
    ("taxi", u"\uf1ba" , [ "solid" ] ),
    ("teamspeak", u"\uf4f9" , [ "brands" ] ),
    ("teeth", u"\uf62e" , [ "solid" ] ),
    ("teeth-open", u"\uf62f" , [ "solid" ] ),
    ("telegram", u"\uf2c6" , [ "brands" ] ),
    ("telegram-plane", u"\uf3fe" , [ "brands" ] ),
    ("tencent-weibo", u"\uf1d5" , [ "brands" ] ),
    ("terminal", u"\uf120" , [ "solid" ] ),
    ("text-height", u"\uf034" , [ "solid" ] ),
    ("text-width", u"\uf035" , [ "solid" ] ),
    ("th", u"\uf00a" , [ "solid" ] ),
    ("th-large", u"\uf009" , [ "solid" ] ),
    ("th-list", u"\uf00b" , [ "solid" ] ),
    ("the-red-yeti", u"\uf69d" , [ "brands" ] ),
    ("theater-masks", u"\uf630" , [ "solid" ] ),
    ("themeco", u"\uf5c6" , [ "brands" ] ),
    ("themeisle", u"\uf2b2" , [ "brands" ] ),
    ("thermometer", u"\uf491" , [ "solid" ] ),
    ("thermometer-empty", u"\uf2cb" , [ "solid" ] ),
    ("thermometer-full", u"\uf2c7" , [ "solid" ] ),
    ("thermometer-half", u"\uf2c9" , [ "solid" ] ),
    ("thermometer-quarter", u"\uf2ca" , [ "solid" ] ),
    ("thermometer-three-quarters", u"\uf2c8" , [ "solid" ] ),
    ("thumbs-down", u"\uf165" , [ "solid", "regular" ] ),
    ("thumbs-up", u"\uf164" , [ "solid", "regular" ] ),
    ("thumbtack", u"\uf08d" , [ "solid" ] ),
    ("ticket-alt", u"\uf3ff" , [ "solid" ] ),
    ("times", u"\uf00d" , [ "solid" ] ),
    ("times-circle", u"\uf057" , [ "solid", "regular" ] ),
    ("tint", u"\uf043" , [ "solid" ] ),
    ("tint-slash", u"\uf5c7" , [ "solid" ] ),
    ("tired", u"\uf5c8" , [ "solid", "regular" ] ),
    ("toggle-off", u"\uf204" , [ "solid" ] ),
    ("toggle-on", u"\uf205" , [ "solid" ] ),
    ("toilet-paper", u"\uf71e" , [ "solid" ] ),
    ("toolbox", u"\uf552" , [ "solid" ] ),
    ("tooth", u"\uf5c9" , [ "solid" ] ),
    ("torah", u"\uf6a0" , [ "solid" ] ),
    ("torii-gate", u"\uf6a1" , [ "solid" ] ),
    ("tractor", u"\uf722" , [ "solid" ] ),
    ("trade-federation", u"\uf513" , [ "brands" ] ),
    ("trademark", u"\uf25c" , [ "solid" ] ),
    ("traffic-light", u"\uf637" , [ "solid" ] ),
    ("train", u"\uf238" , [ "solid" ] ),
    ("transgender", u"\uf224" , [ "solid" ] ),
    ("transgender-alt", u"\uf225" , [ "solid" ] ),
    ("trash", u"\uf1f8" , [ "solid" ] ),
    ("trash-alt", u"\uf2ed" , [ "solid", "regular" ] ),
    ("tree", u"\uf1bb" , [ "solid" ] ),
    ("trello", u"\uf181" , [ "brands" ] ),
    ("tripadvisor", u"\uf262" , [ "brands" ] ),
    ("trophy", u"\uf091" , [ "solid" ] ),
    ("truck", u"\uf0d1" , [ "solid" ] ),
    ("truck-loading", u"\uf4de" , [ "solid" ] ),
    ("truck-monster", u"\uf63b" , [ "solid" ] ),
    ("truck-moving", u"\uf4df" , [ "solid" ] ),
    ("truck-pickup", u"\uf63c" , [ "solid" ] ),
    ("tshirt", u"\uf553" , [ "solid" ] ),
    ("tty", u"\uf1e4" , [ "solid" ] ),
    ("tumblr", u"\uf173" , [ "brands" ] ),
    ("tumblr-square", u"\uf174" , [ "brands" ] ),
    ("tv", u"\uf26c" , [ "solid" ] ),
    ("twitch", u"\uf1e8" , [ "brands" ] ),
    ("twitter", u"\uf099" , [ "brands" ] ),
    ("twitter-square", u"\uf081" , [ "brands" ] ),
    ("typo3", u"\uf42b" , [ "brands" ] ),
    ("uber", u"\uf402" , [ "brands" ] ),
    ("uikit", u"\uf403" , [ "brands" ] ),
    ("umbrella", u"\uf0e9" , [ "solid" ] ),
    ("umbrella-beach", u"\uf5ca" , [ "solid" ] ),
    ("underline", u"\uf0cd" , [ "solid" ] ),
    ("undo", u"\uf0e2" , [ "solid" ] ),
    ("undo-alt", u"\uf2ea" , [ "solid" ] ),
    ("uniregistry", u"\uf404" , [ "brands" ] ),
    ("universal-access", u"\uf29a" , [ "solid" ] ),
    ("university", u"\uf19c" , [ "solid" ] ),
    ("unlink", u"\uf127" , [ "solid" ] ),
    ("unlock", u"\uf09c" , [ "solid" ] ),
    ("unlock-alt", u"\uf13e" , [ "solid" ] ),
    ("untappd", u"\uf405" , [ "brands" ] ),
    ("upload", u"\uf093" , [ "solid" ] ),
    ("usb", u"\uf287" , [ "brands" ] ),
    ("user", u"\uf007" , [ "solid", "regular" ] ),
    ("user-alt", u"\uf406" , [ "solid" ] ),
    ("user-alt-slash", u"\uf4fa" , [ "solid" ] ),
    ("user-astronaut", u"\uf4fb" , [ "solid" ] ),
    ("user-check", u"\uf4fc" , [ "solid" ] ),
    ("user-circle", u"\uf2bd" , [ "solid", "regular" ] ),
    ("user-clock", u"\uf4fd" , [ "solid" ] ),
    ("user-cog", u"\uf4fe" , [ "solid" ] ),
    ("user-edit", u"\uf4ff" , [ "solid" ] ),
    ("user-friends", u"\uf500" , [ "solid" ] ),
    ("user-graduate", u"\uf501" , [ "solid" ] ),
    ("user-injured", u"\uf728" , [ "solid" ] ),
    ("user-lock", u"\uf502" , [ "solid" ] ),
    ("user-md", u"\uf0f0" , [ "solid" ] ),
    ("user-minus", u"\uf503" , [ "solid" ] ),
    ("user-ninja", u"\uf504" , [ "solid" ] ),
    ("user-plus", u"\uf234" , [ "solid" ] ),
    ("user-secret", u"\uf21b" , [ "solid" ] ),
    ("user-shield", u"\uf505" , [ "solid" ] ),
    ("user-slash", u"\uf506" , [ "solid" ] ),
    ("user-tag", u"\uf507" , [ "solid" ] ),
    ("user-tie", u"\uf508" , [ "solid" ] ),
    ("user-times", u"\uf235" , [ "solid" ] ),
    ("users", u"\uf0c0" , [ "solid" ] ),
    ("users-cog", u"\uf509" , [ "solid" ] ),
    ("ussunnah", u"\uf407" , [ "brands" ] ),
    ("utensil-spoon", u"\uf2e5" , [ "solid" ] ),
    ("utensils", u"\uf2e7" , [ "solid" ] ),
    ("vaadin", u"\uf408" , [ "brands" ] ),
    ("vector-square", u"\uf5cb" , [ "solid" ] ),
    ("venus", u"\uf221" , [ "solid" ] ),
    ("venus-double", u"\uf226" , [ "solid" ] ),
    ("venus-mars", u"\uf228" , [ "solid" ] ),
    ("viacoin", u"\uf237" , [ "brands" ] ),
    ("viadeo", u"\uf2a9" , [ "brands" ] ),
    ("viadeo-square", u"\uf2aa" , [ "brands" ] ),
    ("vial", u"\uf492" , [ "solid" ] ),
    ("vials", u"\uf493" , [ "solid" ] ),
    ("viber", u"\uf409" , [ "brands" ] ),
    ("video", u"\uf03d" , [ "solid" ] ),
    ("video-slash", u"\uf4e2" , [ "solid" ] ),
    ("vihara", u"\uf6a7" , [ "solid" ] ),
    ("vimeo", u"\uf40a" , [ "brands" ] ),
    ("vimeo-square", u"\uf194" , [ "brands" ] ),
    ("vimeo-v", u"\uf27d" , [ "brands" ] ),
    ("vine", u"\uf1ca" , [ "brands" ] ),
    ("vk", u"\uf189" , [ "brands" ] ),
    ("vnv", u"\uf40b" , [ "brands" ] ),
    ("volleyball-ball", u"\uf45f" , [ "solid" ] ),
    ("volume-down", u"\uf027" , [ "solid" ] ),
    ("volume-mute", u"\uf6a9" , [ "solid" ] ),
    ("volume-off", u"\uf026" , [ "solid" ] ),
    ("volume-up", u"\uf028" , [ "solid" ] ),
    ("vuejs", u"\uf41f" , [ "brands" ] ),
    ("walking", u"\uf554" , [ "solid" ] ),
    ("wallet", u"\uf555" , [ "solid" ] ),
    ("warehouse", u"\uf494" , [ "solid" ] ),
    ("weebly", u"\uf5cc" , [ "brands" ] ),
    ("weibo", u"\uf18a" , [ "brands" ] ),
    ("weight", u"\uf496" , [ "solid" ] ),
    ("weight-hanging", u"\uf5cd" , [ "solid" ] ),
    ("weixin", u"\uf1d7" , [ "brands" ] ),
    ("whatsapp", u"\uf232" , [ "brands" ] ),
    ("whatsapp-square", u"\uf40c" , [ "brands" ] ),
    ("wheelchair", u"\uf193" , [ "solid" ] ),
    ("whmcs", u"\uf40d" , [ "brands" ] ),
    ("wifi", u"\uf1eb" , [ "solid" ] ),
    ("wikipedia-w", u"\uf266" , [ "brands" ] ),
    ("wind", u"\uf72e" , [ "solid" ] ),
    ("window-close", u"\uf410" , [ "solid", "regular" ] ),
    ("window-maximize", u"\uf2d0" , [ "solid", "regular" ] ),
    ("window-minimize", u"\uf2d1" , [ "solid", "regular" ] ),
    ("window-restore", u"\uf2d2" , [ "solid", "regular" ] ),
    ("windows", u"\uf17a" , [ "brands" ] ),
    ("wine-bottle", u"\uf72f" , [ "solid" ] ),
    ("wine-glass", u"\uf4e3" , [ "solid" ] ),
    ("wine-glass-alt", u"\uf5ce" , [ "solid" ] ),
    ("wix", u"\uf5cf" , [ "brands" ] ),
    ("wizards-of-the-coast", u"\uf730" , [ "brands" ] ),
    ("wolf-pack-battalion", u"\uf514" , [ "brands" ] ),
    ("won-sign", u"\uf159" , [ "solid" ] ),
    ("wordpress", u"\uf19a" , [ "brands" ] ),
    ("wordpress-simple", u"\uf411" , [ "brands" ] ),
    ("wpbeginner", u"\uf297" , [ "brands" ] ),
    ("wpexplorer", u"\uf2de" , [ "brands" ] ),
    ("wpforms", u"\uf298" , [ "brands" ] ),
    ("wrench", u"\uf0ad" , [ "solid" ] ),
    ("x-ray", u"\uf497" , [ "solid" ] ),
    ("xbox", u"\uf412" , [ "brands" ] ),
    ("xing", u"\uf168" , [ "brands" ] ),
    ("xing-square", u"\uf169" , [ "brands" ] ),
    ("y-combinator", u"\uf23b" , [ "brands" ] ),
    ("yahoo", u"\uf19e" , [ "brands" ] ),
    ("yandex", u"\uf413" , [ "brands" ] ),
    ("yandex-international", u"\uf414" , [ "brands" ] ),
    ("yelp", u"\uf1e9" , [ "brands" ] ),
    ("yen-sign", u"\uf157" , [ "solid" ] ),
    ("yin-yang", u"\uf6ad" , [ "solid" ] ),
    ("yoast", u"\uf2b1" , [ "brands" ] ),
    ("youtube", u"\uf167" , [ "brands" ] ),
    ("youtube-square", u"\uf431" , [ "brands" ] ),
    ("zhihu", u"\uf63f", ["brands"] )
]

# category definitions, version fontawesome-free-5.4.1-desktop
categories = [
    ( "Accessibility", [ "accessible-icon", "american-sign-language-interpreting", "assistive-listening-systems", "audio-description", "blind", "braille", "closed-captioning", "deaf", "low-vision", "phone-volume", "question-circle", "sign-language", "tty", "universal-access", "wheelchair"] ),
    ( "Animals", [ "cat", "crow", "dog", "dove", "dragon", "feather", "feather-alt", "fish", "frog", "hippo", "horse", "kiwi-bird", "otter", "paw", "spider"] ),
    ( "Arrows", [ "angle-double-down", "angle-double-left", "angle-double-right", "angle-double-up", "angle-down", "angle-left", "angle-right", "angle-up", "arrow-alt-circle-down", "arrow-alt-circle-left", "arrow-alt-circle-right", "arrow-alt-circle-up", "arrow-circle-down", "arrow-circle-left", "arrow-circle-right", "arrow-circle-up", "arrow-down", "arrow-left", "arrow-right", "arrow-up", "arrows-alt", "arrows-alt-h", "arrows-alt-v", "caret-down", "caret-left", "caret-right", "caret-square-down", "caret-square-left", "caret-square-right", "caret-square-up", "caret-up", "cart-arrow-down", "chart-line", "chevron-circle-down", "chevron-circle-left", "chevron-circle-right", "chevron-circle-up", "chevron-down", "chevron-left", "chevron-right", "chevron-up", "cloud-download-alt", "cloud-upload-alt", "download", "exchange-alt", "expand-arrows-alt", "external-link-alt", "external-link-square-alt", "hand-point-down", "hand-point-left", "hand-point-right", "hand-point-up", "hand-pointer", "history", "level-down-alt", "level-up-alt", "location-arrow", "long-arrow-alt-down", "long-arrow-alt-left", "long-arrow-alt-right", "long-arrow-alt-up", "mouse-pointer", "play", "random", "recycle", "redo", "redo-alt", "reply", "reply-all", "retweet", "share", "share-square", "sign-in-alt", "sign-out-alt", "sort", "sort-alpha-down", "sort-alpha-up", "sort-amount-down", "sort-amount-up", "sort-down", "sort-numeric-down", "sort-numeric-up", "sort-up", "sync", "sync-alt", "text-height", "text-width", "undo", "undo-alt", "upload"] ),
    ( "Audio & Video", [ "audio-description", "backward", "broadcast-tower", "circle", "closed-captioning", "compress", "eject", "expand", "expand-arrows-alt", "fast-backward", "fast-forward", "file-audio", "file-video", "film", "forward", "headphones", "microphone", "microphone-alt", "microphone-alt-slash", "microphone-slash", "music", "pause", "pause-circle", "phone-volume", "play", "play-circle", "podcast", "random", "redo", "redo-alt", "rss", "rss-square", "step-backward", "step-forward", "stop", "stop-circle", "sync", "sync-alt", "undo", "undo-alt", "video", "volume-down", "volume-mute", "volume-off", "volume-up", "youtube"] ),
    ( "Automotive", [ "air-freshener", "ambulance", "bus", "bus-alt", "car", "car-alt", "car-battery", "car-crash", "car-side", "charging-station", "gas-pump", "motorcycle", "oil-can", "shuttle-van", "tachometer-alt", "taxi", "truck", "truck-monster", "truck-pickup"] ),
    ( "Autumn", [ "apple-alt", "campground", "cloud-sun", "drumstick-bite", "football-ball", "hiking", "mountain", "tractor", "tree", "wind", "wine-bottle"] ),
    ( "Buildings", [ "building", "church", "gopuram", "home", "hospital", "hospital-alt", "house-damage", "industry", "mosque", "place-of-worship", "school", "synagogue", "torii-gate", "university", "vihara"] ),
    ( "Business", [ "address-book", "address-card", "archive", "balance-scale", "birthday-cake", "book", "briefcase", "building", "bullhorn", "bullseye", "business-time", "calculator", "calendar", "calendar-alt", "certificate", "chart-area", "chart-bar", "chart-line", "chart-pie", "city", "clipboard", "coffee", "columns", "compass", "copy", "copyright", "cut", "edit", "envelope", "envelope-open", "envelope-square", "eraser", "fax", "file", "file-alt", "folder", "folder-minus", "folder-open", "folder-plus", "glasses", "globe", "highlighter", "industry", "landmark", "marker", "paperclip", "paste", "pen", "pen-alt", "pen-fancy", "pen-nib", "pen-square", "pencil-alt", "percent", "phone", "phone-slash", "phone-square", "phone-volume", "print", "project-diagram", "registered", "save", "sitemap", "socks", "sticky-note", "stream", "table", "tag", "tags", "tasks", "thumbtack", "trademark", "wallet"] ),
    ( "Charity", [ "dollar-sign", "donate", "dove", "gift", "globe", "hand-holding-heart", "hand-holding-usd", "hands-helping", "handshake", "heart", "leaf", "parachute-box", "piggy-bank", "ribbon", "seedling"] ),
    ( "Chat", [ "comment", "comment-alt", "comment-dots", "comment-slash", "comments", "frown", "meh", "phone", "phone-slash", "poo", "quote-left", "quote-right", "smile", "video", "video-slash"] ),
    ( "Chess", [ "chess", "chess-bishop", "chess-board", "chess-king", "chess-knight", "chess-pawn", "chess-queen", "chess-rook", "square-full"] ),
    ( "Code", [ "archive", "barcode", "bath", "bug", "code", "code-branch", "coffee", "file", "file-alt", "file-code", "filter", "fire-extinguisher", "folder", "folder-open", "keyboard", "microchip", "project-diagram", "qrcode", "shield-alt", "sitemap", "stream", "terminal", "user-secret", "window-close", "window-maximize", "window-minimize", "window-restore"] ),
    ( "Communication", [ "address-book", "address-card", "american-sign-language-interpreting", "assistive-listening-systems", "at", "bell", "bell-slash", "bluetooth", "bluetooth-b", "broadcast-tower", "bullhorn", "chalkboard", "comment", "comment-alt", "comments", "envelope", "envelope-open", "envelope-square", "fax", "inbox", "language", "microphone", "microphone-alt", "microphone-alt-slash", "microphone-slash", "mobile", "mobile-alt", "paper-plane", "phone", "phone-slash", "phone-square", "phone-volume", "rss", "rss-square", "tty", "wifi"] ),
    ( "Computers", [ "database", "desktop", "download", "hdd", "headphones", "keyboard", "laptop", "memory", "microchip", "mobile", "mobile-alt", "plug", "power-off", "print", "save", "server", "stream", "tablet", "tablet-alt", "tv", "upload"] ),
    ( "Currency", [ "bitcoin", "btc", "dollar-sign", "ethereum", "euro-sign", "gg", "gg-circle", "hryvnia", "lira-sign", "money-bill", "money-bill-alt", "money-bill-wave", "money-bill-wave-alt", "money-check", "money-check-alt", "pound-sign", "ruble-sign", "rupee-sign", "shekel-sign", "won-sign", "yen-sign"] ),
    ( "Date & Time", [ "bell", "bell-slash", "calendar", "calendar-alt", "calendar-check", "calendar-minus", "calendar-plus", "calendar-times", "clock", "hourglass", "hourglass-end", "hourglass-half", "hourglass-start", "stopwatch"] ),
    ( "Design", [ "adjust", "bezier-curve", "brush", "clone", "copy", "crop", "crop-alt", "crosshairs", "cut", "drafting-compass", "draw-polygon", "edit", "eraser", "eye", "eye-dropper", "eye-slash", "fill", "fill-drip", "highlighter", "layer-group", "magic", "marker", "object-group", "object-ungroup", "paint-brush", "paint-roller", "palette", "paste", "pen", "pen-alt", "pen-fancy", "pen-nib", "pencil-alt", "pencil-ruler", "ruler-combined", "ruler-horizontal", "ruler-vertical", "save", "splotch", "spray-can", "stamp", "swatchbook", "tint", "tint-slash", "vector-square"] ),
    ( "Editors", [ "align-center", "align-justify", "align-left", "align-right", "bold", "clipboard", "clone", "columns", "copy", "cut", "edit", "eraser", "file", "file-alt", "font", "glasses", "heading", "highlighter", "i-cursor", "indent", "italic", "link", "list", "list-alt", "list-ol", "list-ul", "marker", "outdent", "paper-plane", "paperclip", "paragraph", "paste", "pen", "pen-alt", "pen-fancy", "pen-nib", "pencil-alt", "print", "quote-left", "quote-right", "redo", "redo-alt", "reply", "reply-all", "screwdriver", "share", "strikethrough", "subscript", "superscript", "sync", "sync-alt", "table", "tasks", "text-height", "text-width", "th", "th-large", "th-list", "trash", "trash-alt", "underline", "undo", "undo-alt", "unlink", "wrench"] ),
    ( "Education", [ "apple-alt", "atom", "award", "bell", "bell-slash", "book-open", "book-reader", "chalkboard", "chalkboard-teacher", "graduation-cap", "laptop-code", "microscope", "music", "school", "shapes", "theater-masks", "user-graduate"] ),
    ( "Emoji", [ "angry", "dizzy", "flushed", "frown", "frown-open", "grimace", "grin", "grin-alt", "grin-beam", "grin-beam-sweat", "grin-hearts", "grin-squint", "grin-squint-tears", "grin-stars", "grin-tears", "grin-tongue", "grin-tongue-squint", "grin-tongue-wink", "grin-wink", "kiss", "kiss-beam", "kiss-wink-heart", "laugh", "laugh-beam", "laugh-squint", "laugh-wink", "meh", "meh-blank", "meh-rolling-eyes", "sad-cry", "sad-tear", "smile", "smile-beam", "smile-wink", "surprise", "tired"] ),
    ( "Files", [ "archive", "clone", "copy", "cut", "file", "file-alt", "file-archive", "file-audio", "file-code", "file-excel", "file-image", "file-pdf", "file-powerpoint", "file-video", "file-word", "folder", "folder-open", "paste", "save", "sticky-note"] ),
    ( "Tabletop Gaming", [ "acquisitions-incorporated", "book-dead", "critical-role", "d-and-d", "dice-d20", "dice-d6", "dragon", "dungeon", "fantasy-flight-games", "fist-raised", "hat-wizard", "penny-arcade", "ring", "scroll", "skull-crossbones", "wizards-of-the-coast"] ),
    ( "Genders", [ "genderless", "mars", "mars-double", "mars-stroke", "mars-stroke-h", "mars-stroke-v", "mercury", "neuter", "transgender", "transgender-alt", "venus", "venus-double", "venus-mars"] ),
    ( "Halloween", [ "book-dead", "broom", "cat", "cloud-moon", "crow", "ghost", "hat-wizard", "mask", "skull-crossbones", "spider", "toilet-paper"] ),
    ( "Hands", [ "allergies", "fist-raised", "hand-holding", "hand-lizard", "hand-paper", "hand-peace", "hand-point-down", "hand-point-left", "hand-point-right", "hand-point-up", "hand-pointer", "hand-rock", "hand-scissors", "hand-spock", "hands", "handshake", "thumbs-down", "thumbs-up"] ),
    ( "Health", [ "accessible-icon", "ambulance", "h-square", "heart", "heartbeat", "hospital", "medkit", "plus-square", "prescription", "stethoscope", "user-md", "wheelchair"] ),
    ( "Images", [ "adjust", "bolt", "camera", "camera-retro", "chalkboard", "clone", "compress", "expand", "eye", "eye-dropper", "eye-slash", "file-image", "film", "id-badge", "id-card", "image", "images", "portrait", "sliders-h", "tint"] ),
    ( "Interfaces", [ "award", "ban", "barcode", "bars", "beer", "bell", "bell-slash", "bug", "bullhorn", "bullseye", "calculator", "calendar", "calendar-alt", "calendar-check", "calendar-minus", "calendar-plus", "calendar-times", "certificate", "check", "check-circle", "check-double", "check-square", "circle", "clipboard", "clone", "cloud", "cloud-download-alt", "cloud-upload-alt", "coffee", "cog", "cogs", "copy", "cut", "database", "dot-circle", "download", "edit", "ellipsis-h", "ellipsis-v", "envelope", "envelope-open", "eraser", "exclamation", "exclamation-circle", "exclamation-triangle", "external-link-alt", "external-link-square-alt", "eye", "eye-slash", "file", "file-alt", "file-download", "file-export", "file-import", "file-upload", "filter", "fingerprint", "flag", "flag-checkered", "folder", "folder-open", "frown", "glasses", "grip-horizontal", "grip-vertical", "hashtag", "heart", "history", "home", "i-cursor", "info", "info-circle", "language", "magic", "marker", "medal", "meh", "microphone", "microphone-alt", "microphone-slash", "minus", "minus-circle", "minus-square", "paste", "pen", "pen-alt", "pen-fancy", "pencil-alt", "plus", "plus-circle", "plus-square", "poo", "qrcode", "question", "question-circle", "quote-left", "quote-right", "redo", "redo-alt", "reply", "reply-all", "rss", "rss-square", "save", "screwdriver", "search", "search-minus", "search-plus", "share", "share-alt", "share-alt-square", "share-square", "shield-alt", "sign-in-alt", "sign-out-alt", "signal", "sitemap", "sliders-h", "smile", "sort", "sort-alpha-down", "sort-alpha-up", "sort-amount-down", "sort-amount-up", "sort-down", "sort-numeric-down", "sort-numeric-up", "sort-up", "star", "star-half", "sync", "sync-alt", "thumbs-down", "thumbs-up", "times", "times-circle", "toggle-off", "toggle-on", "trash", "trash-alt", "trophy", "undo", "undo-alt", "upload", "user", "user-alt", "user-circle", "volume-down", "volume-mute", "volume-off", "volume-up", "wifi", "wrench"] ),
    ( "Logistics", [ "box", "boxes", "clipboard-check", "clipboard-list", "dolly", "dolly-flatbed", "pallet", "shipping-fast", "truck", "warehouse"] ),
    ( "Maps", [ "ambulance", "anchor", "balance-scale", "bath", "bed", "beer", "bell", "bell-slash", "bicycle", "binoculars", "birthday-cake", "blind", "bomb", "book", "bookmark", "briefcase", "building", "car", "coffee", "crosshairs", "directions", "dollar-sign", "draw-polygon", "eye", "eye-slash", "fighter-jet", "fire", "fire-extinguisher", "flag", "flag-checkered", "flask", "gamepad", "gavel", "gift", "glass-martini", "globe", "graduation-cap", "h-square", "heart", "heartbeat", "helicopter", "home", "hospital", "image", "images", "industry", "info", "info-circle", "key", "landmark", "layer-group", "leaf", "lemon", "life-ring", "lightbulb", "location-arrow", "low-vision", "magnet", "male", "map", "map-marker", "map-marker-alt", "map-pin", "map-signs", "medkit", "money-bill", "money-bill-alt", "motorcycle", "music", "newspaper", "parking", "paw", "phone", "phone-square", "phone-volume", "plane", "plug", "plus", "plus-square", "print", "recycle", "road", "rocket", "route", "search", "search-minus", "search-plus", "ship", "shoe-prints", "shopping-bag", "shopping-basket", "shopping-cart", "shower", "street-view", "subway", "suitcase", "tag", "tags", "taxi", "thumbtack", "ticket-alt", "tint", "traffic-light", "train", "tree", "trophy", "truck", "tty", "umbrella", "university", "utensil-spoon", "utensils", "wheelchair", "wifi", "wine-glass", "wrench"] ),
    ( "Marketing", [ "ad", "bullhorn", "bullseye", "comment-dollar", "comments-dollar", "envelope-open-text", "funnel-dollar", "lightbulb", "mail-bulk", "poll", "poll-h", "search-dollar", "search-location"] ),
    ( "Mathematics", [ "calculator", "divide", "equals", "greater-than", "greater-than-equal", "infinity", "less-than", "less-than-equal", "minus", "not-equal", "percentage", "plus", "square-root-alt", "subscript", "superscript", "times"] ),
    ( "Medical", [ "allergies", "ambulance", "band-aid", "bone", "bong", "brain", "briefcase-medical", "burn", "cannabis", "capsules", "diagnoses", "dna", "file-medical", "file-medical-alt", "file-prescription", "first-aid", "heart", "heartbeat", "hospital", "hospital-alt", "hospital-symbol", "id-card-alt", "joint", "microscope", "mortar-pestle", "notes-medical", "pills", "plus", "poop", "prescription", "prescription-bottle", "prescription-bottle-alt", "procedures", "smoking", "smoking-ban", "star-of-life", "stethoscope", "syringe", "tablets", "teeth", "teeth-open", "thermometer", "tooth", "user-md", "vial", "vials", "weight", "x-ray"] ),
    ( "Moving", [ "archive", "box-open", "couch", "dolly", "people-carry", "route", "sign", "suitcase", "tape", "truck-loading", "truck-moving", "wine-glass"] ),
    ( "Objects", [ "ambulance", "anchor", "archive", "award", "balance-scale", "bath", "bed", "beer", "bell", "bicycle", "binoculars", "birthday-cake", "blender", "bomb", "book", "book-dead", "bookmark", "briefcase", "broadcast-tower", "bug", "building", "bullhorn", "bullseye", "bus", "calculator", "calendar", "calendar-alt", "camera", "camera-retro", "car", "church", "clipboard", "cloud", "coffee", "cog", "cogs", "compass", "cookie", "cookie-bite", "copy", "cube", "cubes", "cut", "dice", "dice-d20", "dice-d6", "dice-five", "dice-four", "dice-one", "dice-six", "dice-three", "dice-two", "digital-tachograph", "door-closed", "door-open", "drum", "drum-steelpan", "envelope", "envelope-open", "eraser", "eye", "eye-dropper", "fax", "feather", "feather-alt", "fighter-jet", "file", "file-alt", "file-prescription", "film", "fire", "fire-extinguisher", "flag", "flag-checkered", "flask", "futbol", "gamepad", "gavel", "gem", "gift", "glass-martini", "glasses", "globe", "graduation-cap", "hat-wizard", "hdd", "headphones", "headphones-alt", "headset", "heart", "helicopter", "highlighter", "home", "hospital", "hourglass", "image", "images", "industry", "key", "keyboard", "laptop", "leaf", "lemon", "life-ring", "lightbulb", "lock", "lock-open", "magic", "magnet", "map", "map-marker", "map-marker-alt", "map-pin", "map-signs", "marker", "medal", "medkit", "memory", "microchip", "microphone", "microphone-alt", "mobile", "mobile-alt", "money-bill", "money-bill-alt", "money-check", "money-check-alt", "moon", "motorcycle", "newspaper", "paint-brush", "paper-plane", "paperclip", "paste", "paw", "pen", "pen-alt", "pen-fancy", "pen-nib", "pencil-alt", "phone", "plane", "plug", "print", "puzzle-piece", "ring", "road", "rocket", "ruler-combined", "ruler-horizontal", "ruler-vertical", "save", "school", "screwdriver", "scroll", "search", "shield-alt", "shopping-bag", "shopping-basket", "shopping-cart", "shower", "skull-crossbones", "snowflake", "space-shuttle", "star", "sticky-note", "stopwatch", "stroopwafel", "subway", "suitcase", "sun", "tablet", "tablet-alt", "tachometer-alt", "tag", "tags", "taxi", "thumbtack", "ticket-alt", "toolbox", "train", "trash", "trash-alt", "tree", "trophy", "truck", "tv", "umbrella", "university", "unlock", "unlock-alt", "utensil-spoon", "utensils", "wallet", "weight", "wheelchair", "wine-glass", "wrench"] ),
    ( "Payments & Shopping", [ "alipay", "amazon-pay", "apple-pay", "bell", "bitcoin", "bookmark", "btc", "bullhorn", "camera", "camera-retro", "cart-arrow-down", "cart-plus", "cc-amazon-pay", "cc-amex", "cc-apple-pay", "cc-diners-club", "cc-discover", "cc-jcb", "cc-mastercard", "cc-paypal", "cc-stripe", "cc-visa", "certificate", "credit-card", "ethereum", "gem", "gift", "google-wallet", "handshake", "heart", "key", "money-check", "money-check-alt", "paypal", "shopping-bag", "shopping-basket", "shopping-cart", "star", "stripe", "stripe-s", "tag", "tags", "thumbs-down", "thumbs-up", "trophy"] ),
    ( "Religion", [ "ankh", "atom", "bible", "church", "cross", "dharmachakra", "dove", "gopuram", "hamsa", "hanukiah", "haykal", "jedi", "journal-whills", "kaaba", "khanda", "menorah", "mosque", "om", "pastafarianism", "peace", "place-of-worship", "pray", "praying-hands", "quran", "star-and-crescent", "star-of-david", "synagogue", "torah", "torii-gate", "vihara", "yin-yang"] ),
    ( "Shapes", [ "bookmark", "calendar", "certificate", "circle", "cloud", "comment", "file", "folder", "heart", "map-marker", "play", "shapes", "square", "star"] ),
    ( "Spinners", [ "asterisk", "certificate", "circle-notch", "cog", "compass", "crosshairs", "life-ring", "snowflake", "spinner", "sun", "sync"] ),
    ( "Sports", [ "baseball-ball", "basketball-ball", "bowling-ball", "dumbbell", "football-ball", "futbol", "golf-ball", "hockey-puck", "quidditch", "table-tennis", "volleyball-ball"] ),
    ( "Status", [ "ban", "battery-empty", "battery-full", "battery-half", "battery-quarter", "battery-three-quarters", "bell", "bell-slash", "calendar", "calendar-alt", "calendar-check", "calendar-minus", "calendar-plus", "calendar-times", "cart-arrow-down", "cart-plus", "comment", "comment-alt", "comment-slash", "compass", "door-closed", "door-open", "exclamation", "exclamation-circle", "exclamation-triangle", "eye", "eye-slash", "file", "file-alt", "folder", "folder-open", "gas-pump", "info", "info-circle", "lightbulb", "lock", "lock-open", "map-marker", "map-marker-alt", "microphone", "microphone-alt", "microphone-alt-slash", "microphone-slash", "minus", "minus-circle", "minus-square", "parking", "phone", "phone-slash", "plus", "plus-circle", "plus-square", "print", "question", "question-circle", "shield-alt", "shopping-cart", "sign-in-alt", "sign-out-alt", "signal", "smoking-ban", "star", "star-half", "star-half-alt", "stream", "thermometer-empty", "thermometer-full", "thermometer-half", "thermometer-quarter", "thermometer-three-quarters", "thumbs-down", "thumbs-up", "tint", "tint-slash", "toggle-off", "toggle-on", "unlock", "unlock-alt", "user", "user-alt", "user-alt-slash", "user-slash", "video", "video-slash", "volume-down", "volume-mute", "volume-off", "volume-up", "wifi"] ),
    ( "Travel", [ "archway", "atlas", "bed", "bus", "bus-alt", "cocktail", "concierge-bell", "dumbbell", "glass-martini", "glass-martini-alt", "globe-africa", "globe-americas", "globe-asia", "hot-tub", "hotel", "luggage-cart", "map", "map-marked", "map-marked-alt", "monument", "passport", "plane", "plane-arrival", "plane-departure", "shuttle-van", "spa", "suitcase", "suitcase-rolling", "swimmer", "swimming-pool", "taxi", "umbrella-beach", "wine-glass", "wine-glass-alt"] ),
    ( "Users & People", [ "accessible-icon", "address-book", "address-card", "bed", "blind", "chalkboard-teacher", "child", "female", "frown", "id-badge", "id-card", "id-card-alt", "male", "meh", "poo", "portrait", "power-off", "smile", "street-view", "user", "user-alt", "user-alt-slash", "user-astronaut", "user-check", "user-circle", "user-clock", "user-cog", "user-edit", "user-friends", "user-graduate", "user-injured", "user-lock", "user-md", "user-minus", "user-ninja", "user-plus", "user-secret", "user-shield", "user-slash", "user-tag", "user-tie", "user-times", "users", "wheelchair"] ),
    ( "Vehicles", [ "accessible-icon", "ambulance", "bicycle", "bus", "bus-alt", "car", "car-alt", "car-crash", "car-side", "fighter-jet", "helicopter", "motorcycle", "paper-plane", "plane", "rocket", "ship", "shopping-cart", "shuttle-van", "space-shuttle", "subway", "taxi", "train", "truck", "truck-monster", "truck-pickup", "wheelchair"] ),
    ( "Writing", [ "archive", "book", "bookmark", "edit", "envelope", "envelope-open", "eraser", "file", "file-alt", "folder", "folder-open", "keyboard", "newspaper", "paper-plane", "paperclip", "paragraph", "pen", "pen-alt", "pen-square", "pencil-alt", "quote-left", "quote-right", "sticky-note", "thumbtack"] )
]

# create gallery for each font-style (regular/solid/brands)
# [ symbol-gallery-item, symbol-gallery-item, ... ]
# symbol-gallery-item = [fontname, character-id, label]
symbols_all_regular = [
    ("Font Awesome 5 Free Regular", uid, icon_name)
    for (icon_name, uid, styles) in fa5_icons
    if "regular" in styles
]

symbols_all_solid = [
    ("Font Awesome 5 Free Solid", uid, icon_name)
    for (icon_name, uid, styles) in fa5_icons
    if "solid" in styles
]

symbols_all_brands = [
    ("Font Awesome 5 Brands Regular", uid, icon_name)
    for (icon_name, uid, styles) in fa5_icons
    if "brands" in styles
]

def get_content_categories():
    # full font names
    font_name_hash = {
        'regular': "Font Awesome 5 Free Regular",
        'solid':   "Font Awesome 5 Free Solid",
        'brands':  "Font Awesome 5 Brands Regular"
    }

    # hash for fa5-icons
    # { icon_name: symbol-gallery-item, ...}
    # symbol-gallery-item = [fontname, character-id, label]
    fa5_icons_hash = {
        icon_name: [ [ font_name_hash[style], uid, "%s, unicode character %s, %s" % (font_name_hash[style], format(ord(uid), '02x'), icon_name)  ] for style in styles]
        for (icon_name, uid, styles) in fa5_icons
    }

    # create gallery-tuples for each category
    # (category-label, symbol-list)
    # symbol-list = [ symbol-gallery-item, symbol-gallery-item, ... ]
    # symbol-gallery-item = [fontname, character-id, label]
    category_icons = [
        (label.replace("&", "and"), [ icon for icon_name in icon_names for icon in fa5_icons_hash[icon_name]], 10)
        for (label, icon_names) in categories
    ]

    return bkt.ribbon.Menu(
                xmlns="http://schemas.microsoft.com/office/2009/07/customui",
                id=None,
                children=[
                    PPTSymbolsGallery(label="{} ({})".format(label, len(symbollist)), symbols=symbollist, columns=columns)
                    for (label, symbollist, columns) in category_icons
                ]
            )


# define the menu parts

menu_title = 'Font Awesome 5 Free'

menu_settings = [
    # menu label,          list of symbols,       icons per row
    ('Regular',            symbols_all_regular,          16  ),
    ('Solid',              symbols_all_solid,            16  ),
    ('Brands',             symbols_all_brands,           16  ),
    # ('IT-System',          symbols_itsystems_5,           6  ),
    # ('Kommunikation',      symbols_communication_5,       6  ),
    # ('Dateien',            symbols_files_5,               6  ),
    # ('Analyse/Bewertung',  symbols_analysis_5,            6  ),
    # ('Mixed',              symbols_mixed_5,               6  ),
]

menus = [
    PPTSymbolsGallery(label="{} ({})".format(label, len(symbollist)), symbols=symbollist, columns=columns)
    for (label, symbollist, columns) in menu_settings
] + [
    # submenu for categories
    bkt.ribbon.DynamicMenu(label="All Categories", get_content=bkt.Callback(get_content_categories))
]

