# -*- coding: utf-8 -*-

# https://docs.microsoft.com/de-de/windows/uwp/design/style/segoe-ui-symbol-font



from math import ceil

import bkt
from bkt.library.powerpoint import PPTSymbolsGallery


segoe_symbols = [
    ("\uE700", "Global Navigation Button"),
    ("\uE701", "Wifi"),
    ("\uE702", "Bluetooth"),
    ("\uE703", "Connect"),
    ("\uE704", "Internet Sharing"),
    ("\uE705", "VPN"),
    ("\uE706", "Brightness"),
    ("\uE707", "Map Pin"),
    ("\uE708", "Quiet Hours"),
    ("\uE709", "Airplane"),
    ("\uE70A", "Tablet"),
    ("\uE70B", "Quick Note"),
    ("\uE70C", "Remembered Device"),
    ("\uE70D", "Chevron Down"),
    ("\uE70E", "Chevron Up"),
    ("\uE70F", "Edit"),
    ("\uE710", "Add"),
    ("\uE711", "Cancel"),
    ("\uE712", "More"),
    ("\uE713", "Settings"),
    ("\uE714", "Video"),
    ("\uE715", "Mail"),
    ("\uE716", "People"),
    ("\uE717", "Phone"),
    ("\uE718", "Pin"),
    ("\uE719", "Shop"),
    ("\uE71A", "Stop"),
    ("\uE71B", "Link"),
    ("\uE71C", "Filter"),
    ("\uE71D", "All Apps"),
    ("\uE71E", "Zoom"),
    ("\uE71F", "Zoom Out"),
    ("\uE720", "Microphone"),
    ("\uE721", "Search"),
    ("\uE722", "Camera"),
    ("\uE723", "Attach"),
    ("\uE724", "Send"),
    ("\uE725", "Send Fill"),
    ("\uE726", "Walk Solid"),
    ("\uE727", "In Private"),
    ("\uE728", "Favorite List"),
    ("\uE729", "Page Solid"),
    ("\uE72A", "Forward"),
    ("\uE72B", "Back"),
    ("\uE72C", "Refresh"),
    ("\uE72D", "Share"),
    ("\uE72E", "Lock"),
    ("\uE730", "Report Hacked"),
    ("\uE731", "EMI"),
    ("\uE734", "Favorite Star"),
    ("\uE735", "Favorite Star Fill"),
    ("\uE736", "Reading Mode"),
    ("\uE737", "Favicon"),
    ("\uE738", "Remove"),
    ("\uE739", "Checkbox"),
    ("\uE73A", "Checkbox Composite"),
    ("\uE73B", "Checkbox Fill"),
    ("\uE73C", "Checkbox Indeterminate"),
    ("\uE73D", "Checkbox Composite Reversed"),
    ("\uE73E", "Check Mark"),
    ("\uE73F", "Back To Window"),
    ("\uE740", "Full Screen"),
    ("\uE741", "Resize Touch Larger"),
    ("\uE742", "Resize Touch Smaller"),
    ("\uE743", "Resize Mouse Small"),
    ("\uE744", "Resize Mouse Medium"),
    ("\uE745", "Resize Mouse Wide"),
    ("\uE746", "Resize Mouse Tall"),
    ("\uE747", "Resize Mouse Large"),
    ("\uE748", "Switch User"),
    ("\uE749", "Print"),
    ("\uE74A", "Up"),
    ("\uE74B", "Down"),
    ("\uE74C", "OEM"),
    ("\uE74D", "Delete"),
    ("\uE74E", "Save"),
    ("\uE74F", "Mute"),
    ("\uE750", "Back Space QWERTY"),
    ("\uE751", "Return Key"),
    ("\uE752", "Up Arrow Shift Key"),
    ("\uE753", "Cloud"),
    ("\uE754", "Flashlight"),
    ("\uE755", "Rotation Lock"),
    ("\uE756", "Command Prompt"),
    ("\uE759", "SIPMove"),
    ("\uE75A", "SIPUndock"),
    ("\uE75B", "SIPRedock"),
    ("\uE75C", "Erase Tool"),
    ("\uE75D", "Underscore Space"),
    ("\uE75E", "Gripper Tool"),
    ("\uE75F", "Dialpad"),
    ("\uE760", "Page Left"),
    ("\uE761", "Page Right"),
    ("\uE762", "Multi Select"),
    ("\uE763", "Keyboard Left Handed"),
    ("\uE764", "Keyboard Right Handed"),
    ("\uE765", "Keyboard Classic"),
    ("\uE766", "Keyboard Split"),
    ("\uE767", "Volume"),
    ("\uE768", "Play"),
    ("\uE769", "Pause"),
    ("\uE76B", "Chevron Left"),
    ("\uE76C", "Chevron Right"),
    ("\uE76D", "Inking Tool"),
    ("\uE76E", "Emoji 2"),
    ("\uE76F", "Gripper Bar Horizontal"),
    ("\uE770", "System"),
    ("\uE771", "Personalize"),
    ("\uE772", "Devices"),
    ("\uE773", "Search And Apps"),
    ("\uE774", "Globe"),
    ("\uE775", "Time Language"),
    ("\uE776", "Ease Of Access"),
    ("\uE777", "Update Restore"),
    ("\uE778", "Hang Up"),
    ("\uE779", "Contact Info"),
    ("\uE77A", "Unpin"),
    ("\uE77B", "Contact"),
    ("\uE77C", "Memo"),
    ("\uE77E", "Incoming Call"),
    ("\uE77F", "Paste"),
    ("\uE780", "Phone Book"),
    ("\uE781", "LEDLight"),
    ("\uE783", "Error"),
    ("\uE784", "Gripper Bar Vertical"),
    ("\uE785", "Unlock"),
    ("\uE786", "Slideshow"),
    ("\uE787", "Calendar"),
    ("\uE788", "Gripper Resize"),
    ("\uE789", "Megaphone"),
    ("\uE78A", "Trim"),
    ("\uE78B", "New Window"),
    ("\uE78C", "Save Local"),
    ("\uE790", "Color"),
    ("\uE791", "Data Sense"),
    ("\uE792", "Save As"),
    ("\uE793", "Light"),
    ("\uE799", "Aspect Ratio"),
    ("\uE7A5", "Data Sense Bar"),
    ("\uE7A6", "Redo"),
    ("\uE7A7", "Undo"),
    ("\uE7A8", "Crop"),
    ("\uE7AC", "Open With"),
    ("\uE7AD", "Rotate"),
    ("\uE7B3", "Red Eye"),
    ("\uE7B5", "Setlock Screen"),
    ("\uE7B7", "Map Pin  2"),
    ("\uE7B8", "Package"),
    ("\uE7BA", "Warning"),
    ("\uE7BC", "Reading List"),
    ("\uE7BE", "Education"),
    ("\uE7BF", "Shopping Cart"),
    ("\uE7C0", "Train"),
    ("\uE7C1", "Flag"),
    ("\uE7C3", "Page"),
    ("\uE7C4", "Task View"),
    ("\uE7C5", "Browse Photos"),
    ("\uE7C6", "Half Star Left"),
    ("\uE7C7", "Half Star Right"),
    ("\uE7C8", "Record"),
    ("\uE7C9", "Touch Pointer"),
    ("\uE7DE", "Lang JPN"),
    ("\uE7E3", "Ferry"),
    ("\uE7E6", "Highlight"),
    ("\uE7E7", "Action Center Notification"),
    ("\uE7E8", "Power Button"),
    ("\uE7EA", "Resize Touch Narrower"),
    ("\uE7EB", "Resize Touch Shorter"),
    ("\uE7EC", "Driving Mode"),
    ("\uE7ED", "Ringer Silent"),
    ("\uE7EE", "Other User"),
    ("\uE7EF", "Admin"),
    ("\uE7F0", "CC"),
    ("\uE7F1", "SDCard"),
    ("\uE7F2", "Call Forwarding"),
    ("\uE7F3", "Settings Display Sound"),
    ("\uE7F4", "TVMonitor"),
    ("\uE7F5", "Speakers"),
    ("\uE7F6", "Headphone"),
    ("\uE7F7", "Device Laptop Pic"),
    ("\uE7F8", "Device Laptop No Pic"),
    ("\uE7F9", "Device Monitor Right Pic"),
    ("\uE7FA", "Device Monitor Left Pic"),
    ("\uE7FB", "Device Monitor No Pic"),
    ("\uE7FC", "Game"),
    ("\uE7FD", "Horizontal Tab Key"),
    ("\uE802", "Streetside Split Minimize"),
    ("\uE803", "Streetside Split Expand"),
    ("\uE804", "Car"),
    ("\uE805", "Walk"),
    ("\uE806", "Bus"),
    ("\uE809", "Tilt Up"),
    ("\uE80A", "Tilt Down"),
    ("\uE80B", "Call Control"),
    ("\uE80C", "Rotate Map Right"),
    ("\uE80D", "Rotate Map Left"),
    ("\uE80F", "Home"),
    ("\uE811", "Parking Location"),
    ("\uE812", "Map Compass Top"),
    ("\uE813", "Map Compass Bottom"),
    ("\uE814", "Incident Triangle"),
    ("\uE815", "Touch"),
    ("\uE816", "Map Directions"),
    ("\uE819", "Start Point"),
    ("\uE81A", "Stop Point"),
    ("\uE81B", "End Point"),
    ("\uE81C", "History"),
    ("\uE81D", "Location"),
    ("\uE81E", "Map Layers"),
    ("\uE81F", "Accident"),
    ("\uE821", "Work"),
    ("\uE822", "Construction"),
    ("\uE823", "Recent"),
    ("\uE825", "Bank"),
    ("\uE826", "Download Map"),
    ("\uE829", "Inking Tool Fill  2"),
    ("\uE82A", "Highlight Fill  2"),
    ("\uE82B", "Erase Tool Fill"),
    ("\uE82C", "Erase Tool Fill 2"),
    ("\uE82D", "Dictionary"),
    ("\uE82E", "Dictionary Add"),
    ("\uE82F", "Tool Tip"),
    ("\uE830", "Chrome Back"),
    ("\uE835", "Provisioning Package"),
    ("\uE836", "Add Remote Device"),
    ("\uE838", "Folder Open"),
    ("\uE839", "Ethernet"),
    ("\uE83A", "Share Broadband"),
    ("\uE83B", "Direct Access"),
    ("\uE83C", "Dial Up"),
    ("\uE83D", "Defender App"),
    ("\uE83E", "Battery Charging 9"),
    ("\uE83F", "Battery 10"),
    ("\uE840", "Pinned"),
    ("\uE841", "Pin Fill"),
    ("\uE842", "Pinned Fill"),
    ("\uE843", "Period Key"),
    ("\uE844", "Punc Key"),
    ("\uE845", "Rev Toggle Key"),
    ("\uE846", "Right Arrow Key Time 1"),
    ("\uE847", "Right Arrow Key Time 2"),
    ("\uE848", "Left Quote"),
    ("\uE849", "Right Quote"),
    ("\uE84A", "Down Shift Key"),
    ("\uE84B", "Up Shift Key"),
    ("\uE84C", "Punc Key 0"),
    ("\uE84D", "Punc Key Left Bottom"),
    ("\uE84E", "Right Arrow Key Time 3"),
    ("\uE84F", "Right Arrow Key Time 4"),
    ("\uE850", "Battery 0"),
    ("\uE851", "Battery 1"),
    ("\uE852", "Battery 2"),
    ("\uE853", "Battery 3"),
    ("\uE854", "Battery 4"),
    ("\uE855", "Battery 5"),
    ("\uE856", "Battery 6"),
    ("\uE857", "Battery 7"),
    ("\uE858", "Battery 8"),
    ("\uE859", "Battery 9"),
    ("\uE85A", "Battery Charging 0"),
    ("\uE85B", "Battery Charging 1"),
    ("\uE85C", "Battery Charging 2"),
    ("\uE85D", "Battery Charging 3"),
    ("\uE85E", "Battery Charging 4"),
    ("\uE85F", "Battery Charging 5"),
    ("\uE860", "Battery Charging 6"),
    ("\uE861", "Battery Charging 7"),
    ("\uE862", "Battery Charging 8"),
    ("\uE863", "Battery Saver 0"),
    ("\uE864", "Battery Saver 1"),
    ("\uE865", "Battery Saver 2"),
    ("\uE866", "Battery Saver 3"),
    ("\uE867", "Battery Saver 4"),
    ("\uE868", "Battery Saver 5"),
    ("\uE869", "Battery Saver 6"),
    ("\uE86A", "Battery Saver 7"),
    ("\uE86B", "Battery Saver 8"),
    ("\uE86C", "Signal Bars 1"),
    ("\uE86D", "Signal Bars 2"),
    ("\uE86E", "Signal Bars 3"),
    ("\uE86F", "Signal Bars 4"),
    ("\uE870", "Signal Bars 5"),
    ("\uE871", "Signal Not Connected"),
    ("\uE872", "Wifi 1"),
    ("\uE873", "Wifi 2"),
    ("\uE874", "Wifi 3"),
    ("\uE875", "Mob SIMLock"),
    ("\uE876", "Mob SIMMissing"),
    ("\uE877", "Vibrate"),
    ("\uE878", "Roaming International"),
    ("\uE879", "Roaming Domestic"),
    ("\uE87A", "Call Forward International"),
    ("\uE87B", "Call Forward Roaming"),
    ("\uE87C", "Jpn Romanji"),
    ("\uE87D", "Jpn Romanji Lock"),
    ("\uE87E", "Jpn Romanji Shift"),
    ("\uE87F", "Jpn Romanji Shift Lock"),
    ("\uE880", "Status Data Transfer"),
    ("\uE881", "Status Data Transfer VPN"),
    ("\uE882", "Status Dual SIM 2"),
    ("\uE883", "Status Dual SIM2VPN"),
    ("\uE884", "Status Dual SIM 1"),
    ("\uE885", "Status Dual SIM1VPN"),
    ("\uE886", "Status SGLTE"),
    ("\uE887", "Status SGLTECell"),
    ("\uE888", "Status SGLTEData VPN"),
    ("\uE889", "Status VPN"),
    ("\uE88A", "Wifi Hotspot"),
    ("\uE88B", "Language Kor"),
    ("\uE88C", "Language Cht"),
    ("\uE88D", "Language Chs"),
    ("\uE88E", "USB"),
    ("\uE88F", "Inking Tool Fill"),
    ("\uE890", "View"),
    ("\uE891", "Highlight Fill"),
    ("\uE892", "Previous"),
    ("\uE893", "Next"),
    ("\uE894", "Clear"),
    ("\uE895", "Sync"),
    ("\uE896", "Download"),
    ("\uE897", "Help"),
    ("\uE898", "Upload"),
    ("\uE899", "Emoji"),
    ("\uE89A", "Two Page"),
    ("\uE89B", "Leave Chat"),
    ("\uE89C", "Mail Forward"),
    ("\uE89E", "Rotate Camera"),
    ("\uE89F", "Close Pane"),
    ("\uE8A0", "Open Pane"),
    ("\uE8A1", "Preview Link"),
    ("\uE8A2", "Attach Camera"),
    ("\uE8A3", "Zoom In"),
    ("\uE8A4", "Bookmarks"),
    ("\uE8A5", "Document"),
    ("\uE8A6", "Protected Document"),
    ("\uE8A7", "Open In New Window"),
    ("\uE8A8", "Mail Fill"),
    ("\uE8A9", "View All"),
    ("\uE8AA", "Video Chat"),
    ("\uE8AB", "Switch"),
    ("\uE8AC", "Rename"),
    ("\uE8AD", "Go"),
    ("\uE8AE", "Surface Hub"),
    ("\uE8AF", "Remote"),
    ("\uE8B0", "Click"),
    ("\uE8B1", "Shuffle"),
    ("\uE8B2", "Movies"),
    ("\uE8B3", "Select All"),
    ("\uE8B4", "Orientation"),
    ("\uE8B5", "Import"),
    ("\uE8B6", "Import All"),
    ("\uE8B7", "Folder"),
    ("\uE8B8", "Webcam"),
    ("\uE8B9", "Picture"),
    ("\uE8BA", "Caption"),
    ("\uE8BB", "Chrome Close"),
    ("\uE8BC", "Show Results"),
    ("\uE8BD", "Message"),
    ("\uE8BE", "Leaf"),
    ("\uE8BF", "Calendar Day"),
    ("\uE8C0", "Calendar Week"),
    ("\uE8C1", "Characters"),
    ("\uE8C2", "Mail Reply All"),
    ("\uE8C3", "Read"),
    ("\uE8C4", "Show Bcc"),
    ("\uE8C5", "Hide Bcc"),
    ("\uE8C6", "Cut"),
    ("\uE8C7", "Payment Card"),
    ("\uE8C8", "Copy"),
    ("\uE8C9", "Important"),
    ("\uE8CA", "Mail Reply"),
    ("\uE8CB", "Sort"),
    ("\uE8CC", "Mobile Tablet"),
    ("\uE8CD", "Disconnect Drive"),
    ("\uE8CE", "Map Drive"),
    ("\uE8CF", "Contact Presence"),
    ("\uE8D0", "Priority"),
    ("\uE8D1", "Goto Today"),
    ("\uE8D2", "Font"),
    ("\uE8D3", "Font Color"),
    ("\uE8D4", "Contact 2"),
    ("\uE8D5", "Folder Fill"),
    ("\uE8D6", "Audio"),
    ("\uE8D7", "Permissions"),
    ("\uE8D8", "Disable Updates"),
    ("\uE8D9", "Unfavorite"),
    ("\uE8DA", "Open Local"),
    ("\uE8DB", "Italic"),
    ("\uE8DC", "Underline"),
    ("\uE8DD", "Bold"),
    ("\uE8DE", "Move To Folder"),
    ("\uE8DF", "Like Dislike"),
    ("\uE8E0", "Dislike"),
    ("\uE8E1", "Like"),
    ("\uE8E2", "Align Right"),
    ("\uE8E3", "Align Center"),
    ("\uE8E4", "Align Left"),
    ("\uE8E5", "Open File"),
    ("\uE8E6", "Clear Selection"),
    ("\uE8E7", "Font Decrease"),
    ("\uE8E8", "Font Increase"),
    ("\uE8E9", "Font Size"),
    ("\uE8EA", "Cell Phone"),
    ("\uE8EB", "Reshare"),
    ("\uE8EC", "Tag"),
    ("\uE8ED", "Repeat One"),
    ("\uE8EE", "Repeat All"),
    ("\uE8EF", "Calculator"),
    ("\uE8F0", "Directions"),
    ("\uE8F1", "Library"),
    ("\uE8F2", "Chat Bubbles"),
    ("\uE8F3", "Post Update"),
    ("\uE8F4", "New Folder"),
    ("\uE8F5", "Calendar Reply"),
    ("\uE8F6", "Unsync Folder"),
    ("\uE8F7", "Sync Folder"),
    ("\uE8F8", "Block Contact"),
    ("\uE8F9", "Switch Apps"),
    ("\uE8FA", "Add Friend"),
    ("\uE8FB", "Accept"),
    ("\uE8FC", "Go To Start"),
    ("\uE8FD", "Bulleted List"),
    ("\uE8FE", "Scan"),
    ("\uE8FF", "Preview"),
    ("\uE902", "Group"),
    ("\uE904", "Zero Bars"),
    ("\uE905", "One Bar"),
    ("\uE906", "Two Bars"),
    ("\uE907", "Three Bars"),
    ("\uE908", "Four Bars"),
    ("\uE909", "World"),
    ("\uE90A", "Comment"),
    ("\uE90B", "Music Info"),
    ("\uE90C", "Dock Left"),
    ("\uE90D", "Dock Right"),
    ("\uE90E", "Dock Bottom"),
    ("\uE90F", "Repair"),
    ("\uE910", "Accounts"),
    ("\uE911", "Dull Sound"),
    ("\uE912", "Manage"),
    ("\uE913", "Street"),
    ("\uE914", "Printer3D"),
    ("\uE915", "Radio Bullet"),
    ("\uE916", "Stopwatch"),
    ("\uE91B", "Photo"),
    ("\uE91C", "Action Center"),
    ("\uE91F", "Full Circle Mask"),
    ("\uE921", "Chrome Minimize"),
    ("\uE922", "Chrome Maximize"),
    ("\uE923", "Chrome Restore"),
    ("\uE924", "Annotation"),
    ("\uE925", "Back Space QWERTYSm"),
    ("\uE926", "Back Space QWERTYMd"),
    ("\uE927", "Swipe"),
    ("\uE928", "Fingerprint"),
    ("\uE929", "Handwriting"),
    ("\uE92C", "Chrome Back To Window"),
    ("\uE92D", "Chrome Full Screen"),
    ("\uE92E", "Keyboard Standard"),
    ("\uE92F", "Keyboard Dismiss"),
    ("\uE930", "Completed"),
    ("\uE931", "Chrome Annotate"),
    ("\uE932", "Label"),
    ("\uE933", "IBeam"),
    ("\uE934", "IBeam Outline"),
    ("\uE935", "Flick Down"),
    ("\uE936", "Flick Up"),
    ("\uE937", "Flick Left"),
    ("\uE938", "Flick Right"),
    ("\uE939", "Feedback App"),
    ("\uE93C", "Music Album"),
    ("\uE93E", "Streaming"),
    ("\uE943", "Code"),
    ("\uE944", "Return To Window"),
    ("\uE945", "Lightning Bolt"),
    ("\uE946", "Info"),
    ("\uE947", "Calculator Multiply"),
    ("\uE948", "Calculator Addition"),
    ("\uE949", "Calculator Subtract"),
    ("\uE94A", "Calculator Divide"),
    ("\uE94B", "Calculator Squareroot"),
    ("\uE94C", "Calculator Percentage"),
    ("\uE94D", "Calculator Negate"),
    ("\uE94E", "Calculator Equal To"),
    ("\uE94F", "Calculator Backspace"),
    ("\uE950", "Component"),
    ("\uE951", "DMC"),
    ("\uE952", "Dock"),
    ("\uE953", "Multimedia DMS"),
    ("\uE954", "Multimedia DVR"),
    ("\uE955", "Multimedia PMP"),
    ("\uE956", "Printfax Printer File"),
    ("\uE957", "Sensor"),
    ("\uE958", "Storage Optical"),
    ("\uE95A", "Communications"),
    ("\uE95B", "Headset"),
    ("\uE95D", "Projector"),
    ("\uE95E", "Health"),
    ("\uE95F", "Wire"),
    ("\uE960", "Webcam 2"),
    ("\uE961", "Input"),
    ("\uE962", "Mouse"),
    ("\uE963", "Smartcard"),
    ("\uE964", "Smartcard Virtual"),
    ("\uE965", "Media Storage Tower"),
    ("\uE966", "Return Key Sm"),
    ("\uE967", "Game Console"),
    ("\uE968", "Network"),
    ("\uE969", "Storage Network Wireless"),
    ("\uE96A", "Storage Tape"),
    ("\uE96D", "Chevron Up Small"),
    ("\uE96E", "Chevron Down Small"),
    ("\uE96F", "Chevron Left Small"),
    ("\uE970", "Chevron Right Small"),
    ("\uE971", "Chevron Up Med"),
    ("\uE972", "Chevron Down Med"),
    ("\uE973", "Chevron Left Med"),
    ("\uE974", "Chevron Right Med"),
    ("\uE975", "Devices 2"),
    ("\uE976", "Expand Tile"),
    ("\uE977", "PC 1"),
    ("\uE978", "Presence Chicklet"),
    ("\uE979", "Presence Chicklet Video"),
    ("\uE97A", "Reply"),
    ("\uE97B", "Set Tile"),
    ("\uE97C", "Type"),
    ("\uE97D", "Korean"),
    ("\uE97E", "Half Alpha"),
    ("\uE97F", "Full Alpha"),
    ("\uE980", "Key12On"),
    ("\uE981", "Chinese Changjie"),
    ("\uE982", "QWERTYOn"),
    ("\uE983", "QWERTYOff"),
    ("\uE984", "Chinese Quick"),
    ("\uE985", "Japanese"),
    ("\uE986", "Full Hiragana"),
    ("\uE987", "Full Katakana"),
    ("\uE988", "Half Katakana"),
    ("\uE989", "Chinese Bo Po Mo Fo"),
    ("\uE98A", "Chinese Pinyin"),
    ("\uE98F", "Construction Cone"),
    ("\uE990", "Xbox One Console"),
    ("\uE992", "Volume 0"),
    ("\uE993", "Volume 1"),
    ("\uE994", "Volume 2"),
    ("\uE995", "Volume 3"),
    ("\uE996", "Battery Unknown"),
    ("\uE998", "Wifi Attention Overlay"),
    ("\uE99A", "Robot"),
    ("\uE9A1", "Tap And Send"),
    ("\uE9A6", "Fit Page"),
    ("\uE9A8", "Password Key Show"),
    ("\uE9A9", "Password Key Hide"),
    ("\uE9AA", "Bidi Ltr"),
    ("\uE9AB", "Bidi Rtl"),
    ("\uE9AC", "Forward Sm"),
    ("\uE9AD", "Comma Key"),
    ("\uE9AE", "Dash Key"),
    ("\uE9AF", "Dull Sound Key"),
    ("\uE9B0", "Half Dull Sound"),
    ("\uE9B1", "Right Double Quote"),
    ("\uE9B2", "Left Double Quote"),
    ("\uE9B3", "Punc Key Right Bottom"),
    ("\uE9B4", "Punc Key 1"),
    ("\uE9B5", "Punc Key 2"),
    ("\uE9B6", "Punc Key 3"),
    ("\uE9B7", "Punc Key 4"),
    ("\uE9B8", "Punc Key 5"),
    ("\uE9B9", "Punc Key 6"),
    ("\uE9BA", "Punc Key 9"),
    ("\uE9BB", "Punc Key 7"),
    ("\uE9BC", "Punc Key 8"),
    ("\uE9CA", "Frigid"),
    ("\uE9CE", "Unknown"),
    ("\uE9D2", "Area Chart"),
    ("\uE9D5", "Check List"),
    ("\uE9D9", "Diagnostic"),
    ("\uE9E9", "Equalizer"),
    ("\uE9F3", "Process"),
    ("\uE9F5", "Processing"),
    ("\uE9F9", "Report Document"),
    ("\uEA0C", "Video Solid"),
    ("\uEA0D", "Mixed Media Badge"),
    ("\uEA14", "Disconnect Display"),
    ("\uEA18", "Shield"),
    ("\uEA1F", "Info 2"),
    ("\uEA21", "Action Center Asterisk"),
    ("\uEA24", "Beta"),
    ("\uEA35", "Save Copy"),
    ("\uEA37", "List"),
    ("\uEA38", "Asterisk"),
    ("\uEA39", "Error Badge"),
    ("\uEA3A", "Circle Ring"),
    ("\uEA3B", "Circle Fill"),
    ("\uEA3C", "Merge Call"),
    ("\uEA3D", "Private Call"),
    ("\uEA3F", "Record 2"),
    ("\uEA40", "All Apps Mirrored"),
    ("\uEA41", "Bookmarks Mirrored"),
    ("\uEA42", "Bulleted List Mirrored"),
    ("\uEA43", "Call Forward International Mirrored"),
    ("\uEA44", "Call Forward Roaming Mirrored"),
    ("\uEA47", "Chrome Back Mirrored"),
    ("\uEA48", "Clear Selection Mirrored"),
    ("\uEA49", "Close Pane Mirrored"),
    ("\uEA4A", "Contact Info Mirrored"),
    ("\uEA4B", "Dock Right Mirrored"),
    ("\uEA4C", "Dock Left Mirrored"),
    ("\uEA4E", "Expand Tile Mirrored"),
    ("\uEA4F", "Go Mirrored"),
    ("\uEA50", "Gripper Resize Mirrored"),
    ("\uEA51", "Help Mirrored"),
    ("\uEA52", "Import Mirrored"),
    ("\uEA53", "Import All Mirrored"),
    ("\uEA54", "Leave Chat Mirrored"),
    ("\uEA55", "List Mirrored"),
    ("\uEA56", "Mail Forward Mirrored"),
    ("\uEA57", "Mail Reply Mirrored"),
    ("\uEA58", "Mail Reply All Mirrored"),
    ("\uEA5B", "Open Pane Mirrored"),
    ("\uEA5C", "Open With Mirrored"),
    ("\uEA5E", "Parking Location Mirrored"),
    ("\uEA5F", "Resize Mouse Medium Mirrored"),
    ("\uEA60", "Resize Mouse Small Mirrored"),
    ("\uEA61", "Resize Mouse Tall Mirrored"),
    ("\uEA62", "Resize Touch Narrower Mirrored"),
    ("\uEA63", "Send Mirrored"),
    ("\uEA64", "Send Fill Mirrored"),
    ("\uEA65", "Show Results Mirrored"),
    ("\uEA69", "Media"),
    ("\uEA6A", "Sync Error"),
    ("\uEA6C", "Devices 3"),
    ("\uEA79", "Slow Motion On"),
    ("\uEA80", "Lightbulb"),
    ("\uEA81", "Status Circle"),
    ("\uEA82", "Status Triangle"),
    ("\uEA83", "Status Error"),
    ("\uEA84", "Status Warning"),
    ("\uEA86", "Puzzle"),
    ("\uEA89", "Calendar Solid"),
    ("\uEA8A", "Home Solid"),
    ("\uEA8B", "Parking Location Solid"),
    ("\uEA8C", "Contact Solid"),
    ("\uEA8D", "Construction Solid"),
    ("\uEA8E", "Accident Solid"),
    ("\uEA8F", "Ringer"),
    ("\uEA90", "PDF"),
    ("\uEA91", "Thought Bubble"),
    ("\uEA92", "Heart Broken"),
    ("\uEA93", "Battery Charging 10"),
    ("\uEA94", "Battery Saver 9"),
    ("\uEA95", "Battery Saver 10"),
    ("\uEA97", "Call Forwarding Mirrored"),
    ("\uEA98", "Multi Select Mirrored"),
    ("\uEA99", "Broom"),
    ("\uEAC2", "Forward Call"),
    ("\uEADF", "Trackers"),
    ("\uEAFC", "Market"),
    ("\uEB05", "Pie Single"),
    ("\uEB0F", "Stock Down"),
    ("\uEB11", "Stock Up"),
    ("\uEB3C", "Design"),
    ("\uEB41", "Website"),
    ("\uEB42", "Drop"),
    ("\uEB44", "Radar"),
    ("\uEB47", "Bus Solid"),
    ("\uEB48", "Ferry Solid"),
    ("\uEB49", "Start Point Solid"),
    ("\uEB4A", "Stop Point Solid"),
    ("\uEB4B", "End Point Solid"),
    ("\uEB4C", "Airplane Solid"),
    ("\uEB4D", "Train Solid"),
    ("\uEB4E", "Work Solid"),
    ("\uEB4F", "Reminder Fill"),
    ("\uEB50", "Reminder"),
    ("\uEB51", "Heart"),
    ("\uEB52", "Heart Fill"),
    ("\uEB55", "Ethernet Error"),
    ("\uEB56", "Ethernet Warning"),
    ("\uEB57", "Status Connecting 1"),
    ("\uEB58", "Status Connecting 2"),
    ("\uEB59", "Status Unsecure"),
    ("\uEB5A", "Wifi Error 0"),
    ("\uEB5B", "Wifi Error 1"),
    ("\uEB5C", "Wifi Error 2"),
    ("\uEB5D", "Wifi Error 3"),
    ("\uEB5E", "Wifi Error 4"),
    ("\uEB5F", "Wifi Warning 0"),
    ("\uEB60", "Wifi Warning 1"),
    ("\uEB61", "Wifi Warning 2"),
    ("\uEB62", "Wifi Warning 3"),
    ("\uEB63", "Wifi Warning 4"),
    ("\uEB66", "Devices 4"),
    ("\uEB67", "NUIIris"),
    ("\uEB68", "NUIFace"),
    ("\uEB7E", "Edit Mirrored"),
    ("\uEB82", "NUIFPStart Slide Hand"),
    ("\uEB83", "NUIFPStart Slide Action"),
    ("\uEB84", "NUIFPContinue Slide Hand"),
    ("\uEB85", "NUIFPContinue Slide Action"),
    ("\uEB86", "NUIFPRoll Right Hand"),
    ("\uEB87", "NUIFPRoll Right Hand Action"),
    ("\uEB88", "NUIFPRoll Left Hand"),
    ("\uEB89", "NUIFPRoll Left Action"),
    ("\uEB8A", "NUIFPPress Hand"),
    ("\uEB8B", "NUIFPPress Action"),
    ("\uEB8C", "NUIFPPress Repeat Hand"),
    ("\uEB8D", "NUIFPPress Repeat Action"),
    ("\uEB90", "Status Error Full"),
    ("\uEB91", "Task View Expanded"),
    ("\uEB95", "Certificate"),
    ("\uEB96", "Back Space QWERTYLg"),
    ("\uEB97", "Return Key Lg"),
    ("\uEB9D", "Fast Forward"),
    ("\uEB9E", "Rewind"),
    ("\uEB9F", "Photo 2"),
    ("\uEBA0", "Mob Battery 0"),
    ("\uEBA1", "Mob Battery 1"),
    ("\uEBA2", "Mob Battery 2"),
    ("\uEBA3", "Mob Battery 3"),
    ("\uEBA4", "Mob Battery 4"),
    ("\uEBA5", "Mob Battery 5"),
    ("\uEBA6", "Mob Battery 6"),
    ("\uEBA7", "Mob Battery 7"),
    ("\uEBA8", "Mob Battery 8"),
    ("\uEBA9", "Mob Battery 9"),
    ("\uEBAA", "Mob Battery 10"),
    ("\uEBAB", "Mob Battery Charging 0"),
    ("\uEBAC", "Mob Battery Charging 1"),
    ("\uEBAD", "Mob Battery Charging 2"),
    ("\uEBAE", "Mob Battery Charging 3"),
    ("\uEBAF", "Mob Battery Charging 4"),
    ("\uEBB0", "Mob Battery Charging 5"),
    ("\uEBB1", "Mob Battery Charging 6"),
    ("\uEBB2", "Mob Battery Charging 7"),
    ("\uEBB3", "Mob Battery Charging 8"),
    ("\uEBB4", "Mob Battery Charging 9"),
    ("\uEBB5", "Mob Battery Charging 10"),
    ("\uEBB6", "Mob Battery Saver 0"),
    ("\uEBB7", "Mob Battery Saver 1"),
    ("\uEBB8", "Mob Battery Saver 2"),
    ("\uEBB9", "Mob Battery Saver 3"),
    ("\uEBBA", "Mob Battery Saver 4"),
    ("\uEBBB", "Mob Battery Saver 5"),
    ("\uEBBC", "Mob Battery Saver 6"),
    ("\uEBBD", "Mob Battery Saver 7"),
    ("\uEBBE", "Mob Battery Saver 8"),
    ("\uEBBF", "Mob Battery Saver 9"),
    ("\uEBC0", "Mob Battery Saver 10"),
    ("\uEBC3", "Dictionary Cloud"),
    ("\uEBC4", "Reset Drive"),
    ("\uEBC5", "Volume Bars"),
    ("\uEBC6", "Project"),
    ("\uEBD2", "Adjust Hologram"),
    ("\uEBD4", "Wifi Call Bars"),
    ("\uEBD5", "Wifi Call 0"),
    ("\uEBD6", "Wifi Call 1"),
    ("\uEBD7", "Wifi Call 2"),
    ("\uEBD8", "Wifi Call 3"),
    ("\uEBD9", "Wifi Call 4"),
    ("\uEBDA", "Family"),
    ("\uEBDB", "Lock Feedback"),
    ("\uEBDE", "Device Discovery"),
    ("\uEBE6", "Wind Direction"),
    ("\uEBE7", "Right Arrow Key Time 0"),
    ("\uEBE8", "Bug"),
    ("\uEBFC", "Tablet Mode"),
    ("\uEBFD", "Status Circle Left"),
    ("\uEBFE", "Status Triangle Left"),
    ("\uEBFF", "Status Error Left"),
    ("\uEC00", "Status Warning Left"),
    ("\uEC02", "Mob Battery Unknown"),
    ("\uEC05", "Network Tower"),
    ("\uEC06", "City Next"),
    ("\uEC07", "City Next 2"),
    ("\uEC08", "Courthouse"),
    ("\uEC09", "Groceries"),
    ("\uEC0A", "Sustainable"),
    ("\uEC0B", "Building Energy"),
    ("\uEC11", "Toggle Filled"),
    ("\uEC12", "Toggle Border"),
    ("\uEC13", "Slider Thumb"),
    ("\uEC14", "Toggle Thumb"),
    ("\uEC15", "Miracast Logo Small"),
    ("\uEC16", "Miracast Logo Large"),
    ("\uEC19", "PLAP"),
    ("\uEC1B", "Badge"),
    ("\uEC1E", "Signal Roaming"),
    ("\uEC20", "Mobile Locked"),
    ("\uEC24", "Insider Hub App"),
    ("\uEC25", "Personal Folder"),
    ("\uEC26", "Home Group"),
    ("\uEC27", "My Network"),
    ("\uEC31", "Keyboard Full"),
    ("\uEC32", "Cafe"),
    ("\uEC37", "Mob Signal 1"),
    ("\uEC38", "Mob Signal 2"),
    ("\uEC39", "Mob Signal 3"),
    ("\uEC3A", "Mob Signal 4"),
    ("\uEC3B", "Mob Signal 5"),
    ("\uEC3C", "Mob Wifi 1"),
    ("\uEC3D", "Mob Wifi 2"),
    ("\uEC3E", "Mob Wifi 3"),
    ("\uEC3F", "Mob Wifi 4"),
    ("\uEC40", "Mob Airplane"),
    ("\uEC41", "Mob Bluetooth"),
    ("\uEC42", "Mob Action Center"),
    ("\uEC43", "Mob Location"),
    ("\uEC44", "Mob Wifi Hotspot"),
    ("\uEC45", "Language Jpn"),
    ("\uEC46", "Mob Quiet Hours"),
    ("\uEC47", "Mob Driving Mode"),
    ("\uEC48", "Speed Off"),
    ("\uEC49", "Speed Medium"),
    ("\uEC4A", "Speed High"),
    ("\uEC4E", "This PC"),
    ("\uEC4F", "Music Note"),
    ("\uEC50", "File Explorer"),
    ("\uEC51", "File Explorer App"),
    ("\uEC52", "Left Arrow Key Time 0"),
    ("\uEC54", "Mic Off"),
    ("\uEC55", "Mic Sleep"),
    ("\uEC56", "Mic Error"),
    ("\uEC57", "Playback Rate1x"),
    ("\uEC58", "Playback Rate Other"),
    ("\uEC59", "Cash Drawer"),
    ("\uEC5A", "Barcode Scanner"),
    ("\uEC5B", "Receipt Printer"),
    ("\uEC5C", "Mag Stripe Reader"),
    ("\uEC61", "Completed Solid"),
    ("\uEC64", "Companion App"),
    ("\uEC6C", "Favicon 2"),
    ("\uEC6D", "Swipe Reveal Art"),
    ("\uEC71", "Mic On"),
    ("\uEC72", "Mic Clipping"),
    ("\uEC74", "Tablet Selected"),
    ("\uEC75", "Mobile Selected"),
    ("\uEC76", "Laptop Selected"),
    ("\uEC77", "TVMonitor Selected"),
    ("\uEC7A", "Developer Tools"),
    ("\uEC7E", "Mob Call Forwarding"),
    ("\uEC7F", "Mob Call Forwarding Mirrored"),
    ("\uEC80", "Body Cam"),
    ("\uEC81", "Police Car"),
    ("\uEC87", "Draw"),
    ("\uEC88", "Draw Solid"),
    ("\uEC8A", "Lower Brightness"),
    ("\uEC8F", "Scroll Up Down"),
    ("\uEC92", "Date Time"),
    ("\uECA5", "Tiles"),
    ("\uECA7", "Party Leader"),
    ("\uECAA", "App Icon Default"),
    ("\uECAD", "Calories"),
    ("\uECB9", "Band Battery 0"),
    ("\uECBA", "Band Battery 1"),
    ("\uECBB", "Band Battery 2"),
    ("\uECBC", "Band Battery 3"),
    ("\uECBD", "Band Battery 4"),
    ("\uECBE", "Band Battery 5"),
    ("\uECBF", "Band Battery 6"),
    ("\uECC4", "Add Surface Hub"),
    ("\uECC5", "Dev Update"),
    ("\uECC6", "Unit"),
    ("\uECC8", "Add To"),
    ("\uECC9", "Remove From"),
    ("\uECCA", "Radio Btn Off"),
    ("\uECCB", "Radio Btn On"),
    ("\uECCC", "Radio Bullet 2"),
    ("\uECCD", "Explore Content"),
    ("\uECE4", "Blocked 2"),
    ("\uECE7", "Scroll Mode"),
    ("\uECE8", "Zoom Mode"),
    ("\uECE9", "Pan Mode"),
    ("\uECF0", "Wired USB"),
    ("\uECF1", "Wireless USB"),
    ("\uECF3", "USBSafe Connect"),
    ("\uED0C", "Action Center Notification Mirrored"),
    ("\uED0D", "Action Center Mirrored"),
    ("\uED0E", "Subscription Add"),
    ("\uED10", "Reset Device"),
    ("\uED11", "Subscription Add Mirrored"),
    ("\uED14", "QRCode"),
    ("\uED15", "Feedback"),
    ("\uED1E", "Subtitles"),
    ("\uED1F", "Subtitles Audio"),
    ("\uED25", "Open Folder Horizontal"),
    ("\uED28", "Calendar Mirrored"),
    ("\uED2A", "Mobe SIM"),
    ("\uED2B", "Mobe SIMNo Profile"),
    ("\uED2C", "Mobe SIMLocked"),
    ("\uED2D", "Mobe SIMBusy"),
    ("\uED2E", "Signal Error"),
    ("\uED2F", "Streaming Enterprise"),
    ("\uED30", "Headphone 0"),
    ("\uED31", "Headphone 1"),
    ("\uED32", "Headphone 2"),
    ("\uED33", "Headphone 3"),
    ("\uED35", "Apps"),
    ("\uED39", "Keyboard Brightness"),
    ("\uED3A", "Keyboard Lower Brightness"),
    ("\uED3C", "Skip Back 10"),
    ("\uED3D", "Skip Forward 30"),
    ("\uED41", "Tree Folder Folder"),
    ("\uED42", "Tree Folder Folder Fill"),
    ("\uED43", "Tree Folder Folder Open"),
    ("\uED44", "Tree Folder Folder Open Fill"),
    ("\uED47", "Multimedia DMP"),
    ("\uED4C", "Keyboard One Handed"),
    ("\uED4D", "Narrator"),
    ("\uED53", "Emoji Tab People"),
    ("\uED54", "Emoji Tab Smiles Animals"),
    ("\uED55", "Emoji Tab Celebration Objects"),
    ("\uED56", "Emoji Tab Food Plants"),
    ("\uED57", "Emoji Tab Transit Places"),
    ("\uED58", "Emoji Tab Symbols"),
    ("\uED59", "Emoji Tab Text Smiles"),
    ("\uED5A", "Emoji Tab Favorites"),
    ("\uED5B", "Emoji Swatch"),
    ("\uED5C", "Connect App"),
    ("\uED5D", "Companion Device Framework"),
    ("\uED5E", "Ruler"),
    ("\uED5F", "Finger Inking"),
    ("\uED60", "Stroke Erase"),
    ("\uED61", "Point Erase"),
    ("\uED62", "Clear All Ink"),
    ("\uED63", "Pencil"),
    ("\uED64", "Marker"),
    ("\uED65", "Inking Caret"),
    ("\uED66", "Inking Color Outline"),
    ("\uED67", "Inking Color Fill"),
    ("\uEDA2", "Hard Drive"),
    ("\uEDA3", "Network Adapter"),
    ("\uEDA4", "Touchscreen"),
    ("\uEDA5", "Network Printer"),
    ("\uEDA6", "Cloud Printer"),
    ("\uEDA7", "Keyboard Shortcut"),
    ("\uEDA8", "Brush Size"),
    ("\uEDA9", "Narrator Forward"),
    ("\uEDAA", "Narrator Forward Mirrored"),
    ("\uEDAB", "Sync Badge 12"),
    ("\uEDAC", "Ringer Badge 12"),
    ("\uEDAD", "Asterisk Badge 12"),
    ("\uEDAE", "Error Badge 12"),
    ("\uEDAF", "Circle Ring Badge 12"),
    ("\uEDB0", "Circle Fill Badge 12"),
    ("\uEDB1", "Important Badge 12"),
    ("\uEDB3", "Mail Badge 12"),
    ("\uEDB4", "Pause Badge 12"),
    ("\uEDB5", "Play Badge 12"),
    ("\uEDC6", "Pen Workspace"),
    ("\uEDD6", "Caret Right 8"),
    ("\uEDD9", "Caret Left Solid 8"),
    ("\uEDDA", "Caret Right Solid 8"),
    ("\uEDDB", "Caret Up Solid 8"),
    ("\uEDDC", "Caret Down Solid 8"),
    ("\uEDE1", "Export"),
    ("\uEDE2", "Export Mirrored"),
    ("\uEDE3", "Button Menu"),
    ("\uEDE4", "Cloud Seach"),
    ("\uEDE5", "Pinyin IMELogo"),
    ("\uEDFB", "Calligraphy Pen"),
    ("\uEE35", "Reply Mirrored"),
    ("\uEE3F", "Lockscreen Desktop"),
    ("\uEE40", "Task View Settings"),
    ("\uEE4A", "Play 36"),
    ("\uEE56", "Pen Palette"),
    ("\uEE57", "Guest User"),
    ("\uEE63", "Settings Battery"),
    ("\uEE64", "Taskbar Phone"),
    ("\uEE65", "Lock Screen Glance"),
    ("\uEE6F", "Generic Scan"),
    ("\uEE71", "Image Export"),
    ("\uEE77", "Wifi Ethernet"),
    ("\uEE79", "Action Center Quiet"),
    ("\uEE7A", "Action Center Quiet Notification"),
    ("\uEE92", "Trackers Mirrored"),
    ("\uEE93", "Date Time Mirrored"),
    ("\uEE94", "Wheel"),
    ("\uEEA3", "Virtual Machine Group"),
    ("\uEECA", "Button View 2"),
    ("\uEF15", "Pen Workspace Mirrored"),
    ("\uEF16", "Pen Palette Mirrored"),
    ("\uEF17", "Stroke Erase Mirrored"),
    ("\uEF18", "Point Erase Mirrored"),
    ("\uEF19", "Clear All Ink Mirrored"),
    ("\uEF1F", "Background Toggle"),
    ("\uEF20", "Marquee"),
    ("\uEF2C", "Chrome Close Contrast"),
    ("\uEF2D", "Chrome Minimize Contrast"),
    ("\uEF2E", "Chrome Maximize Contrast"),
    ("\uEF2F", "Chrome Restore Contrast"),
    ("\uEF31", "Traffic Light"),
    ("\uEF3B", "Replay"),
    ("\uEF3C", "Eyedropper"),
    ("\uEF3D", "Line Display"),
    ("\uEF3E", "PINPad"),
    ("\uEF3F", "Signature Capture"),
    ("\uEF40", "Chip Card Credit Card Reader"),
    ("\uEF58", "Player Settings"),
    ("\uEF6B", "Landscape Orientation"),
    ("\uEF90", "Flow"),
    ("\uEFA5", "Touchpad"),
    ("\uEFA9", "Speech"),
    ("\uF000", "Knowledge Article"),
    ("\uF003", "Relationship"),
    ("\uF080", "Default APN"),
    ("\uF081", "User APN"),
    ("\uF085", "Double Pinyin"),
    ("\uF08C", "Blue Light"),
    ("\uF093", "Button A"),
    ("\uF094", "Button B"),
    ("\uF095", "Button Y"),
    ("\uF096", "Button X"),
    ("\uF0AD", "Arrow Up 8"),
    ("\uF0AE", "Arrow Down 8"),
    ("\uF0AF", "Arrow Right 8"),
    ("\uF0B0", "Arrow Left 8"),
    ("\uF0B2", "Quarentined Items"),
    ("\uF0B3", "Quarentined Items Mirrored"),
    ("\uF0B4", "Protractor"),
    ("\uF0B5", "Checklist Mirrored"),
    ("\uF0B6", "Status Circle 7"),
    ("\uF0B7", "Status Checkmark 7"),
    ("\uF0B8", "Status Error Circle 7"),
    ("\uF0B9", "Connected"),
    ("\uF0C6", "Pencil Fill"),
    ("\uF0C7", "Calligraphy Fill"),
    ("\uF0CA", "Quarter Star Left"),
    ("\uF0CB", "Quarter Star Right"),
    ("\uF0CC", "Three Quarter Star Left"),
    ("\uF0CD", "Three Quarter Star Right"),
    ("\uF0CE", "Quiet Hours Badge 12"),
    ("\uF0D2", "Back Mirrored"),
    ("\uF0D3", "Forward Mirrored"),
    ("\uF0D5", "Chrome Back Contrast"),
    ("\uF0D6", "Chrome Back Contrast Mirrored"),
    ("\uF0D7", "Chrome Back To Window Contrast"),
    ("\uF0D8", "Chrome Full Screen Contrast"),
    ("\uF0E2", "Grid View"),
    ("\uF0E3", "Clipboard List"),
    ("\uF0E4", "Clipboard List Mirrored"),
    ("\uF0E5", "Outline Quarter Star Left"),
    ("\uF0E6", "Outline Quarter Star Right"),
    ("\uF0E7", "Outline Half Star Left"),
    ("\uF0E8", "Outline Half Star Right"),
    ("\uF0E9", "Outline Three Quarter Star Left"),
    ("\uF0EA", "Outline Three Quarter Star Right"),
    ("\uF0EB", "Spatial Volume 0"),
    ("\uF0EC", "Spatial Volume 1"),
    ("\uF0ED", "Spatial Volume 2"),
    ("\uF0EE", "Spatial Volume 3"),
    ("\uF0F7", "Outline Star Left Half"),
    ("\uF0F8", "Outline Star Right Half"),
    ("\uF0F9", "Chrome Annotate Contrast"),
    ("\uF0FB", "Defender Badge 12"),
    ("\uF103", "Detachable PC"),
    ("\uF108", "Left Stick"),
    ("\uF109", "Right Stick"),
    ("\uF10A", "Trigger Left"),
    ("\uF10B", "Trigger Right"),
    ("\uF10C", "Bumper Left"),
    ("\uF10D", "Bumper Right"),
    ("\uF10E", "Dpad"),
    ("\uF110", "English Punctuation"),
    ("\uF111", "Chinese Punctuation"),
    ("\uF119", "HMD"),
    ("\uF11B", "Ctrl Spatial Right"),
    ("\uF126", "Pagination Dot Outline 10"),
    ("\uF127", "Pagination Dot Solid 10"),
    ("\uF128", "Stroke Erase 2"),
    ("\uF129", "Small Erase"),
    ("\uF12A", "Large Erase"),
    ("\uF12B", "Folder Horizontal"),
    ("\uF12E", "Microphone Listening"),
    ("\uF12F", "Status Exclamation Circle 7"),
    ("\uF131", "Video 360"),
    ("\uF133", "Giftbox Open"),
    ("\uF136", "Status Circle Outer"),
    ("\uF137", "Status Circle Inner"),
    ("\uF138", "Status Circle Ring"),
    ("\uF139", "Status Triangle Outer"),
    ("\uF13A", "Status Triangle Inner"),
    ("\uF13B", "Status Triangle Exclamation"),
    ("\uF13C", "Status Circle Exclamation"),
    ("\uF13D", "Status Circle Error X"),
    ("\uF13E", "Status Circle Checkmark"),
    ("\uF13F", "Status Circle Info"),
    ("\uF140", "Status Circle Block"),
    ("\uF141", "Status Circle Block 2"),
    ("\uF142", "Status Circle Question Mark"),
    ("\uF143", "Status Circle Sync"),
    ("\uF146", "Dial 1"),
    ("\uF147", "Dial 2"),
    ("\uF148", "Dial 3"),
    ("\uF149", "Dial 4"),
    ("\uF14A", "Dial 5"),
    ("\uF14B", "Dial 6"),
    ("\uF14C", "Dial 7"),
    ("\uF14D", "Dial 8"),
    ("\uF14E", "Dial 9"),
    ("\uF14F", "Dial 10"),
    ("\uF150", "Dial 11"),
    ("\uF151", "Dial 12"),
    ("\uF152", "Dial 13"),
    ("\uF153", "Dial 14"),
    ("\uF154", "Dial 15"),
    ("\uF155", "Dial 16"),
    ("\uF156", "Dial Shape 1"),
    ("\uF157", "Dial Shape 2"),
    ("\uF158", "Dial Shape 3"),
    ("\uF159", "Dial Shape 4"),
    ("\uF161", "Toll Solid"),
    ("\uF163", "Traffic Congestion Solid"),
    ("\uF164", "Explore Content Single"),
    ("\uF165", "Collapse Content"),
    ("\uF166", "Collapse Content Single"),
    ("\uF167", "Info Solid"),
    ("\uF168", "Group List"),
    ("\uF169", "Caret Bottom Right Solid Center 8"),
    ("\uF16A", "Progress Ring Dots"),
    ("\uF16B", "Checkbox 14"),
    ("\uF16C", "Checkbox Composite 14"),
    ("\uF16D", "Checkbox Indeterminate Combo 14"),
    ("\uF16E", "Checkbox Indeterminate Combo"),
    ("\uF175", "Status Pause 7"),
    ("\uF17F", "Character Appearance"),
    ("\uF180", "Lexicon"),
    ("\uF182", "Screen Time"),
    ("\uF191", "Headless Device"),
    ("\uF193", "Network Sharing"),
    ("\uF19D", "Eye Gaze"),
    ("\uF1AD", "Windows Insider"),
    ("\uF1CB", "Chrome Switch"),
    ("\uF1CC", "Chrome Switch Contast"),
    ("\uF1D8", "Status Checkmark"),
    ("\uF1D9", "Status Checkmark Left"),
    ("\uF20C", "Keyboard Left Aligned"),
    ("\uF20D", "Keyboard Right Aligned"),
    ("\uF210", "Keyboard Settings"),
    ("\uF211", "Network Physical"),
    ("\uF22C", "IOT"),
    ("\uF22E", "Unknown Mirrored"),
    ("\uF246", "View Dashboard"),
    ("\uF259", "Exploit Protection Settings"),
    ("\uF260", "Keyboard Narrow"),
    ("\uF261", "Keyboard12Key"),
    ("\uF26B", "Keyboard Dock"),
    ("\uF26C", "Keyboard Undock"),
    ("\uF26D", "Keyboard Left Dock"),
    ("\uF26E", "Keyboard Right Dock"),
    ("\uF270", "Ear"),
    ("\uF271", "Pointer Hand"),
    ("\uF272", "Bullseye"),
    ("\uF2B7", "Locale Language"),
    ("\uF32A", "Passive Authentication"),
    ("\uF384", "Network Offline"),
    ("\uF385", "Network Connected"),
    ("\uF386", "Network Connected Checkmark"),
    ("\uF3B1", "Sign Out"),
    ("\uF3CC", "Status Info"),
    ("\uF3CD", "Status Info Left"),
    ("\uF3E2", "Nearby Sharing"),
    ("\uF3E7", "Ctrl Spatial Left"),
    ("\uF404", "Interactive Dashboard"),
    ("\uF406", "Clipping Tool"),
    ("\uF407", "Rectangular Clipping"),
    ("\uF408", "Free Form Clipping"),
    ("\uF413", "Copy To"),
    ("\uF439", "Dynamic Lock"),
    ("\uF45E", "Pen Tips"),
    ("\uF45F", "Pen Tips Mirrored"),
    ("\uF460", "HWPJoin"),
    ("\uF461", "HWPInsert"),
    ("\uF462", "HWPStrike Through"),
    ("\uF463", "HWPScratch Out"),
    ("\uF464", "HWPSplit"),
    ("\uF465", "HWPNew Line"),
    ("\uF466", "HWPOverwrite"),
    ("\uF473", "Mob Wifi Warning 1"),
    ("\uF474", "Mob Wifi Warning 2"),
    ("\uF475", "Mob Wifi Warning 3"),
    ("\uF476", "Mob Wifi Warning 4"),
    ("\uF49A", "Globe 2"),
    ("\uF4A9", "GIF"),
    ("\uF4AA", "Sticker 2"),
    ("\uF4BE", "Surface Hub Selected"),
    ("\uF4BF", "Holo Lens Selected"),
    ("\uF4C0", "Earbud"),
    ("\uF4C3", "Mix Volumes"),
    ("\uF540", "Safe"),
    ("\uF552", "Laptop Secure"),
    ("\uF56D", "Print Default"),
    ("\uF56E", "Page Mirrored"),
    ("\uF56F", "Landscape Orientation Mirrored"),
    ("\uF570", "Color Off"),
    ("\uF571", "Print All Pages"),
    ("\uF572", "Print Custom Range"),
    ("\uF573", "Page Margin Portrait Narrow"),
    ("\uF574", "Page Margin Portrait Normal"),
    ("\uF575", "Page Margin Portrait Moderate"),
    ("\uF576", "Page Margin Portrait Wide"),
    ("\uF577", "Page Margin Landscape Narrow"),
    ("\uF578", "Page Margin Landscape Normal"),
    ("\uF579", "Page Margin Landscape Moderate"),
    ("\uF57A", "Page Margin Landscape Wide"),
    ("\uF57B", "Collate Landscape"),
    ("\uF57C", "Collate Portrait"),
    ("\uF57D", "Collate Portrait Separated"),
    ("\uF57E", "Duplex Landscape One Sided"),
    ("\uF57F", "Duplex Landscape One Sided Mirrored"),
    ("\uF580", "Duplex Landscape Two Sided Long Edge"),
    ("\uF581", "Duplex Landscape Two Sided Long Edge Mirrored"),
    ("\uF582", "Duplex Landscape Two Sided Short Edge"),
    ("\uF583", "Duplex Landscape Two Sided Short Edge Mirrored"),
    ("\uF584", "Duplex Portrait One Sided"),
    ("\uF585", "Duplex Portrait One Sided Mirrored"),
    ("\uF586", "Duplex Portrait Two Sided Long Edge"),
    ("\uF587", "Duplex Portrait Two Sided Long Edge Mirrored"),
    ("\uF588", "Duplex Portrait Two Sided Short Edge"),
    ("\uF589", "Duplex Portrait Two Sided Short Edge Mirrored"),
    ("\uF58A", "PPSOne Landscape"),
    ("\uF58B", "PPSTwo Landscape"),
    ("\uF58C", "PPSTwo Portrait"),
    ("\uF58D", "PPSFour Landscape"),
    ("\uF58E", "PPSFour Portrait"),
    ("\uF58F", "Hole Punch Off"),
    ("\uF590", "Hole Punch Portrait Left"),
    ("\uF591", "Hole Punch Portrait Right"),
    ("\uF592", "Hole Punch Portrait Top"),
    ("\uF593", "Hole Punch Portrait Bottom"),
    ("\uF594", "Hole Punch Landscape Left"),
    ("\uF595", "Hole Punch Landscape Right"),
    ("\uF596", "Hole Punch Landscape Top"),
    ("\uF597", "Hole Punch Landscape Bottom"),
    ("\uF598", "Stapling Off"),
    ("\uF599", "Stapling Portrait Top Left"),
    ("\uF59A", "Stapling Portrait Top Right"),
    ("\uF59B", "Stapling Portrait Bottom Right"),
    ("\uF59C", "Stapling Portrait Two Left"),
    ("\uF59D", "Stapling Portrait Two Right"),
    ("\uF59E", "Stapling Portrait Two Top"),
    ("\uF59F", "Stapling Portrait Two Bottom"),
    ("\uF5A0", "Stapling Portrait Book Binding"),
    ("\uF5A1", "Stapling Landscape Top Left"),
    ("\uF5A2", "Stapling Landscape Top Right"),
    ("\uF5A3", "Stapling Landscape Bottom Left"),
    ("\uF5A4", "Stapling Landscape Bottom Right"),
    ("\uF5A5", "Stapling Landscape Two Left"),
    ("\uF5A6", "Stapling Landscape Two Right"),
    ("\uF5A7", "Stapling Landscape Two Top"),
    ("\uF5A8", "Stapling Landscape Two Bottom"),
    ("\uF5A9", "Stapling Landscape Book Binding"),
    ("\uF5AA", "Status Data Transfer Roaming"),
    ("\uF5AB", "Mob SIMError"),
    ("\uF5AC", "Collate Landscape Separated"),
    ("\uF5AD", "PPSOne Portrait"),
    ("\uF5AE", "Stapling Portrait Bottom Left"),
    ("\uF5B0", "Play Solid"),
    ("\uF5E7", "Repeat Off"),
    ("\uF5ED", "Set"),
    ("\uF5EE", "Set Solid"),
    ("\uF5EF", "Fuzzy Reading"),
    ("\uF5F2", "Vertical Battery 0"),
    ("\uF5F3", "Vertical Battery 1"),
    ("\uF5F4", "Vertical Battery 2"),
    ("\uF5F5", "Vertical Battery 3"),
    ("\uF5F6", "Vertical Battery 4"),
    ("\uF5F7", "Vertical Battery 5"),
    ("\uF5F8", "Vertical Battery 6"),
    ("\uF5F9", "Vertical Battery 7"),
    ("\uF5FA", "Vertical Battery 8"),
    ("\uF5FB", "Vertical Battery 9"),
    ("\uF5FC", "Vertical Battery 10"),
    ("\uF5FD", "Vertical Battery Charging 0"),
    ("\uF5FE", "Vertical Battery Charging 1"),
    ("\uF5FF", "Vertical Battery Charging 2"),
    ("\uF600", "Vertical Battery Charging 3"),
    ("\uF601", "Vertical Battery Charging 4"),
    ("\uF602", "Vertical Battery Charging 5"),
    ("\uF603", "Vertical Battery Charging 6"),
    ("\uF604", "Vertical Battery Charging 7"),
    ("\uF605", "Vertical Battery Charging 8"),
    ("\uF606", "Vertical Battery Charging 9"),
    ("\uF607", "Vertical Battery Charging 10"),
    ("\uF608", "Vertical Battery Unknown"),
    ("\uF614", "Double Portrait"),
    ("\uF615", "Double Landscape"),
    ("\uF616", "Single Portrait"),
    ("\uF617", "Single Landscape"),
    ("\uF618", "SIMError"),
    ("\uF619", "SIMMissing"),
    ("\uF61A", "SIMLock"),
    ("\uF61B", "e SIM"),
    ("\uF61C", "e SIMNo Profile"),
    ("\uF61D", "e SIMLocked"),
    ("\uF61E", "e SIMBusy"),
    ("\uF61F", "Noise Cancelation"),
    ("\uF620", "Noise Cancelation Off"),
    ("\uF623", "Music Sharing"),
    ("\uF624", "Music Sharing Off"),
    ("\uF63C", "Circle Shape Solid"),
    ("\uF657", "Wifi Call Bars"),
    ("\uF658", "Wifi Call 0"),
    ("\uF659", "Wifi Call 1"),
    ("\uF65A", "Wifi Call 2"),
    ("\uF65B", "Wifi Call 3"),
    ("\uF65C", "Wifi Call 4"),
    ("\uF69E", "CHTLanguage Bar"),
    ("\uF6BA", "Emoji Tab More Symbols"),
    ("\uF6FA", "Web Search"),
    ("\uF712", "Kiosk"),
    ("\uF714", "RTTLogo"),
    ("\uF715", "Voice Call"),
    ("\uF716", "Go To Message"),
    ("\uF71A", "Return To Call"),
    ("\uF71C", "Start Presenting"),
    ("\uF71D", "Stop Presenting"),
    ("\uF71E", "Productivity Mode"),
    ("\uF738", "Set History Status"),
    ("\uF739", "Set History Status 2"),
    ("\uF73D", "Keyboardsettings 20"),
    ("\uF73E", "One Handed Right 20"),
    ("\uF73F", "One Handed Left 20"),
    ("\uF740", "Split 20"),
    ("\uF741", "Full 20"),
    ("\uF742", "Handwriting 20"),
    ("\uF743", "Cheveron Left 20"),
    ("\uF744", "Cheveron Left 32"),
    ("\uF745", "Cheveron Right 20"),
    ("\uF746", "Cheveron Right 32"),
    ("\uF781", "Mic Off 2"),
    ("\uF785", "Delivery Optimization"),
    ("\uF78A", "Cancel Medium"),
    ("\uF78B", "Search Medium"),
    ("\uF78C", "Accept Medium"),
    ("\uF78D", "Reveal Password Medium"),
    ("\uF7AD", "Delete Word"),
    ("\uF7AE", "Delete Word Fill"),
    ("\uF7AF", "Delete Lines"),
    ("\uF7B0", "Delete Lines Fill"),
    ("\uF7B1", "Instert Words"),
    ("\uF7B2", "Instert Words Fill"),
    ("\uF7B3", "Join Words"),
    ("\uF7B4", "Join Words Fill"),
    ("\uF7B5", "Overwrite Words"),
    ("\uF7B6", "Overwrite Words Fill"),
    ("\uF7B7", "Add New Line"),
    ("\uF7B8", "Add New Line Fill"),
    ("\uF7B9", "Overwrite Words Korean"),
    ("\uF7BA", "Overwrite Words Fill Korean"),
    ("\uF7BB", "Education Icon"),
    ("\uF7ED", "Window Snipping"),
    ("\uF7EE", "Video Capture"),
    ("\uF809", "Status Secured"),
    ("\uF83B", "Narrator App"),
    ("\uF83D", "Power Button Update"),
    ("\uF83E", "Restart Update"),
    ("\uF83F", "Update Status Dot"),
    ("\uF847", "Eject"),
]

def update_search_index(search_engine):
    search_writer = search_engine.writer()

    for code, label in segoe_symbols:
        search_writer.add_document(
            module="segoemdl2",
            fontlabel="Segoe MDL2 Assets",
            fontname="Segoe MDL2 Assets",
            unicode=code,
            label=label,
            keywords=label.lower().split()
        )

    search_writer.commit()


segoe_symbols1 = []
segoe_symbols2 = []
segoe_symbols3 = []
segoe_symbols4 = []

chunk_size = ceil(len(segoe_symbols)/4.0)
for i,char in enumerate(segoe_symbols):
    if 0 <= i <= chunk_size:
        segoe_symbols1.append(("Segoe MDL2 Assets", char[0], char[1], "Segoe MDL2 Assets > 1"))
    elif chunk_size < i <= 2*chunk_size:
        segoe_symbols2.append(("Segoe MDL2 Assets", char[0], char[1], "Segoe MDL2 Assets > 2"))
    elif 2*chunk_size < i <= 3*chunk_size:
        segoe_symbols3.append(("Segoe MDL2 Assets", char[0], char[1], "Segoe MDL2 Assets > 3"))
    else:
        segoe_symbols4.append(("Segoe MDL2 Assets", char[0], char[1], "Segoe MDL2 Assets > 4"))


# define the menu parts
menu_title = "Segoe MDL2 Assets"


menus = [
    PPTSymbolsGallery(label="Seite 1 ({})".format(len(segoe_symbols1)), symbols=segoe_symbols1, columns=16),
    PPTSymbolsGallery(label="Seite 2 ({})".format(len(segoe_symbols2)), symbols=segoe_symbols2, columns=16),
    PPTSymbolsGallery(label="Seite 3 ({})".format(len(segoe_symbols3)), symbols=segoe_symbols3, columns=16),
    PPTSymbolsGallery(label="Seite 4 ({})".format(len(segoe_symbols4)), symbols=segoe_symbols4, columns=16),
]


