# -*- coding: utf-8 -*-

# https://docs.microsoft.com/de-de/windows/uwp/design/style/segoe-ui-symbol-font

import bkt
from bkt.library.powerpoint import PPTSymbolsGallery

symbols_symbol = [
    ("Segoe UI Symbol", u"\uE100", "Skip Back"),
    ("Segoe UI Symbol", u"\uE101", "Skip Ahead"),
    ("Segoe UI Symbol", u"\uE102", "Play"),
    ("Segoe UI Symbol", u"\uE103", "Pause"),
    ("Segoe UI Symbol", u"\uE104", "Edit"),
    ("Segoe UI Symbol", u"\uE105", "Save"),
    ("Segoe UI Symbol", u"\uE106", "Delete"),
    ("Segoe UI Symbol", u"\uE107", "Discard"),
    ("Segoe UI Symbol", u"\uE108", "Remove"),
    ("Segoe UI Symbol", u"\uE109", "Add"),
    ("Segoe UI Symbol", u"\uE10A", "No"),
    ("Segoe UI Symbol", u"\uE10B", "Yes"),
    ("Segoe UI Symbol", u"\uE10C", "More"),
    ("Segoe UI Symbol", u"\uE10D", "Redo"),
    ("Segoe UI Symbol", u"\uE10E", "Undo"),
    ("Segoe UI Symbol", u"\uE10F", "Home"),
    ("Segoe UI Symbol", u"\uE110", "Out"),
    ("Segoe UI Symbol", u"\uE111", "Next"),
    ("Segoe UI Symbol", u"\uE112", "Previous"),
    ("Segoe UI Symbol", u"\uE113", "Favorite"),
    ("Segoe UI Symbol", u"\uE114", "Photo"),
    ("Segoe UI Symbol", u"\uE115", "Settings"),
    ("Segoe UI Symbol", u"\uE116", "Video"),
    ("Segoe UI Symbol", u"\uE117", "Refresh"),
    ("Segoe UI Symbol", u"\uE118", "Download"),
    ("Segoe UI Symbol", u"\uE119", "Mail"),
    ("Segoe UI Symbol", u"\uE11A", "Search"),
    ("Segoe UI Symbol", u"\uE11B", "Help"),
    ("Segoe UI Symbol", u"\uE11C", "Upload"),
    ("Segoe UI Symbol", u"\uE11D", "Emoji"),
    ("Segoe UI Symbol", u"\uE11E", "Two Page"),
    ("Segoe UI Symbol", u"\uE11F", "Upload"),
    ("Segoe UI Symbol", u"\uE120", "Forward Mail"),
    ("Segoe UI Symbol", u"\uE121", "Clock"),
    ("Segoe UI Symbol", u"\uE122", "Send"),
    ("Segoe UI Symbol", u"\uE123", "Crop"),
    ("Segoe UI Symbol", u"\uE124", "Rotate Camera"),
    ("Segoe UI Symbol", u"\uE125", "People"),
    ("Segoe UI Symbol", u"\uE126", "Close Pane"),
    ("Segoe UI Symbol", u"\uE127", "Open Pane"),
    ("Segoe UI Symbol", u"\uE128", "World"),
    ("Segoe UI Symbol", u"\uE129", "Flag"),
    ("Segoe UI Symbol", u"\uE12A", "Preview Link"),
    ("Segoe UI Symbol", u"\uE12B", "Globe"),
    ("Segoe UI Symbol", u"\uE12C", "Trim"),
    ("Segoe UI Symbol", u"\uE12D", "Attach Camera"),
    ("Segoe UI Symbol", u"\uE12E", "Zoom In"),
    ("Segoe UI Symbol", u"\uE12F", "Bookmarks"),
    ("Segoe UI Symbol", u"\uE130", "Document"),
    ("Segoe UI Symbol", u"\uE131", "Protected Document"),
    ("Segoe UI Symbol", u"\uE132", "Page"),
    ("Segoe UI Symbol", u"\uE133", "Bullets"),
    ("Segoe UI Symbol", u"\uE134", "Comment"),
    ("Segoe UI Symbol", u"\uE135", "Mail2"),
    ("Segoe UI Symbol", u"\uE136", "Contact Info"),
    ("Segoe UI Symbol", u"\uE137", "Hang Up"),
    ("Segoe UI Symbol", u"\uE138", "View All"),
    ("Segoe UI Symbol", u"\uE139", "Map Pin"),
    ("Segoe UI Symbol", u"\uE13A", "Phone"),
    ("Segoe UI Symbol", u"\uE13B", "Video Chat"),
    ("Segoe UI Symbol", u"\uE13C", "Switch"),
    ("Segoe UI Symbol", u"\uE13D", "Contact"),
    ("Segoe UI Symbol", u"\uE13E", "Rename"),
    ("Segoe UI Symbol", u"\uE141", "Pin"),
    ("Segoe UI Symbol", u"\uE142", "Music Info"),
    ("Segoe UI Symbol", u"\uE143", "Go"),
    ("Segoe UI Symbol", u"\uE144", "Keyboard"),
    ("Segoe UI Symbol", u"\uE145", "Dock Left"),
    ("Segoe UI Symbol", u"\uE146", "Dock Right"),
    ("Segoe UI Symbol", u"\uE147", "Dock Bottom"),
    ("Segoe UI Symbol", u"\uE148", "Remote"),
    ("Segoe UI Symbol", u"\uE149", "Sync"),
    ("Segoe UI Symbol", u"\uE14A", "Rotate"),
    ("Segoe UI Symbol", u"\uE14B", "Shuffle"),
    ("Segoe UI Symbol", u"\uE14C", "List"),
    ("Segoe UI Symbol", u"\uE14D", "Shop"),
    ("Segoe UI Symbol", u"\uE14E", "Select All"),
    ("Segoe UI Symbol", u"\uE14F", "Orientation"),
    ("Segoe UI Symbol", u"\uE150", "Import"),
    ("Segoe UI Symbol", u"\uE151", "Import All"),
    ("Segoe UI Symbol", u"\uE155", "Browse Photos"),
    ("Segoe UI Symbol", u"\uE156", "Webcam"),
    ("Segoe UI Symbol", u"\uE158", "Pictures"),
    ("Segoe UI Symbol", u"\uE159", "Save Local"),
    ("Segoe UI Symbol", u"\uE15A", "Caption"),
    ("Segoe UI Symbol", u"\uE15B", "Stop"),
    ("Segoe UI Symbol", u"\uE15C", "Show Results"),
    ("Segoe UI Symbol", u"\uE15D", "Volume"),
    ("Segoe UI Symbol", u"\uE15E", "Repair"),
    ("Segoe UI Symbol", u"\uE15F", "Message"),
    ("Segoe UI Symbol", u"\uE160", "Page2"),
    ("Segoe UI Symbol", u"\uE161", "Day"),
    ("Segoe UI Symbol", u"\uE162", "Week"),
    ("Segoe UI Symbol", u"\uE163", "Calendar"),
    ("Segoe UI Symbol", u"\uE164", "Characters"),
    ("Segoe UI Symbol", u"\uE165", "Reply All"),
    ("Segoe UI Symbol", u"\uE166", "Read"),
    ("Segoe UI Symbol", u"\uE167", "Link"),
    ("Segoe UI Symbol", u"\uE168", "Accounts"),
    ("Segoe UI Symbol", u"\uE169", "Show Bcc"),
    ("Segoe UI Symbol", u"\uE16A", "Hide Bcc"),
    ("Segoe UI Symbol", u"\uE16B", "Cut"),
    ("Segoe UI Symbol", u"\uE16C", "Attach"),
    ("Segoe UI Symbol", u"\uE16D", "Paste"),
    ("Segoe UI Symbol", u"\uE16E", "Filter"),
    ("Segoe UI Symbol", u"\uE16F", "Copy"),
    ("Segoe UI Symbol", u"\uE170", "Emoji2"),
    ("Segoe UI Symbol", u"\uE171", "Important"),
    ("Segoe UI Symbol", u"\uE172", "Reply"),
    ("Segoe UI Symbol", u"\uE173", "Slideshow"),
    ("Segoe UI Symbol", u"\uE174", "Sort"),
    ("Segoe UI Symbol", u"\uE178", "Manage"),
    ("Segoe UI Symbol", u"\uE179", "All Apps"),
    ("Segoe UI Symbol", u"\uE17A", "Disconnect Drive"),
    ("Segoe UI Symbol", u"\uE17B", "Map Drive"),
    ("Segoe UI Symbol", u"\uE17C", "New Window"),
    ("Segoe UI Symbol", u"\uE17D", "Open With"),
    ("Segoe UI Symbol", u"\uE181", "Presence"),
    ("Segoe UI Symbol", u"\uE182", "Priority"),
    ("Segoe UI Symbol", u"\uE183", "Skydrive"),
    ("Segoe UI Symbol", u"\uE184", "Today"),
    ("Segoe UI Symbol", u"\uE185", "Font"),
    ("Segoe UI Symbol", u"\uE186", "Font Color"),
    ("Segoe UI Symbol", u"\uE187", "Contact"),
    ("Segoe UI Symbol", u"\uE188", "Folder"),
    ("Segoe UI Symbol", u"\uE189", "Audio"),
    ("Segoe UI Symbol", u"\uE18A", "Placeholder"),
    ("Segoe UI Symbol", u"\uE18B", "View"),
    ("Segoe UI Symbol", u"\uE18C", "Set Lockscreen"),
    ("Segoe UI Symbol", u"\uE18D", "Set Title"),
    ("Segoe UI Symbol", u"\uE190", "Cc"),
    ("Segoe UI Symbol", u"\uE191", "Stop Slideshow"),
    ("Segoe UI Symbol", u"\uE192", "Permisions"),
    ("Segoe UI Symbol", u"\uE193", "Highlight"),
    ("Segoe UI Symbol", u"\uE194", "Disable Updates"),
    ("Segoe UI Symbol", u"\uE195", "Unfavorite"),
    ("Segoe UI Symbol", u"\uE196", "Unpin"),
    ("Segoe UI Symbol", u"\uE197", "Open Loal"),
    ("Segoe UI Symbol", u"\uE198", "Mute"),
    ("Segoe UI Symbol", u"\uE199", "Italic"),
    ("Segoe UI Symbol", u"\uE19A", "Underline"),
    ("Segoe UI Symbol", u"\uE19B", "Bold"),
    ("Segoe UI Symbol", u"\uE19C", "Move to Folder"),
    ("Segoe UI Symbol", u"\uE19D", "Like/Dislike"),
    ("Segoe UI Symbol", u"\uE19E", "Dislike"),
    ("Segoe UI Symbol", u"\uE19F", "Like"),
    ("Segoe UI Symbol", u"\uE1A0", "Align Right"),
    ("Segoe UI Symbol", u"\uE1A1", "Align Center"),
    ("Segoe UI Symbol", u"\uE1A2", "Align Left"),
    ("Segoe UI Symbol", u"\uE1A3", "Zoom"),
    ("Segoe UI Symbol", u"\uE1A4", "Zoom Out"),
    ("Segoe UI Symbol", u"\uE1A5", "Open File"),
    ("Segoe UI Symbol", u"\uE1A6", "Other User"),
    ("Segoe UI Symbol", u"\uE1A7", "Admin"),
    ("Segoe UI Symbol", u"\uE1C3", "Street"),
    ("Segoe UI Symbol", u"\uE1C4", "Map"),
    ("Segoe UI Symbol", u"\uE1C5", "Clear Selection"),
    ("Segoe UI Symbol", u"\uE1C6", "Decrease Font"),
    ("Segoe UI Symbol", u"\uE1C7", "Increase Font"),
    ("Segoe UI Symbol", u"\uE1C8", "Font Size"),
    ("Segoe UI Symbol", u"\uE1C9", "Cellphone"),
    ("Segoe UI Symbol", u"\uE1CA", "Reshare"),
    ("Segoe UI Symbol", u"\uE1CB", "Tag"),
    ("Segoe UI Symbol", u"\uE1CC", "Repeat Once"),
    ("Segoe UI Symbol", u"\uE1CD", "Repeat All"),
    ("Segoe UI Symbol", u"\uE1CE", "Outline Star"),
    ("Segoe UI Symbol", u"\uE1CF", "Solid Star"),
    ("Segoe UI Symbol", u"\uE1D0", "Calculator"),
    ("Segoe UI Symbol", u"\uE1D1", "Directions"),
    ("Segoe UI Symbol", u"\uE1D2", "Target"),
    ("Segoe UI Symbol", u"\uE1D3", "Library"),
    ("Segoe UI Symbol", u"\uE1D4", "Phonebook"),
    ("Segoe UI Symbol", u"\uE1D5", "Memo"),
    ("Segoe UI Symbol", u"\uE1D6", "Microphone"),
    ("Segoe UI Symbol", u"\uE1D7", "Post Update"),
    ("Segoe UI Symbol", u"\uE1D8", "Back to Window"),
    ("Segoe UI Symbol", u"\uE1D9", "Full Screen"),
    ("Segoe UI Symbol", u"\uE1DA", "New Folder"),
    ("Segoe UI Symbol", u"\uE1DB", "Calendar Reply"),
    ("Segoe UI Symbol", u"\uE1DD", "Unsync Folder"),
    ("Segoe UI Symbol", u"\uE1DE", "Report Hacked"),
    ("Segoe UI Symbol", u"\uE1DF", "Sync Folder"),
    ("Segoe UI Symbol", u"\uE1E0", "BlockContact"),
    ("Segoe UI Symbol", u"\uE1E1", "Switch Apps"),
    ("Segoe UI Symbol", u"\uE1E2", "Add Friend"),
    ("Segoe UI Symbol", u"\uE1E3", "Touch Pointer"),
    ("Segoe UI Symbol", u"\uE1E4", "Go to Start"),
    ("Segoe UI Symbol", u"\uE1E5", "Zero Bars"),
    ("Segoe UI Symbol", u"\uE1E6", "One Bar"),
    ("Segoe UI Symbol", u"\uE1E7", "Two Bars"),
    ("Segoe UI Symbol", u"\uE1E8", "Three Bars"),
]

symbols_emoji = [
    ("Segoe UI Emoji", u"😀", "GRINNING FACE"),
    ("Segoe UI Emoji", u"😁", "GRINNING FACE WITH SMILING EYES"),
    ("Segoe UI Emoji", u"😂", "FACE WITH TEARS OF JOY"),
    ("Segoe UI Emoji", u"😃", "SMILING FACE WITH OPEN MOUTH"),
    ("Segoe UI Emoji", u"😄", "SMILING FACE WITH OPEN MOUTH AND SMILING EYES"),
    ("Segoe UI Emoji", u"😅", "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"),
    ("Segoe UI Emoji", u"😆", "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES"),
    ("Segoe UI Emoji", u"😇", "SMILING FACE WITH HALO"),
    ("Segoe UI Emoji", u"😈", "SMILING FACE WITH HORNS"),
    ("Segoe UI Emoji", u"😉", "WINKING FACE"),
    ("Segoe UI Emoji", u"😊", "SMILING FACE WITH SMILING EYES"),
    ("Segoe UI Emoji", u"😋", "FACE SAVOURING DELICIOUS FOOD"),
    ("Segoe UI Emoji", u"😌", "RELIEVED FACE"),
    ("Segoe UI Emoji", u"😍", "SMILING FACE WITH HEART-SHAPED EYES"),
    ("Segoe UI Emoji", u"😎", "SMILING FACE WITH SUNGLASSES"),
    ("Segoe UI Emoji", u"😏", "SMIRKING FACE"),
    ("Segoe UI Emoji", u"😐", "NEUTRAL FACE"),
    ("Segoe UI Emoji", u"😑", "EXPRESSIONLESS FACE"),
    ("Segoe UI Emoji", u"😒", "UNAMUSED FACE"),
    ("Segoe UI Emoji", u"😓", "FACE WITH COLD SWEAT"),
    ("Segoe UI Emoji", u"😔", "PENSIVE FACE"),
    ("Segoe UI Emoji", u"😕", "CONFUSED FACE"),
    ("Segoe UI Emoji", u"😖", "CONFOUNDED FACE"),
    ("Segoe UI Emoji", u"😗", "KISSING FACE"),
    ("Segoe UI Emoji", u"😘", "FACE THROWING A KISS"),
    ("Segoe UI Emoji", u"😙", "KISSING FACE WITH SMILING EYES"),
    ("Segoe UI Emoji", u"😚", "KISSING FACE WITH CLOSED EYES"),
    ("Segoe UI Emoji", u"😛", "FACE WITH STUCK-OUT TONGUE"),
    ("Segoe UI Emoji", u"😜", "FACE WITH STUCK-OUT TONGUE AND WINKING EYE"),
    ("Segoe UI Emoji", u"😝", "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES"),
    ("Segoe UI Emoji", u"😞", "DISAPPOINTED FACE"),
    ("Segoe UI Emoji", u"😟", "WORRIED FACE"),
    ("Segoe UI Emoji", u"😠", "ANGRY FACE"),
    ("Segoe UI Emoji", u"😡", "POUTING FACE"),
    ("Segoe UI Emoji", u"😢", "CRYING FACE"),
    ("Segoe UI Emoji", u"😣", "PERSEVERING FACE"),
    ("Segoe UI Emoji", u"😤", "FACE WITH LOOK OF TRIUMPH"),
    ("Segoe UI Emoji", u"😥", "DISAPPOINTED BUT RELIEVED FACE"),
    ("Segoe UI Emoji", u"😦", "FROWNING FACE WITH OPEN MOUTH"),
    ("Segoe UI Emoji", u"😧", "ANGUISHED FACE"),
    ("Segoe UI Emoji", u"😨", "FEARFUL FACE"),
    ("Segoe UI Emoji", u"😩", "WEARY FACE"),
    ("Segoe UI Emoji", u"😪", "SLEEPY FACE"),
    ("Segoe UI Emoji", u"😫", "TIRED FACE"),
    ("Segoe UI Emoji", u"😬", "GRIMACING FACE"),
    ("Segoe UI Emoji", u"😭", "LOUDLY CRYING FACE"),
    ("Segoe UI Emoji", u"😮", "FACE WITH OPEN MOUTH"),
    ("Segoe UI Emoji", u"😯", "HUSHED FACE"),
    ("Segoe UI Emoji", u"😰", "FACE WITH OPEN MOUTH AND COLD SWEAT"),
    ("Segoe UI Emoji", u"😱", "FACE SCREAMING IN FEAR"),
    ("Segoe UI Emoji", u"😲", "ASTONISHED FACE"),
    ("Segoe UI Emoji", u"😳", "FLUSHED FACE"),
    ("Segoe UI Emoji", u"😴", "SLEEPING FACE"),
    ("Segoe UI Emoji", u"😵", "DIZZY FACE"),
    ("Segoe UI Emoji", u"😶", "FACE WITHOUT MOUTH"),
    ("Segoe UI Emoji", u"😷", "FACE WITH MEDICAL MASK"),
    ("Segoe UI Emoji", u"😸", "GRINNING CAT FACE WITH SMILING EYES"),
    ("Segoe UI Emoji", u"😹", "CAT FACE WITH TEARS OF JOY"),
    ("Segoe UI Emoji", u"😺", "SMILING CAT FACE WITH OPEN MOUTH"),
    ("Segoe UI Emoji", u"😻", "SMILING CAT FACE WITH HEART-SHAPED EYES"),
    ("Segoe UI Emoji", u"😼", "CAT FACE WITH WRY SMILE"),
    ("Segoe UI Emoji", u"😽", "KISSING CAT FACE WITH CLOSED EYES"),
    ("Segoe UI Emoji", u"😾", "POUTING CAT FACE"),
    ("Segoe UI Emoji", u"😿", "CRYING CAT FACE"),
    ("Segoe UI Emoji", u"🙀", "WEARY CAT FACE"),
    ("Segoe UI Emoji", u"🙁", "SLIGHTLY FROWNING FACE"),
    ("Segoe UI Emoji", u"🙂", "SLIGHTLY SMILING FACE"),
    ("Segoe UI Emoji", u"🙃", "UPSIDE-DOWN FACE"),
    ("Segoe UI Emoji", u"🙄", "FACE WITH ROLLING EYES"),
    ("Segoe UI Emoji", u"🙅", "FACE WITH NO GOOD GESTURE"),
    ("Segoe UI Emoji", u"🙆", "FACE WITH OK GESTURE"),
    ("Segoe UI Emoji", u"🙇", "PERSON BOWING DEEPLY"),
    ("Segoe UI Emoji", u"🙈", "SEE-NO-EVIL MONKEY"),
    ("Segoe UI Emoji", u"🙉", "HEAR-NO-EVIL MONKEY"),
    ("Segoe UI Emoji", u"🙊", "SPEAK-NO-EVIL MONKEY"),
    ("Segoe UI Emoji", u"🙋", "HAPPY PERSON RAISING ONE HAND"),
    ("Segoe UI Emoji", u"🙌", "PERSON RAISING BOTH HANDS IN CELEBRATION"),
    ("Segoe UI Emoji", u"🙍", "PERSON FROWNING"),
    ("Segoe UI Emoji", u"🙎", "PERSON WITH POUTING FACE"),
    ("Segoe UI Emoji", u"🙏", "PERSON WITH FOLDED HANDS"),
]


# define the menu parts
menu_title = "Segoe UI"

menus = [
    PPTSymbolsGallery(label="Segoe UI Symbol", symbols=symbols_symbol, columns=16),
    PPTSymbolsGallery(label="Segoe UI Emoji", symbols=symbols_emoji, columns=16),
]


